### ISSUE TITLE
Support submodules

### ISSUE THREAD

**Issue by languitar** [android-password-store/Android-Password-Store#111]
I am using submodules in the git repository to aggregate multiple password repositories. Please add support to clone and pull recursively.

**Comment by XaosTX** [comment]
This app is phenomenal!  The only thing keeping me from using it as my daily driver for passwords is that I too use submodules to segregate my password-store between personal, work, shared with family members, etc.

What can any of us do to help with this?

**Comment by msfjarvis** [comment]
> This app is phenomenal!  The only thing keeping me from using it as my daily driver for passwords is that I too use submodules to segregate my password-store between personal, work, shared with family members, etc.
> 
> What can any of us do to help with this?

Not a whole lot other than collating the comments from https://github.com/android-password-store/Android-Password-Store/pull/348 and putting together a new pull request. It's not a priority at the moment so I won't be working on it myself but I'm happy to help someone else along the process.

**Comment by msfjarvis** [comment]
Closing as part of [issue tracker cleanup](https://github.com/android-password-store/Android-Password-Store/discussions/1836).
