### ISSUE TITLE
[Documentation Improvement] Backup process missing something?

### ISSUE THREAD

**Issue by oren** [android-password-store/Android-Password-Store#1248]
My laptop's hardware crashed and i am trying to restore my password store on a new laptop. My backup was created using the process [documented on the wiki](https://github.com/android-password-store/Android-Password-Store/wiki/Ubuntu-Android-Guide-backup). 

I restored the .password-store folder and the gpg keys using the commands on that wiki page:

Restore the pass data folder

```
cp -r ~/password-store ~/.password-store
```

Restore the gpg keys

```
gpg2 --import secret.gpg
gpg --edit-key <KEY_ID>
gpg>trust
enter '5'
```

but I see the following message:
```
gpg: decryption failed: No secret key
```

Here is the output of gpg -k:

```
gpg -k
/home/oren/.gnupg/pubring.kbx
-----------------------------
pub   rsa4096 2020-02-25 [SC]
      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
uid           [ultimate] my name  <myname@gmail.com>
sub   rsa4096 2020-02-25 [E]
```

Any ideas what's going on? is the process of backup missing something? I am not familiar with managing gpg keys so any advice would be appreciated!

**Comment by msfjarvis** [comment]
How did you export your secret key? `gpg --export-secret-keys <key id>` is the only way to get our secret keys in a form that can be imported elsewhere.
