### ISSUE TITLE
Feature-Request: Inputstick support

### ISSUE THREAD

**Issue by fanningert** [android-password-store/Android-Password-Store#145]
It would be great when `Password Store` support Inputstick.

**Android-InputStick API:**
http://inputstick.com/index.php/en/developers-en/inputstick-api-en
https://github.com/inputstick/InputStickAPI-Android

**Comment by JasperWeiss** [comment]
This would solve #144. It shouldn't require InputstickUtility though. It'd be better to instead use the direct connection mentioned in the description.

**Comment by JasperWeiss** [comment]
Just noticed that it doesn't work natively with any Bluetooth enabled device but requires a special usb dongle. That's kind of disappointing : /

**Comment by fanningert** [comment]
Yea, that is right. What it is working great. And the great point. It is working on every pc/laptop what has not a bluetooth connector. Or when it is not possible on security to install a bluetooth device (example in our company bluetooth is deactivated on every laptop). And this usb toogle is a input device for every laptop/pc.

**Comment by JasperWeiss** [comment]
It is quite handy but given the amount of people who are actually going to use this (and thus buying the thing) I'm not sure if it's worth the effort from the developers perspective.
That said, a universal way to get passwords on other devices without having to install/buy/setup anything is still kind of a must for this app to be usefill for most people.
A yubikey like system for passwords (not 2 factor authentication) would be amazing and I kinda hope this app could at some point be just that.

**Comment by Ajedi32** [comment]
> That said, a universal way to get passwords on other devices without having to install/buy/setup anything is still kind of a must for this app to be usefill for most people.

_Is_ there a way to do that? I've been looking for something like that for a while now, and so far InputStick is the _only_ viable solution I've found for automatically entering login credentials into semi-trusted computers without exposing your entire password database to them.

**Comment by msfjarvis** [comment]
The maintainers do not own an Inputstick to be able to test any implementation of this, and the Inputstick developers have ignored a [request to publish their library to a public maven repository](https://github.com/inputstick/InputStickAPI-Android/issues/1) for 4 years which makes integration much harder than it needs to be. This issue has also been stale for more than 3 years which to me suggests that there isn't enough interest for this. Password Store will be gaining the ability to type passwords over Bluetooth in a future release via a first-party bridge.
