### ISSUE TITLE
Bug: Internal exception 

### ISSUE THREAD

**Issue by ghost** [android-password-store/Android-Password-Store#147]
I tried password store with github which worked just fine. But with gitlab it throws the following exception: Internal exception occurred
Message from jgit: Could not get advertised Ref for branch master.
This happens when trying to synchronize the repository. Push/pull works fine.

**Comment by bergercookie** [comment]
Encountered the same problem when I tried to sync with a remote repository via ssh (no use of gitlab)

**Comment by zeapo** [comment]
Was it using ssh or https?

**Comment by zeapo** [comment]
Is your repository url (in the settings) correct?

**Comment by bergercookie** [comment]
Yes it is.

**Comment by bergercookie** [comment]
I am trying to clone from a git bare repository in which I have only issued the following commands (as instructed in https://github.com/zeapo/Android-Password-Store/issues/133)
```
git config branch.master.merge refs/heads
git config branch.master.remote origin
```

**Comment by bignose-debian** [comment]
This is difficult for the developers and impossible for the users to even diagnose, because the message should not be this uninformative. Issue #219 requests better treatment of exceptions like this one.

**Comment by trs80** [comment]
I started getting this, I tried deleting the local repository and cloning it afresh, that just got me an empty store and then running sync or pull gives me the same error. I even tried deleting all the app data and the same thing happened. git fsck shows a bunch of dangling commits and one dangling tree, could that be the problem? HEAD is correctly pointing at master.

**Comment by msfjarvis** [comment]
Should be fixed in master, open a new issue otherwise.
