### ISSUE TITLE
file permissions

### ISSUE THREAD

**Issue by brightdroid** [android-password-store/Android-Password-Store#154]
After sync/push to my git-repo all files get new file permissions of 0700, which is not ideal.

**Comment by Adonai** [comment]
Second this. First commit from PwdStore added +x on all files.

**Comment by devkhan** [comment]
Additionally, this is also causing this on decrypting using the binary:

```
gpg: [don't know]: invalid packet (ctb=0a)
```

**Comment by msfjarvis** [comment]
I cannot reproduce this, please let me know with a full device log if you it is still a problem on the latest [snapshot build](https://dl.msfjarvis.dev/APS).
