### ISSUE TITLE
Feature request: Fingerprint Authentication

### ISSUE THREAD

**Issue by Rawa** [android-password-store/Android-Password-Store#156]
Would love to see the feature of unlocking the keystore with usage of the Fingerprint Authentication API. Since Google seems to be aiming to add this as a primary feature for security in Android I think it would be worth considering adding the possiblity to unlock the keystore with it.

Relevant links:
http://developer.android.com/about/versions/marshmallow/android-6.0.html#fingerprint-authentication
http://developer.android.com/training/articles/keystore.html

**Comment by gautamk** [comment]
:+1:  Bump

**Comment by Scrunshes** [comment]
+1

**Comment by jumper047** [comment]
I think it must be assigned to openkeychain

**Comment by zeapo** [comment]
Do you want the fingerprint to unlock the Password Store (the app itself) or to decrypt the passwords? If it's the latter you should open the issue on OpenkeyChain as @jumper047 stated.

**Comment by dsem** [comment]
Here's the relevant issue on OpenKeychan: https://github.com/open-keychain/open-keychain/issues/1642

**Comment by msfjarvis** [comment]
Application locking is done with https://github.com/android-password-store/Android-Password-Store/pull/541, closing this for now since OpenKeychain's blocking it for multiple years now.
