### ISSUE TITLE
Feature request: Proxy support

### ISSUE THREAD

**Issue by nexus-uw** [android-password-store/Android-Password-Store#163]
Hello,

I was wondering if it was possible to add proxy support to this app's setting so it could access an git instance (most likely gitlab) hosted on I2P, TOR, etc. This allows users to self host owncloud behind a NAT at home (or somewhere they don't control the network).

Thanks,
Simon

**Comment by zeapo** [comment]
Hi,

Does this application https://play.google.com/store/apps/details?id=com.lechucksoftware.proxy.proxysettings&hl=fr solve your issue?

**Comment by nexus-uw** [comment]
Hi zeapo,

unfortunately, that app does not work on Android 6.0 
![screenshot_20160224-102926](https://cloud.githubusercontent.com/assets/3188890/13291443/b75e07c2-dae5-11e5-8551-98174bada8bb.png).


Also I have tried using (orbot's)[https://play.google.com/store/apps/details?id=org.torproject.android&hl=en] non-rooted tor-rifying options, but it appears that jGit does not respect the flags that it sets.

**Comment by msfjarvis** [comment]
[Snapshots](https://dl.msfjarvis.dev/APS/) have been updated with the proxy setting. While it works well in my testing with tinyproxy and Squid, it'll be helpful for more people to try it out and file bugs so we can polish off any problems before release.
