### ISSUE TITLE
Request a password from another app

### ISSUE THREAD

**Issue by chmduquesne** [android-password-store/Android-Password-Store#168]
I described the use case on this reddit [post](https://www.reddit.com/r/androidpwd/comments/45x6z7/intent_to_get_a_password_from_another_app/).

So I know I initially said it should be done via an Intent, but it is probably slightly more tricky: an Intent starts an activity, but getting structured results out of this activity requires extra conditions. The documentation of Intents related to [getting a result](http://developer.android.com/training/basics/intents/result.html) indicates that the way to go is a [ContentProvider](http://developer.android.com/guide/topics/providers/content-providers.html).

Suggestions welcome.

**Comment by msfjarvis** [comment]
This issue has gone stale and there is no maintainer interest in implementing it.
