### ISSUE TITLE
git commit signing for new passwords

### ISSUE THREAD

**Issue by ahippo** [android-password-store/Android-Password-Store#170]
It would be great if it were possible to sign new commits to the password repository.
(using a signing key on YubiKey, in particular)
This is possible to do using `pass` utility. but I didn't find how to do this using Password Store.

It would also be great to configure author for git commits.
(it's currently root@localhost)

Sorry, if I missed the feature somehow or am doing something wrong.

Thank you in advance!
I don't think I can help with the code much but I definitely can assist with testing if needed.

**Comment by zeapo** [comment]
That would indeed be great.

**Comment by raindev** [comment]
Another vote for commit signing ✋ `pass` signs commits by default which is very nice to have for peace of mind 🙂

**Comment by Ch00k** [comment]
Another +1 here. I set up my remote git repo to reject unsigned commits, which means I cannot create passwords on my phone.

**Comment by LunaSquee** [comment]
Another +1 from me.

**Comment by karmicdude** [comment]
Another +1 from me too

**Comment by FabianHenneke** [comment]
> It would also be great to configure author for git commits.
(it's currently root@localhost)

This is now possible via Settings -> Git utils.

**Comment by msfjarvis** [comment]
It's impossible to support this feature in JGit 3 and we cannot upgrade to a newer version without completely dropping support for at least Android 6 so this feature will have to be reconsidered for the next major bump (2.x.y), whenever that happens.
