### ISSUE TITLE
Use password from store for 'Syncronize repository' / 'Push/Pull'

### ISSUE THREAD

**Issue by girst** [android-password-store/Android-Password-Store#179]
I have a rather complicated password for git, so it would be awesome to save which password (from the .password-store) is for the git server and ask for the master password then instead. 

currently, I have go to the git's password directory, unlock the password with my gpg masterpassword and copy/paste it into the 'sync repo' dialog. 

thanks

**Comment by zeapo** [comment]
that's a nice idea

**Comment by sc-perth** [comment]
This is already working for me after enabling the app-fill feature.
Admittedly, I had to click the option in the pop-up to create the relationship between the password entry & the password prompt the first time. That's pretty trivial however.

**Comment by stuart12** [comment]
hi @sc-perth can you please provide a more information on how you used the app-fill feature to link an entry in the password store to the SSH passphrase? I just see "Authenticate Please provide the passphrase for your SSH key Remember the passphrase CANCEL OK". How can I tell Password Store to use an entry from the password and choose the correct entry?

**Comment by msfjarvis** [comment]
I don't want to support this exact use case, but with b94b52a42ddc2325b539d0956fd0adcf35308b52 the passphrase/password can now be saved into encrypted storage so you need to copy and paste just once which IMO works just as well.
