### ISSUE TITLE
Clipboard clearing with no copy

### ISSUE THREAD

**Issue by gschwaer** [android-password-store/Android-Password-Store#186]
Hi, the clipboard is cleared even if the option automatically copy password is not selected and no copy operation was done. This might be a design decision, but it would be better to clear the clipboard only if the auto-copy function is enabled or the password was copied in the show password window.
In my case, I just want to remember the password and then type it by hand. An in the current configuration the clipboard gets cleared afterwards even though the password was never in the clipboard. It might also be nice to change the clipboard clearing text in the settings. ;) Thanks! (I'm on version 1.2.0.43 from play store)

**Comment by zeapo** [comment]
You're right!

**Comment by msfjarvis** [comment]
This was fixed by https://github.com/android-password-store/Android-Password-Store/pull/464
