### ISSUE TITLE
Feature request: Open YOLO API by Dashlane & Google

### ISSUE THREAD

**Issue by vshl** [android-password-store/Android-Password-Store#206]
I know it is quite early, I believe the Android Password store will be benefited by the new announced [Open YOLO password API](https://blog.dashlane.com/dashlane-google-open-source-api/) in the future.

> In the future, we see this open API going beyond just Android devices, and becoming universally-implemented by apps and password managers across every platform and operating system. 

I'm creating a new issue, so there is enough time to evaluate the API when its available.

**Comment by emersion** [comment]
Bump: https://github.com/openid/OpenYOLO-Android

**Comment by zeapo** [comment]
I will take a look into it as soon as I'm available to work on this project again

**Comment by msfjarvis** [comment]
OpenYOLO's working group agreed to shelve it.
