### ISSUE TITLE
Orbot/Tor support

### ISSUE THREAD

**Issue by sjug** [android-password-store/Android-Password-Store#215]
Feature request to support Orbot/tor, for higher security git repo setups that aren't publicly accessible.

**Comment by zeapo** [comment]
I've never used Orbot, but doesn't it support a global mode where all applications go through Tor?
If that's the case, isn't that enough?

**Comment by sjug** [comment]
Yeah, Orbot does transparent proxying but you need root for that to work.

**Comment by statianzo** [comment]
Transparent proxying works without root. It uses Android's VPN feature to route all traffic through the local tor proxy service.

**Comment by betsythefc** [comment]
I don't use the VPN feature because many of my apps won't work through tor, so having to selectively turn on and off the VPN is a hassle. This could be implemented as a generic proxy feature, with an optional checkbox for orbot/tor?

**Comment by jrb** [comment]
Orbot's app vpn support is pretty clunky, but works in a pinch.

It seems like most of the time you have to manually start Orbot (or configure it to start at boot), unlike OpenKeychain or Orfox, which are able to spin up Orbot on-demand. 

Support similar to what's in OpenKeychain for Orbot/i2p support would be really nifty.

**Comment by betsythefc** [comment]
I think a generic proxy option would be useful, and us tor users can configure it to use orbot, while everyone else can use it for whatever proxy they need.

**Comment by msfjarvis** [comment]
A generic proxy option is being implemented, but there will not be an Orbot/Tor specific control.

**Comment by msfjarvis** [comment]
[Snapshots](https://dl.msfjarvis.dev/APS/) have been updated with the proxy setting. While it works well in my testing with tinyproxy and Squid, it'll be helpful for more people to try it out and file bugs so we can polish off any problems before release.
