### ISSUE TITLE
overlay buttons not working

### ISSUE THREAD

**Issue by rjbergTU** [android-password-store/Android-Password-Store#221]
When I try to autofill a password, it does not work. The settings button does work though. I have tried all autofill settings.

Even matched passwords do not enter. I can view and edit passwords though.

The problem is on a lg leon with android 5.0.1. My nvidia tablet with marshmallow does work.

Edit: I also tried changing the keyboard. Did not work.

**Comment by somasis** [comment]
I can reproduce this on my phone, an LG G4 running Android 6.0. Settings and close work fine, other autofill buttons (pick, pick and match) don't do anything when I tap them.

**Comment by somasis** [comment]
I'm hitting this issue on the F-Droid version, so I don't believe so.

**Comment by msfjarvis** [comment]
We have rolled out a more reliable and safe Autofill implementation on devices running Oreo and above which does not suffer from this. The previous implementation is now unmaintained.
