### ISSUE TITLE
Do not clear the clipboard - feature request

### ISSUE THREAD

**Issue by smblott-github** [android-password-store/Android-Password-Store#242]
Suggest: add an option to *not* clear passwords copied to the clipboard *at all*.

Why?

1. Correct me, but ... it's not obvious that clearing the clipboard adds any security whatsoever (since any app which wants to read the password can do so immediately it hits the clipboard).

2. But, it's worse than that.  Putting *myPasswordIsDaBest* into the clipboard **tells** other apps that the thing that was just in the clipboard was a password.

(Although, I'm sure others have thought about this more deeply than I have...)

**Comment by zeapo** [comment]
Understandable, and planed ;)

Regarding your points:

1. Clearing the clipboard is not here to solve the case where an application is listening to any changes to the clipboard, Autofill and Share As Clear Text are. Clearing the clipboard is a way to protect you from pasting your password somewhere you shouldn't have.
2. `myPasswordIsDaBest` is a legacy that should have gone a while ago and will be replaced by random string.

**Comment by smblott-github** [comment]
Why not replace the password with whatever was there before hand.  That would seem more useful.

**Comment by zeapo** [comment]
In simple cases, i.e. you copied a single password, that would be simple. However, if you copied a password, then copied another one before the previous one is cleared, this will add more things to take into account, see #228.

**Comment by smblott-github** [comment]
I read #228 before posting.  Wasn't really convinced that it's as complicated as described...

Two global variables (or something):

    previousClipboardContents
    lastClippedPassword

And, additionally, each timer knows:

    myClippedPassword

When a timer expires:
- if `lastClippedPassword == myClippedPassword`, then put `previousClipboardContents` back in the clipboard
- otherwise, do nothing.

Then, all of the timers are more or less independent of each other.

This is also correct for the case when the user themselves clips something else before the timer expires.

**Comment by msfjarvis** [comment]
This can be achieved by setting the password show time to 0
