### ISSUE TITLE
Support thumb drive for git repository

### ISSUE THREAD

**Issue by nullterminated** [android-password-store/Android-Password-Store#255]
I'm using QTPass for Linux and my git remote is on a USB stick. I'd like to use that same usb stick as the git remote on my phone. Password Store only supports SSH and HTTPS for the git remote.

**Comment by zeapo** [comment]
How is your thumb drive connected to your phone? You could use the external repository feature (even though it's not bug free)

**Comment by nullterminated** [comment]
It's one of those OTG usb sticks with usb-a on one side and micro usb on the other. I tried the external repo option, but the file chooser doesn't see the mounted stick. The drive is definitely mounted though, as I can find it under Settings > Storage & USB > Portable storage. Using CM13 marshmallow if that makes a difference. I assume it needs to access the stick through a storage api.

**Comment by nullterminated** [comment]
So I managed to make the thumb drive visible to password store using the advice here

https://www.youtube.com/watch?v=gZ-O3yqqwww

but it still seems not to work. When I set the password store to use the /storage/usbstick/myrepo/ I see a password store screen with Settings in top right, Use Local Directory in bottom left and Clone From Server in bottom right. Perhaps this is because I have a --bare git repo on the USB? If I choose Use Local Directory, it confirms I want to use /storage/usbstick/myrepo/ and goes back to showing the same start screen.

**Comment by nullterminated** [comment]
I should say, even if it does work, it won't be much of a solution when I update to USB-C phone and USB-C Yubikey. I'd have to have a USB-C hub to connect both at the same time, which would be decidedly janky :)

**Comment by nullterminated** [comment]
Yeah, bare repo was the problem. So I can use the stick as an external repo and NFC yubikey. Hidden storage with git remote at file:/// would be preferable. I'll see if I can find where to do that in the source :)

**Comment by zeapo** [comment]
That seems like the right solution :)

**Comment by msfjarvis** [comment]
Looks like this is solved.
