### ISSUE TITLE
Add ability to view git commit log and SHA's

### ISSUE THREAD

**Issue by hughdavenport** [android-password-store/Android-Password-Store#284]

**Comment by FabianHenneke** [comment]
While this wouldn't be too hard to implement in a very basic fashion (just a TextView that mimics the output of git log --oneline), it's not clear whether we should. It seems better to leave this to a dedicated Git app such as Agit.

@msfjarvis What do you think?

**Comment by msfjarvis** [comment]
> While this wouldn't be too hard to implement in a very basic fashion (just a TextView that mimics the output of git log --oneline), it's not clear whether we should. It seems better to leave this to a dedicated Git app such as Agit.
> 
> @msfjarvis What do you think?

I've wanted to provide some basic read-only git functionality for a while now so maybe I'll tackle this for 1.10 next month.

**Comment by Nosweh** [comment]
As it's been a while since the last activity here, this issue does not seem time critical. Being new to this project, I would like to take a look at this if that's okay. I would try and implement viewing the commit log as a simple non-interactive list view.

**Comment by msfjarvis** [comment]
> As it's been a while since the last activity here, this issue does not seem time critical. Being new to this project, I would like to take a look at this if that's okay. I would try and implement viewing the commit log as a simple non-interactive list view.

Absolutely, please feel free to give it a shot.
