### ISSUE TITLE
Repository contains unmerged paths

### ISSUE THREAD

**Issue by slackline** [android-password-store/Android-Password-Store#296]
Hi,

I've encountered the following error...

    Error occured during the sync operation, Message from jgit:
    Repository contains unmerged paths
    Caused by:
    org.eclipse.jgit.errors.UnmergedPathException: Unmerged path: find.sh

The file 'find.sh' was a short script I found when trying to resolve [this issue](hub.com/zeapo/Android-Password-Store/issues/162#issuecomment-290012999) that sought to identify problem commits.

The file isn't present on my git server, nor on my phones local copy and the git tree on my server has nothing to commit or change...

    $ git status
    On branch master
    Your branch is up-to-date with 'origin/master'.
    nothing to commit, working tree clean

...so I'm a little confused why Android Password Store is complaining.  Is there anything else I can do to investigate or to resolve this?  I'd be fine with deleting the local directory structure on my phone and synchronising anew as I did with the previous issue of a detached head (since resolved by *not* having the directory backed up in SpiderOak One!).

EDIT : Looks like another instance of user error, I'd somehow deleted the find.sh from the directory on my phone but since Password-Store doesn't have a git interface (that I've found yet!) it hadn't been removed from git.  Placing a copy back on the phone allowed syncing to complete, although the file hasn't been restored to the server but still resides on the phone.  No huge deal to leave it there as its only 212B but is there a way to remove it from the directory on the phone and still sync?

**Comment by zeapo** [comment]
We execute a git-add when you add or remove a password. Hence, we do not track manual changes to the directory. A hack to solve your issue is to add a new password on your phone and do a sync.

The error happens during the rebase. We probably could solve this easily.

**Comment by msfjarvis** [comment]
This issue has gone stale, please open a new one if this problem still affects the latest release from the Play Store.
