### ISSUE TITLE
add submodule support

### ISSUE THREAD

**Issue by ghost** [android-password-store/Android-Password-Store#297]
I have my personal passwords and then want to store my project password in a separate folder for access control issues. 

Can your software just do the next step to do:

git submodule init
git submodule update

?

Thanks
Jon

**Comment by zeapo** [comment]
Sadly it's not as simple as "git submodule init", we use jgit as a library for everything related to git.

**Comment by rejon** [comment]
Ok how do you do with jgit?

**Comment by SpotlightKid** [comment]
Or just do the equivalent of `git clone --recursive`?

**Comment by e-zhang** [comment]
It looks like in the jgit docs there is a "setCloneSubmodules(boolean)"  method that can be added for the equivalent of `git clone --recursive`. 

Doing updates might be trickier. I think the equivalent of `git submodule foreach git pull` would probably need to be implemented with a combination of jgit.submodule's `SubmoduleWalk` and `PullCommand`s. 

I haven't done any Android development before, so I would greatly appreciate anyone who has to help verify.

**Comment by languitar** [comment]
I opened a similar issue ages ago: #111. Maybe someone can merge these two.

**Comment by msfjarvis** [comment]
Tracking in #111
