### ISSUE TITLE
Support synchronizing to a git branch besides master

### ISSUE THREAD

**Issue by cr1901** [android-password-store/Android-Password-Store#298]
I use `password-store` on my desktop in a setup where it makes sense to have multiple branches. My `master` branch was not up to date, and while a simple fast-forward is sufficient in my case, I can imagine cases where reconciling master with various branches is impractical.

Is there an option to override using master as the git branch that `Android-Password-Store` syncs to?

**Comment by Nalum** [comment]
I would love to see this as well. I've been using a personal and work branch for a while.
