### ISSUE TITLE
Clear clipboard and passwords on Ripple alert

### ISSUE THREAD

**Issue by ahstro** [android-password-store/Android-Password-Store#306]
It would make a lot of sense if Password Store responded to alerts by [Guardian Project's Ripple app](https://github.com/guardianproject/Ripple) by clearing the clipboard and passwords.

**Comment by msfjarvis** [comment]
What I have in mind is that on receiving a ripple alert, we

- clear clipboard
- delete saved passwords from internal or external storage
- clear all app preferences

Is that good enough for what you have in mind?

**Comment by msfjarvis** [comment]
Seems like there never was much interest for this in the first place and OP appears to be unavailable so I'm just going to close this for inactivity with a wontfix label.
