### ISSUE TITLE
Readable error messages for OpenPGP-lib errors

### ISSUE THREAD

**Issue by zeapo** [android-password-store/Android-Password-Store#32]
After decrypt/encrypt, opengpg returns errors on failure. These should be handled correctly and displayed to the user.

**Comment by hughdavenport** [comment]
This currently has a toaster pop up saying "Error from OpenKeyChain: No encrypted data with known secret key found in stream", but then just spins forever.

IMO this app should detect that and then display that error in the app and not spin forever. Potentially saying which keys it is encrypted for as a helpful notice?
