### ISSUE TITLE
Autofill in Chrome not working

### ISSUE THREAD

**Issue by juicetin** [android-password-store/Android-Password-Store#323]
Hi,

I'm running into an issue where autofill in browsers (the official Chrome app, specifically) isn't working. I'm on a Motorola G4 Plus on the latest official update (not rooted or anything), using the latest version of Chrome available from the Play Store.

I tried a handful of websites (popular source code repository websites, a few different email providers, other random things) so it doesn't appear that it's working for some websites and not others or anything like that.

It does work for apps though.

Will provide extra info/etc. on request - not too sure where to start. Thanks!

**Comment by zeapo** [comment]
@wongma7 might have an idea

Side questions, does it work with versions .64 and prior?

**Comment by juicetin** [comment]
Not too sure about that - running the latest version off F-Droid at the moment. Let me try some older versions and get back to you @zeapo

**Comment by juicetin** [comment]
@zeapo @wongma7 in my particular case, seems like 64 doesn't work, and 63 off F-Droid is corrupt :S  (tried downloading from a few different browsers/transferring it from a downloaded copy from my computer - not sure what the problem is with 63 though, could be on my end)

**Comment by zeapo** [comment]
You should be able to get the logcat using the version from F-Droid, otherwise, I can provide a debug apk.

**Comment by juicetin** [comment]
I can't seem to find a link to it - would it be directly from this page? https://f-droid.org/packages/com.zeapo.pwdstore/

**Comment by zeapo** [comment]
What I meant is that using the current version from F-Droid, you should be able to see the logs, no need to install a special version.

**Comment by wongma7** [comment]
Does it work in webviews? Tbh I don’t recall how to test that exactly, unless you know offhand an app that features webviews instead of opening links in browser. 

This is a huge stretch, but the package name of chrome is still com.android.chrome yes? Did auto fill in chrome ever work on this phone or are you just seeing this after updates?

**Comment by msfjarvis** [comment]
The new Oreo+ Autofill implementation works perfectly fine with Chrome, the old code is not going to receive any fixes now.
