### ISSUE TITLE
pass-tomb support

### ISSUE THREAD

**Issue by juicetin** [android-password-store/Android-Password-Store#329]
Hi,

[Enhancement]
Another suggestion for an integration with an existing addon - pass-tomb.

Not sure how feasible this is or how long it will take before it is though, as Android doesn't natively support LUKS - though there is a WIP project on porting the standard to Android (https://github.com/guardianproject/LUKS). Note that the original project is no longer maintained, and they instead point at the forks that still are.

There are Android app/s that use the LUKS project in its current/previous state nonetheless - https://play.google.com/store/apps/details?id=com.nemesis2.luksmanager&hl=en but not sure how reliable they are, though the reviews look good enough that despite the 'pre-release' state of the port.

**Comment by sylph1o** [comment]
Would [EDS Lite](https://github.com/sovworks/edslite) work?

**Comment by msfjarvis** [comment]
At the moment there is no feasible way to implement this. To secure your usernames you can store them within the password file. Closing.
