### ISSUE TITLE
Crash when trying to create a folder when moving a password

### ISSUE THREAD

**Issue by elvay1** [android-password-store/Android-Password-Store#338]
Hello,

First thing, thank you for this application!
Here the issue : 

When I select a password (long press on it), then click on the folder icon in the menu bar, and then click on the + icon, the application stop working.

I don't know if it's fixed with the #210 but just in case I let you know!

(My device is a Moto G running LineageOs 14.1 => android 7.1.2) 
Regards, 
Romain.

**Comment by zeapo** [comment]
Hi,

What version of the application are you using? (you can find it in settings -> scroll to bottom)

**Comment by elvay1** [comment]
Ho Sorry !
It's the latest available on the play store at this time : 1.2.0.64

**Comment by zeapo** [comment]
Can you switch to the alpha version on play store?

**Comment by elvay1** [comment]
It looks like I'm not eligible to alpha version, no update is available, I can switch to F-droid if needed.

**Comment by zeapo** [comment]
F-Droid will be up to date this weekend. I will upload an apk (signed using Play Store's key) later this afternoon.

**Comment by elvay1** [comment]
I moved on fdroid's 1.2.0.68, i can reproduce the issue

**Comment by msfjarvis** [comment]
Please file a new issue with logs if this is still a problem on the latest Play Store release.
