### ISSUE TITLE
SSH key import doesn't report errors

### ISSUE THREAD

**Issue by chrboe** [android-password-store/Android-Password-Store#341]
## To reproduce:
1. Settings -> Import SSH-Key
2. Select any random file (**not** an SSH key)
3. Observe Toast

## What should happen?
An error message should appear (e.g. "SSH-Key import failed")

## What happens instead?
The error is silently dropped and the Toast shows "SSH key imported", indicating success. The user only notices the error when they try to use the SSH key.

**Comment by jpellegrini** [comment]
Tried `adb logcat` when importing, but no message shows up there either...

**Comment by msfjarvis** [comment]
#709 and #714 implement a decently accurate verification flow that should be able to catch most missteps in SSH key selection.
