### ISSUE TITLE
Remember SSH key passphrase

### ISSUE THREAD

**Issue by tullis** [android-password-store/Android-Password-Store#342]
Hi,

Thanks very much for all of your work on this app. I have it set up with OpenKeychain and a Yubikey Neo and it's working very well.

It strikes me that it would be useful to be able to configure the option to remember an SSH key private passphrase somehow, such as with an SSH-agent. Otherwise I have to enter my passphrase every time I do a push, pull, or sync operation.

Would it be possible just to secure this SSH pass-phrase with a fingerprint, or use some kind of `ssh-agent` process to provide a configurable time period during which I wouldn't have to re-enter my pass-phrase?

**Comment by zeapo** [comment]
Hi,

This is indeed a must have to get the #277 working. We'll be working on it later.

**Comment by msfjarvis** [comment]
This is fixed in master.
