### ISSUE TITLE
"Synchronize" action not documented

### ISSUE THREAD

**Issue by vvug** [android-password-store/Android-Password-Store#343]
While `git pull` and `git push` are well know git commands, there is no `git synchronize`, so I can't guess what the "Syncronize" action in PasswordStore does. There's also an upvoted, 2 years old question on Reddit:

https://www.reddit.com/r/androidpwd/comments/3mtlbi/what_is_synchronize_repository/

but it's still unanswered. Please document it somewhere.

**Comment by ZzZi2ptor** [comment]
git pull

**Comment by zeapo** [comment]
@vvug It's indeed not documented :/

It's a git `pull --rebase` followed by a `git push`

**Comment by msfjarvis** [comment]
Documented [here](https://github.com/android-password-store/Android-Password-Store/wiki/Git-Operations-available-in-the-app).
