### ISSUE TITLE
support keybase.io encrypted git

### ISSUE THREAD

**Issue by eranchetz** [android-password-store/Android-Password-Store#344]
https://keybase.io/blog/encrypted-git-for-everyone

**Comment by wongma7** [comment]
Agree would be awesome, but it's not possible atm. They have created a remote-helper which from my understanding is some binary the git binary calls. Apps like this use libraries like jgit or libgit2, I'm not even sure jgit is extensible, and as for libgit2 reimplementing the remote-helper as a "custom transport" or something looks like a job for keybase

**Comment by betsythefc** [comment]
Looks like an issue has already been raised with Keybase on this:
https://github.com/keybase/client/issues/9458

**Comment by maximbaz** [comment]
I think it will be easier to support [spwhitton/git-remote-gcrypt](https://github.com/spwhitton/git-remote-gcrypt), because it uses PGP encryption, which we all know and which is already used in this project. 

As a bonus, `git-remote-gcrypt` allows to store the encrypted repo anywhere, even on a public Github repo if you wish so - the file names are encrypted and nobody will know what your repo contains.

There is a [tracking issue](https://github.com/zeapo/Android-Password-Store/issues/165) for it already, but I just wanted to cross-link the requests and let you know about this possibility - because I didn't know about it myself until yesterday 🙂

**Comment by Celti** [comment]
JGit allows for implementing custom transports by extending the [`Transport` class](https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/transport/Transport.java). It *should* be relatively simple to just use [jnr-ffi](https://github.com/jnr/jnr-ffi) to glue this `KBFSTransport` to [kbfsgit](https://github.com/keybase/kbfs/blob/master/kbfsgit/) or KBFS [libgit](https://github.com/keybase/kbfs/blob/master/kbfsgit/), but I don't know much Java and am uncertain.

It would be pretty much the same thing to support git-remote-gcrypt, only of course the glue for PGP to Java already exists.

**Comment by shilch** [comment]
Bump

**Comment by giulianisanches** [comment]
Does [this](https://github.com/keybase/kbfs/issues/1231) help Android Password Store to use keybase encrypted git repositories ?

**Comment by nilsi** [comment]
It sounds like this is whats needed. Could it be implemnted into android password store? Would be great!

**Comment by msfjarvis** [comment]
> It sounds like this is whats needed.

It's not. APS uses JGit, not raw shell commands for git access. The approach works on Termux because it uses the git binary directly which allows for these remote helpers.

**Comment by matt-snider** [comment]
There is [this outstanding JGit PR](https://github.com/eclipse/jgit/pull/55) which might be useful and worth the experiment of integrating that branch into APS even if it isn't merged yet.

**Comment by msfjarvis** [comment]
I'm sorry but we can't afford the development bandwidth to fork another one of our library dependencies right now.

**Comment by matt-snider** [comment]
@msfjarvis Thanks for the response. I think you've misunderstood me. Sorry if that wasn't clear. I didn't mean that you or any core developer should fork the JGit dependency and begin developing on top of it just for the purposes of implementing the keybase integration. That would not be a good idea at all.

I meant that if there is someone in this thread who is interested, a good area for further research would be to test whether the code from the JGit PR is sufficient to implement the keybase integration. Then once/if that PR is merged into master, this feature could be implemented without requiring any additional libraries.

**Comment by blaggacao** [comment]
I was really happy when I saw keybase git, until I noticed it's not supported.
Is there a way to avoid two concurring cryptostacks OpenKeychain / keybase on my phone AND using Android-Password-Store?

**Comment by msfjarvis** [comment]
> I was really happy when I saw keybase git, until I noticed it's not supported.
> Is there a way to avoid two concurring cryptostacks OpenKeychain / keybase on my phone AND using Android-Password-Store?

They're completely unrelated to each other and one cannot replace the other so I'm not sure what would make you think it'd be possible.

**Comment by blaggacao** [comment]
Split brain about cryptostacks is not a desirable state. While I acknowledge the difference, I can't draw value out of the lack of interoperability.

I understand that GnuPGP is not going to be swapped for NaCl just because, maybe keybase is to blame to better support GnuPGP. To this end, ideally keybase would be an option for providing the key to encrypt / decrypt to Android Password Store. Again that's probably on keybase to implement.

**Comment by msfjarvis** [comment]
> Again that's probably on keybase to implement.
It is. Keybase is a standalone application with no way for other apps to integrate in any fashion. Not for git, not for kbfs, and certainly not for encryption and decryption via GPG.

**Comment by rabbitear** [comment]
Hi,
I have my password-store inside a keybase:/ git repo... But I do not see a keybase:/ option when selecting a git repo with Android password store, only http:/ and ssh:/ so how do I connect the keybase repo? Do I need to clone the repo into, say GitHub or gitlab each time I update a password?

**Comment by msfjarvis** [comment]
> Hi,
> I have my password-store inside a keybase:/ git repo... But I do not see a keybase:/ option when selecting a git repo with Android password store, only http:/ and ssh:/ so how do I connect the keybase repo? Do I need to clone the repo into, say GitHub or gitlab each time I update a password?

Keybase offers no way for JGit users to work with their repositories, so APS cannot support it. You can either use your solution, or do what I do and use a computer on your local network as the server on your phone and pull from it, letting the computer handle interfacing with Keybase.

**Comment by rabbitear** [comment]
Thankyou for your replay, that sounds like even a better idea, since it's not out in the wild.

**Comment by msfjarvis** [comment]
This cannot be fixed so I'm closing the issue.
