### ISSUE TITLE
Enhancement: Automatically install SSH authorized_keys

### ISSUE THREAD

**Issue by shtrom** [android-password-store/Android-Password-Store#347]
It would be neat if the app offered the option to install the newly-generated SSH key onto the git server in a secure way.

Essentially, this would mean adding a line in `~/.ssh/authorized_keys` on the server (say, `echo ... >> ~/.ssh/authorized_keys`) that looks like

    command="perl -e 'exec qw(git-shell -c), $ENV{SSH_ORIGINAL_COMMAND}'" ssh-rsa .... PasswordStore key on DEVICENAME

The idea is to limit that particular key to just using git commands, and not have full access to the account. This comes from [0].

Of course, the installation of that particular key would require either the password for that server (one last time), or another full-shell SSH key (I'm not sure how this could be handled at the moment).

[0] http://joeyh.name/blog/entry/locking_down_ssh_authorized_keys/#git

**Comment by msfjarvis** [comment]
There has been little to no interest from both maintainers and the community in the years this issue has been open so I'm electing to close it as a wontfix.
