### ISSUE TITLE
jgit error: Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectId.w1' on a null object reference

### ISSUE THREAD

**Issue by nicksellen** [android-password-store/Android-Password-Store#357]
I was so happy to see an android app I can use with my pass git repo :)

Ran into this jgit problem though...

I did the following:
* select the _local (hidden)_ option
* generate ssh key using the app
* put public key on my server
* add ssh details to my git repo (personal VPS server, with a bare git repo in `/git/pass.git`)
* attempt to pull from remote

Then comes the jgit error:

<img src="https://user-images.githubusercontent.com/31616/33230697-487bc5ee-d1e0-11e7-9ebe-77decd1d35be.png" width="220">

I wondered if my git repo was corrupt, but a `git fsck` finds no issues. I can clone the repo locally using the copy-n-pasted _Resulting URL_ box.

I am using version 1.2.0.73 from the play store which is the same version as the f-droid one.

**Comment by nicksellen** [comment]
I uninstalled everything and ran through it again and it worked this time :/

**Comment by pastly** [comment]
Haaaaa. I hit the same error message. To fix I did what is probably the same thing. Specifically:

- Went to settings -> delete repository -> delete directory
- Got taken back to main screen
- Selected clone from server
- Selected Hidden (preferred)
- All my server info was still there
- Hit clone

And it worked the second time.

By the way, I'm really surprised this app works behind Orbot's VPN mode and with a repository stored at an Tor onion service. I was anticipating that to cause issues.

**Comment by tbeitter** [comment]
@pastly worked for me, too. Thank you!

**Comment by s1shed** [comment]
Working here too after going through the steps outlined by @pastly.

**Comment by jpalcantara** [comment]
Followed pastly commented 23 days ago and now it is working.  But I have a question on the length of a password that be used when I open a password.  Is there a limit?  I am not able to open any password.

**Comment by indeedwatson** [comment]
I just had this error out of nowhere when trying to sync my repo.

Am I supposed to delete the whole thing and re-do everything all over again?

**Comment by zeapo** [comment]
I'll try to find some time to work on this.

Le ven. 27 juil. 2018 à 02:06, indeedwatson <notifications@github.com> a
écrit :

**Comment by kakolisgay** [comment]
Pastly's solution worked for me.

**Comment by pdecat** [comment]
Still an issue with v1.4.0 from https://play.google.com/store/apps/details?id=dev.msfjarvis.aps

Hopefully, [same work-around](https://github.com/android-password-store/Android-Password-Store/issues/357#issuecomment-349833720) still works :)

**Comment by msfjarvis** [comment]
Yes I finally managed to reproduce it today. I'll be patching it in the coming days.

**Comment by msfjarvis** [comment]
And just like that I can't get myself into the broken state anymore :sob:

Anybody care to help with **exact** reproduction steps so I can try to work this out?

**Comment by pdecat** [comment]
Cannot reproduce either, tried to uninstall/reinstall, install with another package name, no luck :(.

**Comment by ivanterrible** [comment]
I have encountered the exact same error as mentioned above cannot retrieve passwords from git repo.  The steps are essentially the same, using ssh, "Password Store" version 1.4.0 and "OpenKeyChain" providing the authentication for the repository.  I have deleted folder and tried countless times, installed and uninstalled it has never once been successful.  This is on a vanilla Pixel 2XL everything up to date.  The repo itself is fine and fully functional from linux laptop running pass.

**Comment by fliiiix** [comment]
Issue still exists in 1.13.1. 

![photo5377699354590163312](https://user-images.githubusercontent.com/1682954/101980181-f54fab00-3c63-11eb-8c1e-f7db4623725c.jpg)

The workaround with deleting the repo and cloning it again worked for me as well.
I guess the issue is that I attempted to clone the repo which failed the first time which left the internal repo in some broken state.
