### ISSUE TITLE
Password search is outrageously slow

### ISSUE THREAD

**Issue by anoadragon453** [android-password-store/Android-Password-Store#359]
The algorithm for combing through password results is not very fast, which combining with searching every time a user presses a key makes for a poor experience while typing in their sear h phrase (sometimes freezing for up to 10! seconds while typing).

A short-term solution is to add an option to only search when the user presses a search icon on the keyboard.

Long-term is a faster searching algorithm altogether.

**Comment by anoadragon453** [comment]
Coming back to this (still using the app btw, working mostly well), the real solution is just to debounce the search, such that when the user stops inputting characters for half a second, only then perform the search.

There's no point in searching on every character press if the user is intending to enter more characters.

**Comment by MSF-Jarvis** [comment]
Most cases of debouncing that I have found either use coroutines, or RxJava for the purpose. I tried a simple one which unfortunately does _not_ seem to do the trick (Does not refresh in many cases where it should), so I'll defer this to the next sprint when I start migrating the `AsyncTask`s to coroutines.

**Comment by anoadragon453** [comment]
Ok, thank you :)

**Comment by AluminumTank** [comment]
I was just looking at this, and it seems that currently the search is run on the main thread (correct me if I'm wrong). Wouldn't this be the primary problem causing the 10+ second hangups that @anoadragon453 was talking about?

**Comment by msfjarvis** [comment]
> I was just looking at this, and it seems that currently the search is run on the main thread (correct me if I'm wrong). Wouldn't this be the primary problem causing the 10+ second hangups that @anoadragon453 was talking about?

It can be a major contributor. We're currently in the process of modernizing the codebase which is going to introduce Kotlinx.coroutines into the mix. I'll switch to a [Channels](https://kotlinlang.org/docs/reference/coroutines/channels.html)-based debouncer for this operation when that happens.

**Comment by anoadragon453** [comment]
> We're currently in the process of modernizing the codebase 

Great to hear!

Yes, debouncing would go a long way, but moving search off the main thread would be the ideal long-term solution.

**Comment by msfjarvis** [comment]
> > We're currently in the process of modernizing the codebase
> 
> Great to hear!
> 
> Yes, debouncing would go a long way, but moving search off the main thread would be the ideal long-term solution.

Channels can only be created off the main thread so asynchronous operation was implied there.

**Comment by msfjarvis** [comment]
Just dropping a note here to remind myself to work on this today :)

**Comment by anoadragon453** [comment]
I've noticed that a log line, `D REPO    : current path: ...` where `...` is the absolute filesystem path to one of my password files, is printed for *every* one of my passwords *every* time a letter is typed into the search bar. Presumably this is causing some lag as logging is not a free operation.

This logging also seems unnecessary (and leaks personal information into logs!) and should likely be removed regardless.

Doing a quick github search of this repository didn't turn up where this is happening, so it may be a dependency.

**Comment by anoadragon453** [comment]
Additionally, while looking through my logcat I noticed the following log lines while searching:

```
04-06 00:22:36.785 12704 12704 I Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
04-06 00:22:36.785  1205  1205 W RichInputConnection: Slow InputConnection: GET_WORD_RANGE_AT_CURSOR took 580 ms.
04-06 00:22:36.868  1205  1205 I Choreographer: Skipped 38 frames!  The application may be doing too much work on its main thread.
```

Perhaps if the search logic can be moved to a separate thread, the UI wouldn't lock up.

**Comment by msfjarvis** [comment]
> I've noticed that a log line, `D REPO : current path: ...` where `...` is the absolute filesystem path to one of my password files, is printed for _every_ one of my passwords _every_ time a letter is typed into the search bar. Presumably this is causing some lag as logging is not a free operation.
> 
> This logging also seems unnecessary (and leaks personal information into logs!) and should likely be removed regardless.
> 
> Doing a quick github search of this repository didn't turn up where this is happening, so it may be a dependency.

It's not a dependency, the logging was intentional and will be removed in the large refactors me and Fabian are separately working on.

**Comment by msfjarvis** [comment]
> Additionally, while looking through my logcat I noticed the following log lines while searching:
> 
> ```
> 04-06 00:22:36.785 12704 12704 I Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
> 04-06 00:22:36.785  1205  1205 W RichInputConnection: Slow InputConnection: GET_WORD_RANGE_AT_CURSOR took 580 ms.
> 04-06 00:22:36.868  1205  1205 I Choreographer: Skipped 38 frames!  The application may be doing too much work on its main thread.
> ```
> 
> Perhaps if the search logic can be moved to a separate thread, the UI wouldn't lock up.

It's being done in #683

**Comment by msfjarvis** [comment]
This has been fixed in master for a couple versions now.
