### ISSUE TITLE
Autofill stopped working after a crash after failing to reach git server

### ISSUE THREAD

**Issue by doronbehar** [android-password-store/Android-Password-Store#361]
I'm experiencing this problem for the 2nd time, this is what happened to me the last time:

I was trying to synchronize the git repository with my PC but I haven't noticed that WiFi is off so it took a long time for the app to reach the git server and obviously it failed at the end. I'm not sure exactly what happened from there on, but I'm pretty sure I switched to another app instead of killing it my self while waiting for it to fail by it self. After a long while, I got a message from Android saying Password-Store crashed.

From there on, the auto-fill feature stopped working. I don't use it a lot because I use Firefox (#176) so it took me a while to be sure of it and report this.

Something very similar happened to me a long time ago with an earlier version of the app. Than and now, I had to clear all app's data, recreating the ssh keys and rewriting all the settings etc.

I'm not sure if I can find anything relevant in Android's cat log in order to debug this because the crash happened a few days ago, I just thought I should report this.

**Comment by tverlaan** [comment]
I think I'm facing a similar issue. The app crashes when it tries to autofill.

**Comment by madduck** [comment]
My app doesn't crash, but autofill works only in about 1/10 of the cases. The other times, the password field is simply left blank.

**Comment by msfjarvis** [comment]
The new Autofill implementation (for Android Oreo and above) does not suffer from this problem.
