### ISSUE TITLE
Save password silently fails

### ISSUE THREAD

**Issue by dventimi** [android-password-store/Android-Password-Store#365]
In the "New password" screen, at some point recently the "Save" control (the checkmark) does nothing.  Actually, the same is true of the "Cancel" control (the X mark).  When pressed, nothing happens.  Consequently, there's no way to save new passwords.  This is on Android 5.0.1, Password Store version 1.2.0.73

**Comment by zeapo** [comment]
Thanks for the report.
Do you get any error? Are you running the Play Store version?

**Comment by dventimi** [comment]
I did not get an error.  Yes, I'm running the Play Store version.  Interestingly, when I tried it on a different phone I did get an error.  I took a screenshot, which is attached.
![screenshot_2018-01-10-09-38-42](https://user-images.githubusercontent.com/105000/34829077-63684fca-f694-11e7-8ec3-bbb12b289ba1.png)

I don't know if it is the same underlying problem.  Will do more investigation of the problem with both phones today.  Nevertheless, the error I *did* receive raises a question.  Is Git synchronization now required?  I'm pretty sure there once was a time when it was not.  It would be a bit of a problem if it is, since I use [Resilio](https://www.resilio.com/) to sync my .password-store folder across all my devices automatically.

**Comment by petryx** [comment]
Any solution for this issue? 

For me the issue persist, I can't include new passwords
 
Version Android 8.1.0
Motorolo Moto G5s

**Comment by capocasa** [comment]
Same issue! Huawei Mate 10 Pro, password does not save, no error message.

**Comment by msfjarvis** [comment]
Does anybody here who has the problem _not_ use SD Card to store their repo?

**Comment by Hjortsberg** [comment]
I never even had a SD-card mounted in the phone I experienced this on, I store on the internal storage.

**Comment by msfjarvis** [comment]
> I never even had a SD-card mounted in the phone I experienced this on, I store on the internal storage.

Thanks for getting back. I suppose it _is_ an OpenKeychain thing then...

**Comment by ar-** [comment]
I also have this error now. The "save" button for new passwords fails silently, and I have no way to insert new password. There are errors in the logs, but they are not shown to the user, I think it is quite dangerous to hide file system errors from the user.

For creating new passwords in existing directories:

>  java.io.FileNotFoundException: File '/storage/emulated/0/PassStore/test/testnew' permission denied

and for new passwords in new directories

>  java.io.FileNotFoundException: Directory '/storage/emulated/0/PassStore/test2' could not be created

I'm syncing the while pass repo with synchthing between different devices.
The app has permission to read and write storage. When I revoke that permission it asks correctly to re-enable it. Other apps can also read and write to the same directory.

**Comment by msfjarvis** [comment]
> I also have this error now. The "save" button for new passwords fails silently, and I have no way to insert new password. There are errors in the logs, but they are not shown to the user, I think it is quite dangerous to hide file system errors from the user.
> 
> For creating new passwords in existing directories:
> 
> > java.io.FileNotFoundException: File '/storage/emulated/0/PassStore/test/testnew' permission denied
> 
> and for new passwords in new directories
> 
> > java.io.FileNotFoundException: Directory '/storage/emulated/0/PassStore/test2' could not be created
> 
> I'm syncing the while pass repo with synchthing between different devices.
> The app has permission to read and write storage. When I revoke that permission it asks correctly to re-enable it. Other apps can also read and write to the same directory.

I'm aware of problem with external storage, it's a JGit problem that I have not had the bandwidth to investigate and resolve.

**Comment by ar-** [comment]
> I'm aware of problem with external storage, it's a JGit problem that I have not had the bandwidth to investigate and resolve.

Okay. Maybe I can find where it is, but can you fix the UI ? Tell the user that there is an error?

**Comment by msfjarvis** [comment]
> > I'm aware of problem with external storage, it's a JGit problem that I have not had the bandwidth to investigate and resolve.
> 
> Okay. Maybe I can find where it is, but can you fix the UI ? Tell the user that there is an error?

I'll prioritize it after #685 lands.

**Comment by capocasa** [comment]
Not an SSD, but folder on public internal space for syncing with 3rd party program.

**Comment by ar-** [comment]
> I'm aware of problem with external storage, it's a JGit problem that I have not had the bandwidth to investigate and resolve.

The issue is not related to JGit. (I personally don't use git, I use syncthing). here is a complete stacktrace from the debugger:
```
E/PgpActivity: An Exception occurred
    java.io.FileNotFoundException: /storage/emulated/0/PassStore/test/ttt.gpg (Permission denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:287)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
        at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:360)
        at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:319)
        at com.zeapo.pwdstore.crypto.PgpActivity$encrypt$1$1.onReturn(PgpActivity.kt:591)
        at me.msfjarvis.openpgpktx.util.OpenPgpApi$executeApiAsync$2.invokeSuspend(OpenPgpApi.kt:37)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:869)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:6760)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)
```

It is simply an access error when trying to store a new password on disk. (PgpActivity.encrypt())

It is also nicely commented with:

> // TODO This might fail, we should check that the write is successful

The code line where the error happens is here:
https://github.com/android-password-store/Android-Password-Store/blob/7dc6ee799200deee9d5c5faed74dff4d564dad43/app/src/main/java/com/zeapo/pwdstore/crypto/PgpActivity.kt#L591

**Comment by ForDavStuff** [comment]
I can't get openkeychain to find password store app. It looks like the icon shown in OKC is from the old version and therfore it tries to redirect me to a play store page that doesn't exist anymore (OFC not finding the already installed and configured password store app)

**Comment by msfjarvis** [comment]
> I can't get openkeychain to find password store app. It looks like the icon shown in OKC is from the old version and therfore it tries to redirect me to a play store page that doesn't exist anymore (OFC not finding the already installed and configured password store app)

Please use the [Discussions](https://github.com/android-password-store/Android-Password-Store/discussions) page for general questions rather than commenting on unrelated issues so we are able to better help you.
