### ISSUE TITLE
Error message during password addition/removal

### ISSUE THREAD

**Issue by avorop** [android-password-store/Android-Password-Store#373]
When I try to add a password I get popup with text "An error occurred during a Git operation. Message from jgit: Exception caught during execution of add command. Caused by: java.io.IOException: open failed ENOENT (No such file or directory)"

If I click OK Button, then the application is closed. When I open it again, I see that the password is actually added, then why error?

Grunt below, can be ignored :)

As general comment, the app is very confusing. I still don't get where actually the passwords are stored and why I get those error messages. I thought I have to configure access to Git server, which I've tried to do, to no good result. I guess I don't understand what is "Git server" here. I've just laid out bare Git repo on my host and hoped, that this would be enough.

Then there is command "Push to remote". When I try it I get back "There's nothing to push". Hm, and how do I control what to push?

Then there's "External repository" option? Is it related to "Git server" or completely independent?

Maybe, if I understood the background it would be easier to use the app. But I can't find any concise documentation.

And one more question, when setting up access to Git server, it is offered to login using ssh key. Which shall be used? The key managed by OpenKeyChain supports SSH authentication. Then there's option "Generate SSH key pair" in the settings menu. So which one is used?

**Comment by msfjarvis** [comment]
Please file a new issue if this problem still persists and we'll look into improving documentation further.
