### ISSUE TITLE
Clipboard not cleared after manual copy

### ISSUE THREAD

**Issue by mhoran** [android-password-store/Android-Password-Store#374]
I recently noticed that manually copied passwords are not cleared after the configured timeout. While the progress bar starts to count up, when it reaches the end, the password is not cleared. This seems only to happen if "Automatically Copy Password" is unchecked.

I was able to reproduce this with an Android emulator running version 8.0.0.

**Comment by zeapo** [comment]
You manually copy the passwords, and that makes the clearing "random"?

**Comment by mhoran** [comment]
I've disabled "Automatically Copy Password" and use the copy password icon from the action bar instead. Based on the description of "Automatically clear the clipboard after copy" in settings ("After an [...] manual copy, [...] the clipboard will be automatically cleared"), I expected the clipboard would be cleared. However, the password persists even after 45 seconds have passed.

I've never seen the clipboard cleared in this scenario, though if I flip "Automatically Copy Password" back on, the password is cleared after 45 seconds. I can't test the exact same scenario in this configuration, since I'm returned to the password list.

**Comment by mhoran** [comment]
I did some digging, and it seems that this used to work as documented in the preference description, but was changed in https://github.com/zeapo/Android-Password-Store/commit/7826dce5269cf0da753acdd301c125252cd8f0c0. That commit eventually made its way over to the corresponding Kotlin code in https://github.com/zeapo/Android-Password-Store/commit/c3eb4f0a414b4bceb79b3c19eec2f69528ced02bt.

I'll leave it to you as to whether the preference description should be changed, or the commit changing this behavior should be reverted. I presume the commit author, @wongma7, had a reason to make the change. Or perhaps there could be a separate preference.

I've just enabled automatic password copying for the time being, but I'd prefer to shut that back off. Autofill also makes that mostly moot, though sometimes autofill doesn't work as expected and I have to copy the password.

**Comment by zeapo** [comment]
Nice catch.
I'm trying to wrap my head around disabling the auto-clear after manual copy, will be back to this.

**Comment by reroman** [comment]
I think the setting to verify should be "clear_after_copy" instead of "copy_on_decrypt" (actually, it looks like the first one is never used in the app). Also modify some toasts according to the selected options.

**Comment by msfjarvis** [comment]
Fixed by https://github.com/android-password-store/Android-Password-Store/pull/464
