### ISSUE TITLE
Provide easy way for copying username

### ISSUE THREAD

**Issue by likwrk** [android-password-store/Android-Password-Store#375]
Add copy icon on the username line or add notifications to the android drawer (like keepassdriod does) so that it would be easy to copy username and password to the needed app without switching to password store app multiple times. So the flow would be:
1. Open password store and select password file
2. Switch to the app you need to enter credentials to
3. By tapping the notification in the drawer easy copy username/password and paste it

**Comment by zeapo** [comment]
Nice idea ^^

**Comment by msfjarvis** [comment]
This was fixed by #635
