### ISSUE TITLE
Can not connect to github

### ISSUE THREAD

**Issue by xianghongai** [android-password-store/Android-Password-Store#376]
```
Error occured during the sync operation, Message from jgit:Exception caught during execution of add command Caused by:
java.io.IOException: No such file or directory
Please check the FAQ for possible reasons why this error might occur.
```

```
Error orrured during the pull operation, Message from jgit:Pull on repository without HEAD currently not supported
Caused by:
null
please check the FAQ for possible reasons why this error might occur.
```

```
Error orrured during the push operation:Nothing to push.
Caused by:
org.eclipse.jgit.error.Trans portException:Nothing to push.
```

![screenshot_2018-01-25-17-49-37-454_com zeapo pwds](https://user-images.githubusercontent.com/2075006/35382485-62f04f40-01fa-11e8-845c-bde9706b1c31.png)
![screenshot_2018-01-25-17-49-58-597_com zeapo pwds](https://user-images.githubusercontent.com/2075006/35382486-637470e0-01fa-11e8-8c61-b6af1cac4e46.png)
![screenshot_2018-01-25-17-49-12-454_com zeapo pwds](https://user-images.githubusercontent.com/2075006/35382487-6408137c-01fa-11e8-9b07-f0c3ea981125.png)
![screenshot_2018-01-25-17-49-18-235_com zeapo pwds](https://user-images.githubusercontent.com/2075006/35382491-64874cfa-01fa-11e8-8454-f08d4b27d386.png)

**Comment by martini97** [comment]
I'm also having the same problem

**Comment by zeapo** [comment]
That means that you're trying to clone an empty repository.

**Comment by martini97** [comment]
@zeapo , the repository Im trying to clone is not empty, it contains my password store, I already checked and confirmed that the repo does contain a HEAD. Im using that app downloaded from F-droid. Ive already tried using ssh and https authentication. Do you have any idea what I might be domingo wrong?

**Comment by Jyuukun** [comment]
Having the same problem here.

**Comment by julianprester** [comment]
Getting the same error message here. Now I think it might have something to do with GitHub private repositories. I tried setting my repository to Public and now I am at least able to pull it. Pushing still gives the same TransportException though.

**Comment by erayd** [comment]
I'm using a GitHub private repo with no problems. Can successfully clone, pull etc. without error.

I use an SSH private deploy key for read-only access, and do not push from the phone.

Using v1.2.0.73 of the app from the Play Store, on Android 8.1.

**Comment by zeapo** [comment]
@martini97 are you using https?

**Comment by martini97** [comment]
@zeapo I've tried using both https and ssh

**Comment by piotryordanov** [comment]
Same here. Can't connect with either https or ssh!

**Comment by c4pointer** [comment]
I have same problem with my gitlab repo. It is not empty for sure.

**Comment by 1fabunicorn** [comment]
Is this fixed now? I can't get it to work, giving me this error
![image](https://user-images.githubusercontent.com/19752126/72405336-75088900-3726-11ea-968e-de06d0c251f9.png)

This is after copying the "ssh clone string" from github right into the "resulting url" field.

Thanks!
