### ISSUE TITLE
Avoid ssh-key passphrase in config file

### ISSUE THREAD

**Issue by gregorlarson** [android-password-store/Android-Password-Store#378]
The option to save ssh-key passphrase needs to be a little more clear.
I (foolishly) assumed that the passphrase would be retained in RAM, similar to how openkeychain retains a gpg-key passphrase in a service-process.

Writing a passphrase to a config-file presents a *much* higher risk than keeping it in RAM.
I understand why you might want to use the ssh-key without a password prompt for the user, however, I think the "Remember the passphrase" box might be to vague because folks (like me) might not catch on to the fact it is being written to a key-file.

Request, near term:

Make it more clear to the user that the ssh-key password is being saved to persistent storage, for example:
    "Save password to configuration file"

Longer term:

I see other work/requests to allow openkeychain to keep the ssh passphrase or key, this would be much better than keeping passphrase in config-file.

Other options:

Instead of  keeping the passphrase in the config-file, have you considered using the Android KeyChain or KeyStore facilities to keep the ssh-key secure, yet still available?

https://developer.android.com/reference/android/security/KeyChain.html
https://developer.android.com/training/articles/keystore.html

Thank you for your important work on this!!

**Comment by zeapo** [comment]
Thanks for the good remark. The options you suggested are the right ones, however we need time to work on it (which I don't have currently).

I'll change the strings to mark it as "insecure".

**Comment by stuart12** [comment]
Why don't we consider allowing the user to select a password entry that is the passphrase for the SSH key?  My SSH passphrase is already in the password store. I just need to be able to tell Password Store where to find it.

**Comment by j0rd** [comment]
There's also a way to embed your SSH key into a GPG key.

Here's some docs on that:
https://www.linode.com/docs/security/authentication/gpg-key-for-ssh-authentication/

I've recently done this and it works, although I'm just now getting familiar with GPG, so I'm not the best person to explain on how this route could be used.

With that said, storing anything plain text is a horrible idea.

**Comment by msfjarvis** [comment]
This has been reworked to store the passphrase into a separately encrypted set of preferences.
