### ISSUE TITLE
jgit: Pull on repository without HEAD currently not supported; Caused by: null

### ISSUE THREAD

**Issue by marc-reh** [android-password-store/Android-Password-Store#385]
I was trying to "pull from remote" when I got the above error message. I copied my external repository to my Mac, inspected it with git fsck and got lots of error messages (I am not very familiar with git though). I followed the suggestion in #357: I deleted my repository, cloned it again from the server (actually, from my Mac), and everything worked again. I am not sure what exactly I was doing when the error occurred; I was doing some ssh setup on my Mac, and I tried to willfully get password store's ssh attempt rejected, but I don't remember my exact procedure.

**Comment by justinacolmena** [comment]
![screenshot_20181211-083455](https://user-images.githubusercontent.com/32494761/49841936-1411c300-fd66-11e8-8779-492bc0066a62.png)
> `Last login: Tue Dec 11 17:35:28 2018 from 24.237.158.21`
> `[justina@otherhost ~]$ cd .password-store/`
> `[justina@otherhost .password-store]$ git branch -vv`
> `* master 1b77991 Add generated password for someaccount.`
> `[justina@otherhost .password-store]$`

It looks like I am connected to the right repository on the other host, and the app is looking at the latest commit on the other host. So is there a "master" branch but no HEAD? What is the problem?

**Comment by justinacolmena** [comment]
The above error happened when I was trying to synchronize with a default password-store initialized by the unix "pass" utility.

I was able to create a backup of the encrypted passwords from the app, zip up the backup directory with a different app, transfer it over and unzip it to a new directory on the remote git server.

All the necessary files are now there, and I can synchronize with the git repository in that directory on the remote server.

So.

**Comment by indeedwatson** [comment]
This keeps happening to me, I haven't been able to sync in months, makes the app pretty much useless.

**Comment by greywood** [comment]
I get the same thing too. I would love to sync/push/pull. I'll pray to the great gods!

**Comment by daesters** [comment]
> I get the same thing too. I would love to sync/push/pull. I'll pray to the great gods! Is there any more to see more information? A debug setting in password-store?

Have a look at the answer from **pastly**, https://github.com/zeapo/Android-Password-Store/issues/357#issuecomment-349833720
That work for me quite well!

**Comment by greywood** [comment]
I guess at some point I had tinkered with the the pass git repository, so I ran some git commands and got it back to working state.

**Comment by msfjarvis** [comment]
This has been resolved on master.
