### ISSUE TITLE
“Synchronise repository” breaks symlinks

### ISSUE THREAD

**Issue by shtrom** [android-password-store/Android-Password-Store#387]
Due to SSO across different domains, I have resorted to symlinking some entries in my `.password-store`. It works and syncs well across machines, including an OS X one.

However, whenever I do a “Synchronise repository” with Android Password Store, it replaces all those symlinks with plaintext files containing the path to the linked file, com: mits and pushes that back. As a result, the next `pass git pull` on any other machine pulls down those invalid files, leading to occasional confusion when I try to retrieve a password: 

```
gpg: no valid OpenPGP data found.
gpg: decrypt_message failed: Unknown system error
```

**Comment by c-e-p-x-u-o** [comment]
Same issue!

**Comment by c-e-p-x-u-o** [comment]
symlinks are disable in ```.git/config``` file: ```symlinks = false```
due to
![screenshot](https://user-images.githubusercontent.com/14617699/38060260-afb828e2-32f2-11e8-9e2d-fa9d45d4695f.png)

**Comment by zeapo** [comment]
This should have been fixed in 2016... see https://github.com/zeapo/Android-Password-Store/issues/98#issuecomment-182358857 I'll try to do it ASAP :)

For the simlink support see #98.

**Comment by msfjarvis** [comment]
Being tracked in #636
