### ISSUE TITLE
NPE when getting last edit time

### ISSUE THREAD

**Issue by zeapo** [android-password-store/Android-Password-Store#389]
Samsung Galaxy S9+ (star2lte), Android 8.0
```
java.lang.NullPointerException:
  at com.zeapo.pwdstore.PasswordStore.getLastChangedTimestamp (PasswordStore.java:436)
  at com.zeapo.pwdstore.PasswordStore.decryptPassword (PasswordStore.java:444)
```

**Comment by behrica** [comment]
Galaxy S7
Same for me, maybe duplicate of #450

**Comment by behrica** [comment]
I found a workaround in order to see my passwords, at least. By "long press" on an entry I can get into edit mode and can see the password and copy it manually to clipboard.
Doing this I get as well a message "could not read last changed timestamp", but it does not crash

**Comment by msfjarvis** [comment]
This crash was resolved on master a while ago.
