### ISSUE TITLE
App crashes when the back arrow key is used to exit the settings page after adjusting settings

### ISSUE THREAD

**Issue by codaphrenic** [android-password-store/Android-Password-Store#393]
#### Expected behavior
It is expected that on clicking the back arrow key, the app should exit the settings page to the main page.

#### Actual behavior

The app crashes when the back arrow is used to exit the settings page

#### How to reproduce
* Download the app from fdroid store
* Scroll through your menu and launch app.
* Select the left bottom key that reads **USE LOCAL DIRECTORY**
* Select SD Card
* Click Ok, then select any desired folder
* Click on **Edit git server settings**
* Go back to the settings page using the default android back key 
* Now press the back arrow key at the top left corner and the app crashes

***

* Device: TECNO-L8Plus 
* Operating system: Android 5.1

* Application: Password Store
* version: 1.2.0.75

#### Recording Of The Bug

<center>
https://youtu.be/9pg-J2qCm-A
</center>
 

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@fego/app-crashes-when-the-back-arrow-key-is-used-to-exit-the-settings-page-after-adjusting-settings">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by zidhuss** [comment]
Are you still able to reproduce this on the latest version?

**Comment by msfjarvis** [comment]
This is a storage permission bug that has been fixed
