### ISSUE TITLE
Cannot create numerals only passwords

### ISSUE THREAD

**Issue by reroman** [android-password-store/Android-Password-Store#395]
When I only select Numerals in the Generate Password dialog, the password generated always contains letters.

**Comment by zidhuss** [comment]
With all the flags unset, it defaults to generating a password with only lowercase characters. When you're selecting to include `Numerals`, you're allowing numerals to be generated along with the lowercase characters.

However we probably _do_ want the ability to generate numeral only passwords.

**Comment by zeapo** [comment]
To generate numerals only, we should add a checkbox "include letters". When unchecked it would remove [a-zA-z] from the generator.

**Comment by FabianHenneke** [comment]
Resolved by #478.
