### ISSUE TITLE
Add support for ssh ProxyJump

### ISSUE THREAD

**Issue by pmaziere** [android-password-store/Android-Password-Store#408]
Hello, 

I have my password-store repository on a non accessible computer behind an ssh gateway.
From my laptop, I use the ProxyJump feature of openssh in order to push and pull the repository.

Is it possible to implement this feature in Android-Password-Store ?

thanks

**Comment by 00dani** [comment]
This should be possible, albeit possibly a little fiddly - Android-Password-Store uses JGit, which uses JSch for its SSH support. JSch doesn't appear to use a `ProxyJump` option in so many words, but one of their sample programs does implement the same functionality so it's definitely something JSch can do: http://www.jcraft.com/jsch/examples/JumpHosts.java.html

**Comment by FabianHenneke** [comment]
For later: ProxyJump could be implemented with SSHJ along the lines of https://github.com/hierynomus/sshj/issues/494#issuecomment-471277584.

**Comment by msfjarvis** [comment]
Closing as part of [issue tracker cleanup](https://github.com/android-password-store/Android-Password-Store/discussions/1836).
