### ISSUE TITLE
Using Autofill (API >= 26)

### ISSUE THREAD

**Issue by l0rn** [android-password-store/Android-Password-Store#410]
So as far as i understood it is agreed that implementing the Autofill mechanism provided by Android O and higher is desirable thing to do. I am opening a new ticket because #352 has mixed topics.

I started to implement Autofill functionality here:
https://github.com/ctrlaltcoop/Android-Password-Store/tree/oreo-autofill

I got so far that I basically copied over the example service from [google's example project](https://github.com/googlesamples/android-AutofillFramework) and expanded the heuristics to work better with web forms.

I plan to finish this in the course of the next two weeks. I could use help with:

- Correct License / Attribution
    - I use the stuff from the google example which is licensed under Apache License. I use some big fragments but altered a lot. What would be the correct way to attribute the source etc.?
- If someone experienced with the codebase could provide simplified snippets how to extract usernames from the app that would be cool, i guess i'd figure it out myself sooner or later, but that would mean i have to reverse engineer the AutofillService which seems a bit messy - at least for someone who is used to python and not so experienced with java

**Comment by l0rn** [comment]
Got pretty far... If you want to support me take a peek [https://github.com/ctrlaltcoop/Android-Password-Store/tree/oreo-autofill](here). On my todo list:

- Find out how to be backwards compatible (if < Oreo use accessibilty), still don't know how to tell gradle that - so far i had to set minSdkVersion to 26 which would lock out all old devices
- Improve heuristics to find login forms
- Make heuristic work for apps too

I created a [Pull Request](https://github.com/zeapo/Android-Password-Store/pull/411) to see the progress

**Comment by IvanMalison** [comment]
@zeapo @l0rn What's the status of this

**Comment by l0rn** [comment]
It's basically still in this inbetween state of not being implemented - i abandandoned it then because chrome didn't support autofill back then yet. Also there is some workflow issues still, like choose from list if you have no domain / app identifier match is not implemented.

I'd really like to pick it up soon, but I'm pretty busy with my paid work (moneys tight) and my daughter

**Comment by IvanMalison** [comment]
I'm happy to pick it up if you want.

**Comment by l0rn** [comment]
yea cool feel free to do so!

the general functionality should be given already - it's actually installed on my phone. In oreo till 8.1 chrome seems to ignore autofill api, it works in webviews and apps though. as mentioned a manual selection option for a password entry as missing as well as a mechanism to match password entries against app identifiers

**Comment by IvanMalison** [comment]
@l0rn Have you tested in in android p? or in versions beyond 8.1?

**Comment by philgood** [comment]
@IvanMalison Do you have any further development updates?

**Comment by igaryhe** [comment]
Do you have any further development progress?

**Comment by l0rn** [comment]
sorry, pretty sure i won't make it anywhere in the near future. we're pretty swamped.

**Comment by c4software** [comment]
This issue is still in progress somewhere ? I could implement it, if anybody is currently doing it...

**Comment by IvanMalison** [comment]
@c4software please do. Android dev is pain to me as I have to leave my beloved emacs AND use java/kotlin.

**Comment by msfjarvis** [comment]
> This issue is still in progress somewhere ? I could implement it, if anybody is currently doing it...

If you'd like to continue it I'll be happy to assist with code review and feedback.

**Comment by c4software** [comment]
Hi,

I started the implementation. So, the service is done and seems to working well.

<img width="421" alt="Capture d’écran 2019-09-29 à 22 20 35" src="https://user-images.githubusercontent.com/988914/65838826-6b8a1b00-e307-11e9-96fb-ba502a6a7585.png">

Now i « just » had to do the picker activity (the window to pick witch entry you want for autofill).

PS : I have and had busy weeks… So…it could take some times to finish.

**Comment by msfjarvis** [comment]
Great job @c4software! Looking forward to reviewing and merging this :)

**Comment by c4software** [comment]
Hi the base logic is done. I just need to implement the « Filtering password RecyclerView » :

https://youtu.be/KVGyJdb4x4U (for curious people)

I will look at the « old » autofill service to see if i can reuse some stuff.

**Comment by c4software** [comment]
Some news :

UI : 
- Password filtering is working. 
- Item selection is working. (And fill the original view)

Todo :
- Decrypt the password. 
- fix UI height jumping.

**Comment by c4software** [comment]
The UI will look like this : 

![ezgif-2-5b7cdbea1d60](https://user-images.githubusercontent.com/988914/66042823-ceed9600-e51d-11e9-893f-78098b7de88a.gif)

Tell me if it's ok for you? 
- If yes I will implement the password unlock method.

PS : The default « Recycler » is populate with last decoded items (get from the Shortcut manager)

**Comment by msfjarvis** [comment]
Looking great! If you start a PR I'd love to start reviewing this and helping out

**Comment by krims0n32** [comment]
Good stuff! This is the only thing I'm missing from the app.

**Comment by TLATER** [comment]
@msfjarvis @c4software don't mean to push you, but any further updates? It's been a little while and it would be a shame if that progress just dropped.

**Comment by msfjarvis** [comment]
I'm not working on it right now as I don't have the time. The existing implementation works reasonably well for my needs.

**Comment by c4software** [comment]
I'm really busy right now! I don't have many spare time right now…

**Comment by FabianHenneke** [comment]
I also think that the current implementation works reasonably well for the time being.

I have been working on and off on a more complete version (with origin checks, save support, username field detection, password generation) which is about 80% done and loosely based on the current PR. When it is complete, I will submit a separate PR, but this may take some more time.
