### ISSUE TITLE
Push more the one files to gitea will failed

### ISSUE THREAD

**Issue by phil-flex** [android-password-store/Android-Password-Store#414]
Pushed one or two files is fine,but third will fail.

**Comment by phil-flex** [comment]
![screenshot_2018-06-26-05-28-34-537_com zeapo pwdstore](https://user-images.githubusercontent.com/34325924/41877050-7a6a3a9e-7902-11e8-8953-bd6f755a9617.png)

**Comment by FabianHenneke** [comment]
Are you still experiencing this issue with the current Play Store version (v1.7.1)? The git flow has seen many changes and this may have been fixed along the way. It may also be an issue with a particular git remote, have you tried with others?

If the problem should persist, please open a new issue.
