### ISSUE TITLE
Push not working when editing existing entries

### ISSUE THREAD

**Issue by sjau** [android-password-store/Android-Password-Store#415]
Hi

I use v 1.2.0.73 and I noticed when I edit existing password entries on my droid, then changes won't be pushed back to the git repo even when I select git push from the menu.

However, after creating new entries or deleting entries, it will push them.

**Comment by zidhuss** [comment]
Hi, do you still have this on the latest F-Droid release?

**Comment by msfjarvis** [comment]
Reporter went AWOL
