### ISSUE TITLE
Typing in Search Bar sometimes doesn't search.

### ISSUE THREAD

**Issue by anoadragon453** [android-password-store/Android-Password-Store#426]
Recently since an upgrade to Android 9, sometimes when opening Password Store, tapping search and typing in the search bar doesn't actually carry out a search. Instead I have to kill the app and reopen it to get search working, which as you can imagine is incredibly frustrating.

I haven't seen input behavior break on any other apps on Android 9.

**Comment by anoadragon453** [comment]
Still having this problem. I have ruled out the OTG cable/mouse/keyboard combo being the problem. I don't see a pattern to the issue, other than the Android 9 upgrade.

**Comment by lufte** [comment]
I have this same issue with Android 7.1.1 on a Motorola G4 Play. The search bar doesn't work most of the time.

I'm happy to run any tests you need to debug this.

**Comment by regagain** [comment]
Just wanted to chime in and let you know that I have the same issue. Samsung S10e, Android 10, password-store 1.6.0.

**Comment by msfjarvis** [comment]
> Just wanted to chime in and let you know that I have the same issue. Samsung S10e, Android 10, password-store 1.6.0.

Can you reproduce it reliably?

**Comment by FabianHenneke** [comment]
@msfjarvis It could be worth a try to set the event listeners in the search view in onPrepareOptionsMenu, not onCreateOptionsMenu: https://stackoverflow.com/a/16854431/297261.

What do you think about #677? With this, we could determine whether 1) the change to onPrepareOptionsMenu fixes everything or 2) onQueryTextChange is broken, but onQueryTextSubmit works and users at least don't have to restart the app to

**Comment by msfjarvis** [comment]
> @msfjarvis It could be worth a try to set the event listeners in the search view in onPrepareOptionsMenu, not onCreateOptionsMenu: https://stackoverflow.com/a/16854431/297261.
> 
> What do you think about #677? With this, we could determine whether 1) the change to onPrepareOptionsMenu fixes everything or 2) onQueryTextChange is broken, but onQueryTextSubmit works and users at least don't have to restart the app to

Sure it can't hurt to try.

**Comment by msfjarvis** [comment]
welp `resolves` triggered GitHub's auto closer

**Comment by anoadragon453** [comment]
I can in fact reproduce it reliably using my USB C yubikey (which Android treats as a keyboard being plugged in). Once I plug in the device, the activity refreshes and search no longer works.

Here's a video of the behaviour. When the screen flashes black, I've plugged in the device: https://streamable.com/j3bom

Happy to try the above PR, if someone could generate an APK, or I'll just wait for release.

**Comment by FabianHenneke** [comment]
@anoadragon453 The potential fix should be contained in the snapshot build: https://dl.msfjarvis.dev/APS/
That search is no longer working after the activity refreshed makes it more likely that the fix is actually correct.

**Comment by msfjarvis** [comment]
@anoadragon453 can you confirm if the snapshot build has resolved the problem?

**Comment by anoadragon453** [comment]
@msfjarvis It does not I'm afraid. Same symptoms with the same steps.

I'm attached some adb logs as those will probably be more useful than another video:


[log.txt](https://github.com/android-password-store/Android-Password-Store/files/4435251/log.txt)

The most interesting lines here look to be:

```
04-06 00:27:47.559 13096 13096 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
04-06 00:27:47.559  1205  1205 E RichInputConnection: Unable to connect to the editor to retrieve text.
04-06 00:27:47.560  1205  1205 D RichInputConnection: Will try to retrieve text later.
```

which only occur when I'm typing into the field and nothing is showing up, and get printed out *after* I hit the left back arrow to exit out of the entry field.

**Comment by msfjarvis** [comment]
Is this still a problem with v1.8.1?

**Comment by anoadragon453** [comment]
It does not actually, hooray!
