### ISSUE TITLE
The doco is not clear for newbs

### ISSUE THREAD

**Issue by Finger8** [android-password-store/Android-Password-Store#428]
The software is on android Play, so people with little github experience try it out. Then find, it's a mystery how to keep a safe copy. E.g. is the github *public* repository encrypted with the OpenKey password, so no-one can read it - or do you need to have a private repository? Which?

Is it possible to put an encrypted version on a Cloud server - if so, exactly how, step by step. I've tried and failed.

If you did get a copy onto github - to link up to it, why do you need a "bare" repository to connect a new device to it, or is that no what was meant?.

A couple more pages of doco (proofed by someone who isn't a coder) is all I'm asking for.

**Comment by zidhuss** [comment]
Hi,

I agree it is an issue and it's something that I'm currently addressing. I'll be updating the README and wiki pages with more up to date information and features.

**Comment by msfjarvis** [comment]
I've answered the questions in thr Frequently Asked Questions page of the wiki, please open a new issue if there are any further suggestions that you'd like to see incorporated.
