### ISSUE TITLE
Lost local repository (hidden) after f-droid update

### ISSUE THREAD

**Issue by nickless81** [android-password-store/Android-Password-Store#440]
I update the app with f-droid this morning and after that the app doesn't restart.
I tried to reinstall the app and after that I lost my local store password.
There's a way I can restore that file without root?

**Comment by zidhuss** [comment]
The app failing to start is probably related to #437, #439. It has been fixed in `v1.3.1`.

As for your local store, do you have a remote backup that you could restore?

**Comment by nickless81** [comment]
No I don't have a remote backup.
How can I restore the file store here?:
/data/user/0/com.zeapo.pwdstore/files/store

Please add a functionality to recover an existing hidden file instead of ONLY deletes it.

**Comment by msfjarvis** [comment]
Issue has gone stale, closing.
