### ISSUE TITLE
App crashes when selecting "entry" to unlock

### ISSUE THREAD

**Issue by plittlefield** [android-password-store/Android-Password-Store#450]
The app crashes when selecting any password entry to unlock.

Here is a (snipped) pastebin of adb logcat - [Android Password Store crash on selecting entry](https://pastebin.com/B0wNcCzT)

Any other part of the app seems fine, like Settings, etc.

:-)

Paully

Password Store 1.2.0.75
Android 9.0
Google Pixel 1 (sailfish)

**Comment by plittlefield** [comment]
Any news? It's still happening :-( I might have to change my password app...

**Comment by zeapo** [comment]
Hey, sorry for the delay. We'll fix the issue and deploy the latest version on play store.

**Comment by plittlefield** [comment]
Thank you!

**Comment by marcinma** [comment]
Actually it looks like app crashes always. With or without PGP key selected;. Any progress on that?

Mi A1 on LineageOS 15.1

**Comment by behrica** [comment]
It just started for me as well. For a long time I had no issue, just started now.

**Comment by FabianHenneke** [comment]
We have gone through several revisions since this was last confirmed. Please open a new issue if unlocking an entry should still crash the app for you.
