### ISSUE TITLE
Doesn't warn about existing password of same name before replacing

### ISSUE THREAD

**Issue by indiandragon** [android-password-store/Android-Password-Store#451]
If a new password is created and the 'name' for it is already existing, it silently replaces it with the new password. Dangerous if you have lot of passwords & multiple accounts; as you need to remember (or) search in prior if you have saved using the same name.

Please provide a warning before for existing name before saving.

**Comment by zeapo** [comment]
Thanks for the report. we'll check and fix that.

**Comment by zidhuss** [comment]
I've added an alert when a password already exists and is about to overridden (054056fa221e13fd58b41ecc66bfaa1d24baea81).

I believe that's all I can do for now until #322 is implemented. Then we could allow the user to abort a move operation.

**Comment by indiandragon** [comment]
@zidhuss The alert does not occur in 1.3.2, was it removed for some reason. I replaced a password due to this issue as there was no warning. This bug could lead to dangerous consequences.
