### ISSUE TITLE
Autofill keeps showing the Overlay permission dialog

### ISSUE THREAD

**Issue by canatella** [android-password-store/Android-Password-Store#452]
When trying to use autofill on Android > 8, the overlay permission popup is always shown instead of the password store popup. This is due to Settings.canDrawOverlays(this) always returning false in AutofillService.java line 191. According to https://stackoverflow.com/questions/46173460/why-in-android-o-method-settings-candrawoverlays-returns-false-when-user-has, it is due to bug https://issuetracker.google.com/issues/66072795. It would be nice to have a workaround because as of now the autofill feature is unusable on my Android 9.

I could do some testing if needed.

**Comment by canatella** [comment]
By the way, maybe the right solution would be to implement https://developer.android.com/guide/topics/text/autofill-services on Android >= 8.

**Comment by zidhuss** [comment]
This is something that is yet to be fixed. Some work was started on the issue in #411 though it's not yet complete.

**Comment by msfjarvis** [comment]
We've rolled out support for Android Oreo's Autofill feature and the older implementation is now unmaintained and unsupported.
