### ISSUE TITLE
Should APS really use the clipboard (by default)?

### ISSUE THREAD

**Issue by OffifialMITX** [android-password-store/Android-Password-Store#476]
[KDE Connect](https://cgit.kde.org/kdeconnect-android.git/) is able to run in background and read the clipboard contents, and nothing besides internal settings says explicitely that it has the permission to. Which means that basically any app can do the same and steal the passwords if it is mailicious.

**Comment by FabianHenneke** [comment]
Automatic copying of passwords upon decryption can be disabled in the settings and Autofill allows to fill password fields without going through the clipboard. Please open another issue if there is anything else we can do to further reduce the reliance on the clipboard.
