### ISSUE TITLE
Support for GPG smartcards

### ISSUE THREAD

**Issue by pinpox** [android-password-store/Android-Password-Store#479]
Hello,

I have migrated my keys on the desktop to a gpg smartcard. Is there support for smartcards via NFC or USB? If not, how hard would it be to implement?

If it is not possible to be used on a phone, what would be the best workflow to be able to use the keys on android? Multiple Subkeys?

**Comment by erayd** [comment]
Smartcards are already supported, via OpenKeychain. I personally use a Yubikey Neo via NFC, and can confirm it works excellently.

**Comment by FabianHenneke** [comment]
I can confirm that OpenKeychain's support for smart cards via NFC is excellent, so this is definitely the way to go.
