### ISSUE TITLE
Can't export to SD on Samsung 7.0

### ISSUE THREAD

**Issue by CaptainFrosty** [android-password-store/Android-Password-Store#481]
I am running (rooted) stock nougat 7.0 (Samsung 8.1) on galaxy s8+ and I can't export to SD, I have to copy it over from the internal storage. The storage permission is granted.

**Comment by msfjarvis** [comment]
Can you confirm this on the latest release and provide a log if it's still broken?

**Comment by msfjarvis** [comment]
This issue has gone stale, please open a new one if the problem still affects the latest release from the Play Store.
