### ISSUE TITLE
Password store ignores selected openkeychain key

### ISSUE THREAD

**Issue by dsmaynard** [android-password-store/Android-Password-Store#482]
I have two subkeys imported to my openkeychain, each linked to a different yubikey, and both of which have been used to encrypt my passwords. In the password store I have my preferred key selected (call it key 1), yet when I click to view a password, it asks me for the pin/yubikey corresponding to key 2, even though it shows the correct key id (key 1) listed in the Crypto section. 

If I delete key 2, then key 1 works fine and I'm able to open the password file. It seems like the password store is just selecting the first key, possibly by alphabetical order, from openkeychain?

Password store v 1.3.2
Openkeychain v 5.2
Pixel 3, Android 9 Pie

**Comment by Radtoo** [comment]
Observing the same issue with

Password store v 1.3.2
Openkeychain v 5.4

It does seem to only try one of the authorized keys. To work around this issue, you currently have to go to Openkeychain->Apps->Password Store and uncheck the other keys. At least you can avoid deleting the other key(s) this way.

**Comment by msfjarvis** [comment]
This should actually already be resolved in the snapshot build (available [here](https://dl.msfjarvis.dev/APS/)), can someone verify this?

**Comment by msfjarvis** [comment]
I can confirm this is fixed, closing the issue.

**Comment by zanona** [comment]
I'm not sure if this is related as this is related to the git repository authentication, but, by having my primary key + authentication subkey A on a smartcard and then, another authentication subkey B _(generated by the same primary key)_, stored on my device, causes an issue where only subkey A is attempted while subkey B never gets  tried. Unless I subkey A is removed.
It probably has to do with the fact that the prompt allows you to select a primary key instead of a specific authentication key.

**Comment by msfjarvis** [comment]
> I'm not sure if this is related, by having my primary key + authentication subkey A on a smartcard and then, another authentication subkey B _(generated by the same primary key)_, stored on my device, causes an issue where only subkey A is attempted while subkey B never gets tried. Unless I subkey A is removed.

Being tracked at #998 alongside other key handling semantics where GnuPG and OpenKeychain differ from each other.

**Comment by zanona** [comment]
Sorry, @msfjarvis, I realised I forgot to mention this is about the git repository authentication using openkeychain, rather than the encryption process itself? The issue mentioned seemed to be linked to issues around `.gpg-id` instead?
Perhaps this would be a better fit under a different issue?

**Comment by msfjarvis** [comment]
> Sorry, @msfjarvis, I realised I forgot to mention this is about the git repository authentication using openkeychain, rather than the encryption process itself? The issue mentioned seemed to be linked to issues around `.gpg-id` instead?
> Perhaps this would be a better fit under a different issue?

Yeah please file a separate issue.
