### ISSUE TITLE
External repo location input

### ISSUE THREAD

**Issue by syslino** [android-password-store/Android-Password-Store#484]
Hi, it would be great, if i could type in the path to an external repo on my device.

Currently the path picker is not able to  pick a path under /data/data... because it does not have permission to view that directory.

The background is, that I use pass in the termux App and I'd like to be able to use the same repo for the app and for termux.

**Comment by msfjarvis** [comment]
Whatever the picker cannot access, the app cannot either. Manually entering the Tasker path won't make it work.
