### ISSUE TITLE
Improve app flow

### ISSUE THREAD

**Issue by AeliusSaionji** [android-password-store/Android-Password-Store#500]
I appreciate this app but after having used it for over a year, I have come to realize that there are a few things that need to be done to make it more pleasant to use.

1. Open the keyboard with search bar focused when the app is opened. I'm opening this app to search for a password, don't make me manually tap the search button waaayyyy on the top of the screen. It's also strange that the floating action button is "add" rather than search. That button should be reserved for the most frequently used action, which is going to be search.
2. Present me with a flat directory structure, do not navigate into folders. Opening folders makes the app clunky and awkward, because the app session is preserved- as in, when I navigate to a folder, I will still be in that folder next time I open the app. Annoyingly, you need to hit the back button like 4 times to get out of a folder which brings any kind of usage flow to a grinding halt. The first few "backs" just exit out of search, and only THEN I can navigate up a folder. We just have to get rid of the filebrowser type behavior. When I search for `git` I want to see `github.com` with all associated usernames, and I should only need tap my username to have the pw copied to clipboard.

I assume everyone has used `passmenu` at some point- the dmenu based pass client. Let's take some lessons from how streamlined the flow of passmenu is. Search->enter->done.

Thank you for your work thus far!

**Comment by zidhuss** [comment]
I agree wholly with point number 1. The search feature should be more prominent as that's the primary action. I'm in favour of changing the FAB to search instead of add. I don't think the default behaviour should be to open up the keyboard. You're going to get users that will be annoyed that they'd have to dismiss the keyboard to navigate the app.

However, with point number 2 I do believe the directory structure is the right way to do things. `pass` works on the directory structure.

> When I search for git I want to see github.com with all associated usernames, and I should only need tap my username to have the pw copied to clipboard.

Is this not what happens now when you perform a search?

**Comment by AeliusSaionji** [comment]
![](https://i.imgur.com/QHDvcII.png)

 I see now that if I search for usernames the search will recurse.

 However 99% of my user names are the same email address, so I search for domain name to get useful results. 

 But then I get what you see here, just a folder. And then I navigate into that folder, and see my initial post for the problems with that.

**Comment by AeliusSaionji** [comment]
Oh, and I follow the following structure 

domain/username.gpg

**Comment by AeliusSaionji** [comment]
> pass works on the directory structure

have you used dmenu based passmenu?

I'm not saying to eliminate directories, I'm just saying that directories by themselves are not useful as a search result, and the way we navigate directories in this app causes a lot of needless interaction overhead.
