### ISSUE TITLE
Add verbose mode to debug issues in production

### ISSUE THREAD

**Issue by nohn** [android-password-store/Android-Password-Store#501]
The app should offer a verbose mode to debug issues in production: I can't fetch my repository, the app just hangs and it would be really helpful to see, where it hangs.

**Comment by msfjarvis** [comment]
Prod will now default to verbose

**Comment by Skrilltrax** [comment]
Shouldn't we provide a switch for verbose mode ?

**Comment by msfjarvis** [comment]
> Shouldn't we provide a switch for verbose mode ?

Yes I mentioned that in the PR. I was waiting to finish the Dagger introduction before I work on that. Really need to clean-up our preferences so that'll get rolled up with this toggle too.
