### ISSUE TITLE
Push to remote - doesn't do anything

### ISSUE THREAD

**Issue by kalee** [android-password-store/Android-Password-Store#506]
I have my repository in bitbucket.  It is cloned on a chromebook, IOS phone, and an Android phone.  I just finished a month long trip, and added several knew passwords on the Android phone.  I confirmed that the repository was never updated.
press the three dots
Push to remote
{message} You have to set the information about the server before ....
ON MY WAY ...
Git/Edit git server settings
(verify server and hit save button)
(press <- Password Strore)
Authenticate {Enter password for bitbucket.org}
{running command}
Returns back to Password Store screen
No change....

Settings:
Crypto: OpenKeychain

I have imported my SSH Key.  That is how I see the repository.

Any suggestions appreciated.  Thank you!
If there is a link for instructions to get logs, please share.

**Comment by msfjarvis** [comment]
Please create another issue if this is still a problem on the current stable release.
