### ISSUE TITLE
Open a specific entry with Tasker

### ISSUE THREAD

**Issue by CarloDePieri** [android-password-store/Android-Password-Store#512]
I'm trying to open the app directly at a specific entry (so I only have to input the main password to get the password of that entry) by using Tasker.
I think I could use an intent to do so, but I don't know the correct parameters.

It should be possible, since Nova+Sesame manage to create a shortcut with the following intent that does exactly what I want: 
```
#Intent;action=ninja.sesame.app.action.LINK_RELAY;component=ninja.sesame.app.edge/.bridge.LinkRelayActivity;S.linkId=deeplink%3A%2F%2Fcom.zeapo.pwdstore%2FappShortcut%2F%2Fdocs%2Fcarlo%2F%23com.zeapo.pwdstore%2F.PasswordStore;B.isSearch=false;end
```
This somehow opens the entry /docs/Carlo/mykey
Thing is, simply copying that intent into Tasker Autoshortcut does not work... Am I missing something? Thank you for your time!

**Comment by msfjarvis** [comment]
Sesame processes the app shortcuts we create for recently used passwords and uses those as deeplinks. That string is not a direct intent action. You can open passwords directly by following the code [here](https://github.com/android-password-store/Android-Password-Store/blob/d695d21497e5f54f78316f77a1d637009b3ee633/app/src/main/java/com/zeapo/pwdstore/LaunchActivity.kt#L42-#L49). The activity is `com.zeapo.pwdstore.crypto.PgpActivity`, the string extras are all in the code.
