### ISSUE TITLE
auth fail when using gpg smartcard

### ISSUE THREAD

**Issue by bricewge** [android-password-store/Android-Password-Store#517]
Using the new [signed build](https://github.com/zeapo/Android-Password-Store/blob/bca66a12e981b13c24cf4d1bccdea6be1fcc6eba/app/release/app-release.apk) I wasn't able to use an OpenPGP card, in my case a Yubikey 5 NFC, for SSH authentication.

Following the instructions in the [wiki](https://github.com/zeapo/Android-Password-Store/wiki/Generate-SSH-Key#from-openkeychain-coming-soon) didn't helped. By the way "Share as SSH public key" from OpenKeychain generated an public key I don't know of. But even when using the correct SSH public key, generated with `ssh-add -L`, it didn't worked. I tired several times, on two git servers, resting the app data and cache each time.

Here is the error:
```
Auth fail
Caused by: org.eclipse.jgit.errors.TransportException: git@server.me/username/repo.git: Auth fail
```

Related with #486.

**Comment by jagd** [comment]
Maybe related to this. I got this error by using OpenKeyChain SSH key.

![grafik](https://user-images.githubusercontent.com/108780/61498169-7ef13f80-a9c2-11e9-809f-732b8e3deb68.png)

**Comment by bricewge** [comment]
I don't encounter this issue anymore with Passowrd Store 1.3.3 and OpenKeychain 5.4. Using a smartcard through NFC to clone a repo and then decrypt passwords works as expected.

Thank you all for your hard work!
