### ISSUE TITLE
overlapped buttons

### ISSUE THREAD

**Issue by 532910** [android-password-store/Android-Password-Store#522]
It doesn't fit into the line in russian locale:
![image](https://user-images.githubusercontent.com/14617699/60479081-3a109d80-9c8d-11e9-87b6-293128bef3d0.png)

**Comment by MSF-Jarvis** [comment]
Thanks for the report, I'll re-evaluate this layout in my redesign PR which you can track at #519

**Comment by 532910** [comment]
Not fixed in v1.3.3, please reopen

![image](https://user-images.githubusercontent.com/14617699/69691863-518b6f80-10e1-11ea-91d3-486b1da25cab.png)

**Comment by msfjarvis** [comment]
> Not fixed in v1.3.3, please reopen
> 
> ![image](https://user-images.githubusercontent.com/14617699/69691863-518b6f80-10e1-11ea-91d3-486b1da25cab.png)

There has been no release since the commit was merged.

**Comment by 532910** [comment]
Oh, sorry.
