### ISSUE TITLE
Add ssh-ca-certificate ability

### ISSUE THREAD

**Issue by xundeenergie** [android-password-store/Android-Password-Store#527]
There is a some year old (relatively new) feature on openssh called "Certificates". (Look at https://framkant.org/2016/10/setting-up-a-ssh-certificate-authority-ca/)
This is a real cool feature and enhances ssh-security enormous.

What do i need for in Android-Password-Store?
I need the possibility to add a line in know_hosts file in format:
```
@cert-authority * ssh-rsa AAAAB3NzaC1yc2EAAAADAQABA
```
this is the public key from my own ssh-certification authority.
And i need to store the the certificate from my public key (generated with Password-Store, send to CA-Host, sign it, import certificate back) additionally to private and public key.

And Password-Store must support certificates for ssh althoug... ;-)

This is a real secure new feature. Please support it...

**Comment by msfjarvis** [comment]
SSHJ does not support this yet: https://github.com/hierynomus/sshj/issues/281

**Comment by msfjarvis** [comment]
https://github.com/hierynomus/sshj/pull/703

Support for this is hopefully coming in the next release

**Comment by msfjarvis** [comment]
SSHJ support for this feature is now available so I'll try to get it out over this weekend.

**Comment by msfjarvis** [comment]
Closing as part of [issue tracker cleanup](https://github.com/android-password-store/Android-Password-Store/discussions/1836).
