### ISSUE TITLE
UI button to create folders

### ISSUE THREAD

**Issue by Schueni1** [android-password-store/Android-Password-Store#528]
A more obvious way to create folders would be nice. The current way is not very intuitive.

Right now I create folders by naming a new password "folderName/passwordName".

**Comment by CaptainFrosty** [comment]
I didn't even know that was possible, thanks. I can't create folders with the button, or keys inside folders. I have to manually edit the vault.

**Comment by AluminumTank** [comment]
I think that this would be a great feature to use the FAB (Floating Action Button) for, so that it can create both passwords and folders.
