### ISSUE TITLE
Copying implicit username

### ISSUE THREAD

**Issue by madduck** [android-password-store/Android-Password-Store#529]
This is similar to #375, but a lower-hanging fruit, and slightly different too.

I use the `domain/username.gpg` convention, so most of my files don't have any extra data, just the password. There are times when I'd like to copy the username, i.e. the filename. Unfortunately, this does not seem possible, and I cannot long-press on the text either, not even during edit mode, to have Android select the text so I can copy it.

So an option "Copy username to clipboard" or an icon next to the username to click would be useful.

Thanks!

**Comment by braderhart** [comment]
Would like to see this too. I often generate random usernames on sites, and it is really difficult to populate them currently on Android.

**Comment by Skrilltrax** [comment]
Changes merged into master.
