### ISSUE TITLE
Sort by recently used

### ISSUE THREAD

**Issue by durka** [android-password-store/Android-Password-Store#535]
Some passwords I look up all the time. It would be nice to have a "recently decrypted" / "favorites" view.

**Comment by Dioxo** [comment]
Is anyone currently working on this?
I'd like to work on this issue.

**Comment by msfjarvis** [comment]
> Is anyone currently working on this?
> I'd like to work on this issue.

Nope, all yours. I'll assign you.

**Comment by Dioxo** [comment]
I think we can now close this issue. @msfjarvis :)
