### ISSUE TITLE
When we select OpenKeychain auth we get an exception

### ISSUE THREAD

**Issue by zeapo** [android-password-store/Android-Password-Store#539]
When setting up the repo. If we use the OpenKeychain auth, it expects to find the ssh key, and hence raises an exception.

Moreover, it always asks for authorization, for every action... this should not be the right behaviour. This was not handled in the original PR.

**Comment by msfjarvis** [comment]
#554 resolved the second part of this AFAIK

**Comment by msfjarvis** [comment]
@FabianHenneke IIRC you use OpenKeychain for SSH auth, mind checking if this is still an issue?

**Comment by FabianHenneke** [comment]
Works exactly as expected: I am being asked for authorization on the first clone, but not thereafter.
