### ISSUE TITLE
Error during a Git operation

### ISSUE THREAD

**Issue by grighi** [android-password-store/Android-Password-Store#543]
When trying to pull from my computer, I'm getting

Message from jgit: ssh://myuser@server:22: org.eclipse.jgit.transport.CredentialItem$StringType:Password:
Caused by: 
null

I tried deleting the repo and starting a new one. I'm cloning from a bare repo with the correct password to get into my computer.

**Comment by msfjarvis** [comment]
Please open another issue if you can reproduce this on the current stable release.
