### ISSUE TITLE
Import SSH not working

### ISSUE THREAD

**Issue by salotz** [android-password-store/Android-Password-Store#546]
Hello thanks for making the app. One problem I had though was importing SSH keys. After I selected the key I wanted to import and then tried to push (after I registered the key in my git server) it gave me an error saying that the key could not be found. I then tried the key generation option which worked and I can push to the server. I then attempted to select another key I generated (using ConnectBot) and this failed again. I attempted to reselect the one that was generated from the Password store app and this failed again. So I know it is something to do with the import process itself.
I'm fine with using the key generation for now, but I do hope that the import feature is made to work so I can use the same key for all my SSH stuff on that device.

**Comment by saruman9** [comment]
dup https://github.com/android-password-store/Android-Password-Store/issues/442
