### ISSUE TITLE
committor should be turned into friendly bot

### ISSUE THREAD

**Issue by salotz** [android-password-store/Android-Password-Store#547]
I hope this is only an aesthetics ting, but this is the commit I get from pushing from the app to my repo on gitlab. It automatically links me to the user "Tripple Moon" who I am assuming is a developer. Its a little creepy since this is my password server... Could you please change this to a friendly password store user with the icon image?

![image](https://user-images.githubusercontent.com/7883146/65826202-9ebca380-e24e-11e9-83bb-3415762a7b52.png)

**Comment by msfjarvis** [comment]
If you don't set a custom author and email it defaults to `root@localhost`, none of the developers are written into the app.
