### ISSUE TITLE
Support multiple authentication methods

### ISSUE THREAD

**Issue by maxammann** [android-password-store/Android-Password-Store#548]
Hello,

I configured my SSH server to expect multiple authentication methods:

```
AuthenticationMethods publickey,password
```

When I select "ssh-key" as the method the git pull fails with the following error:

<img src="https://user-images.githubusercontent.com/905221/65830425-9a74a280-e2af-11e9-81a1-49786991076a.png" width="300">

When I select username/password as method the authentication just fails:

<img src="https://user-images.githubusercontent.com/905221/65830433-a2344700-e2af-11e9-8234-dedb948c3d6a.png" width="300">

- jgit Docu: https://www.codeaffine.com/2014/12/09/jgit-authentication/
- Authentication code in Password-Store: https://github.com/zeapo/Android-Password-Store/blob/f05c0b37ca0df5cab4906d5484572d0288c479ed/app/src/main/java/com/zeapo/pwdstore/git/GitOperation.kt#L51

**Comment by FabianHenneke** [comment]
@msfjarvis I think that SSHJ could handle multiple authentication methods somewhat easily. I'm just unsure about the correct way to handle this in the UI. We could simply always allow password authentication if needed after performing public key authentication, which wouldn't need any additional UI. What do you think?

**Comment by msfjarvis** [comment]
> @msfjarvis I think that SSHJ could handle multiple authentication methods somewhat easily. I'm just unsure about the correct way to handle this in the UI. We could simply always allow password authentication if needed after performing public key authentication, which wouldn't need any additional UI. What do you think?

I think that'd work well.
