### ISSUE TITLE
An error during Git operation

### ISSUE THREAD

**Issue by srustamo** [android-password-store/Android-Password-Store#552]
MacOS 10.13.6
Android 6.0.1
Latest F-Droid 

Syncing on a LAN via ssh to a local machine with a bare git repo. Same setup but with iOS version works fine.

On Android, cloning a local bare git repo fails with the following error:

Message from jgit: ssh://srxx@192.168.0.11:22:org.eclipse.jgit.transport.CredentialItem$StingType:Password:Causedby:null

**Comment by msfjarvis** [comment]
F-Droid release is terribly out of date and has been dropped as an official release channel for now. Can you test for this issue on a recent build from any of the sources currently listed in the README?

**Comment by msfjarvis** [comment]
This issue has gone stale, please open a new one if the problem still affects the latest release from the Play Store.
