### ISSUE TITLE
impossible to clone repository

### ISSUE THREAD

**Issue by 5752379147142** [android-password-store/Android-Password-Store#553]
I updated Password Store to version 1.3.3 and now synchronization of the repository is impossible.
I tried to wipe all data and re-configured like it used to be with version 1.3.2 with no joy.
When I try to configure the server via https the following error shows up:
"An erro occurred during a Git operation
Error occurred during the operation,
Message from jgit:
Invalid remote: origin
Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException:https://github.com/XXX:https://github/XXX/info/refs?service=git-upload-pack not found."

When I try to configure the server using ssh the app says that I forgot to specify a username although it is set properly.

Please help me! The app used to work like a charm but now it is useless!

**Comment by msfjarvis** [comment]
Seems like a configuration error on your end. If you can share more information about your setup (What Git provider you're using, if the repo is initialized already, etc) then we can possibly try to resolve this.

**Comment by 5752379147142** [comment]
Thank you for your reply!
git provider is github.com
the repo is the very same one I used to synch with app v1.3.2 and it is initialized already.

When I try to configure the ssh I get the following error:
![Inkedphoto_2019-10-12_23-28-12_LI](https://user-images.githubusercontent.com/49161999/66707880-2ffc4180-ed48-11e9-992e-c686ca24216b.jpg)

**Comment by jessesimpson36** [comment]
Can confirm that cloning in this app is broken.

**Comment by zeapo** [comment]
From the screen, you're using the "ssh" protocol with a "https" server url. 

the easiest for you would be to copy/paste the URL given from github directly into the "Resulting URL" field. It will automatically fill the rest of the fields.
