### ISSUE TITLE
Cannot select OpenPGP Key id

### ISSUE THREAD

**Issue by kaiwk** [android-password-store/Android-Password-Store#555]
platform: Android
password-store: 1.3.2
OpenPGP: 5.3

see: #346 

I tried reinstalling both apps, but still not working.

When I long pressed password item for editing, it toasts like below:
> Password Store: Failed to get last changed date.

**Comment by kaiwk** [comment]
I can't select OpenPGP Key id in Settings either.

**Comment by helmo** [comment]
I had another go at this.  I removed the openkeychain once more and re-installed it via F-droid.
After importing the keys it was working again ... but not anymore after a reboot.

Here's a screenshot of what I see after I tap 'Select OpenPGP Key id': 
![P_20191113_091948_vHDR_Auto](https://user-images.githubusercontent.com/104120/68745719-79fe6e80-05f7-11ea-8fec-a5b46a189c91.jpg)

Re-installing Android-Password-Store from F-droid made no difference.

**Comment by Radtoo** [comment]
On MIUI I need to configure security permissions to allow popups and further authorize accessing OpenKeychain. Maybe your ROM's security or current security settings get in the way?

**Comment by kaiwk** [comment]
> On MIUI I need to configure security permissions to allow popups and further authorize accessing OpenKeychain. Maybe your ROM's security or current security settings get in the way?

Thank you for the help. After I authorize the OpenKeychain permission "start in background", it works. I will close the issue, if someone has similar problem, I'd suggest to check the Android app permission first.

**Comment by gregorlarson** [comment]
Even though this work-around does work, there is room for improvement. Perhaps an error message indicating the missing permission?

**Comment by msfjarvis** [comment]
> Even though this work-around does work, there is room for improvement. Perhaps an error message indicating the missing permission?

The permission's not missing from this app, it's missing from Open Keychain. They need to remedy it.
