### ISSUE TITLE
Add indicator for number of items in folder

### ISSUE THREAD

**Issue by AluminumTank** [android-password-store/Android-Password-Store#559]
See title. I got this idea from [passforios](https://github.com/mssun/passforios):

![screenshot1](https://user-images.githubusercontent.com/19600707/67233189-bda6f380-f410-11e9-9d90-4d7cbd3952ea.png)

**Comment by AluminumTank** [comment]
I tested #562 to see how it works. It correctly counts password entries in the directory, but does not correctly count subdirectories. For cases where there are only subdirectories in a directory, either no count is shown, or the wrong count is shown:
![Screenshot-2019-11-13-12-14-46](https://user-images.githubusercontent.com/19600707/68787390-71b22d80-060f-11ea-8358-e81ad9cf005a.jpeg)

(Contents of `minetest`:)
![Screenshot-2019-11-13-12-19-56](https://user-images.githubusercontent.com/19600707/68787704-087eea00-0610-11ea-9b37-dfec6683d763.jpeg)

(Contents of `osmc`:)
![Screenshot-2019-11-13-12-21-42](https://user-images.githubusercontent.com/19600707/68787946-70cdcb80-0610-11ea-85d4-9540d30688d6.jpeg)

As can be seen, the count for `minetest` should be 1 (not blank), and the count for `osmc` should be 1 (not 2).

**Comment by msfjarvis** [comment]
> I tested #562 to see how it works. It correctly counts password entries in the directory, but does not correctly count subdirectories. For cases where there are only subdirectories in a directory, either no count is shown, or the wrong count is shown:
> ![Screenshot-2019-11-13-12-14-46](https://user-images.githubusercontent.com/19600707/68787390-71b22d80-060f-11ea-8358-e81ad9cf005a.jpeg)
> 
> (Contents of `minetest`:)
> ![Screenshot-2019-11-13-12-19-56](https://user-images.githubusercontent.com/19600707/68787704-087eea00-0610-11ea-9b37-dfec6683d763.jpeg)
> 
> (Contents of `osmc`:)
> ![Screenshot-2019-11-13-12-21-42](https://user-images.githubusercontent.com/19600707/68787946-70cdcb80-0610-11ea-85d4-9540d30688d6.jpeg)
> 
> As can be seen, the count for `minetest` should be 1 (not blank), and the count for `osmc` should be 1 (not 2).

Pleae test #573

**Comment by AluminumTank** [comment]
Tested with #573, working as expected. Thanks!
