### ISSUE TITLE
Remotely generated passwords doesn't work with openkeychain

### ISSUE THREAD

**Issue by bernerha** [android-password-store/Android-Password-Store#560]
Hello,

I have a very strange behavior.
I changed my setup to OpenKeychain + yubikey gpg and re-encrypted all my passwords with my new key. Everything works fine on my different computers.

I deleted the repo in Password Store and cloned it again.
But if i try to decrypt one of the keys in Password Store I get the error:
`Error from OpenKeychain: No encrypted data with known secret key found in stream!`
(btw error messages shouldn't disappear that fast ;) )

On the other hand if I create a password in Password Store everything works fine, I get asked for the pin/yubikey. It's also possible to decrypt the password on my computers.

New passwords generated on my computer also doesn't work.

Phone: OneplusA6003 with OxygenOS 9.0.9
Password Store: 1.3.2 from fdroid
OpenKeychain: 5.4 from fdroid

I already reinstalled both apps.

Regards

**Comment by zeapo** [comment]
Hi @bernerha 

Can you check that you've associated the correct key in openkeychain from APS?

A radical way to be sure you're using the correct key is to go to openkeychain > apps, click on password store. Use the three dots up-right, and click on revoke. Next, in APS, go to settings and configure again your open keychain key id. It will prompt you to allow APS and to select the key again.

**Comment by bernerha** [comment]
Hi,

already tried it. Same outcome.
Is there a easy way to debug the app on my phone? My knowledge about Android dev is limited :)

**Comment by bernerha** [comment]
Got it, I think. I'll try Android studio and the remote debugging.

**Comment by bernerha** [comment]
Found the Problem :+1: 
I use a hardened gpg.conf with:
```
# Disable putting recipient key IDs into messages
throw-keyids
```
And Openkeychain can't handle this. I'm going to change that option.
Or is there any change it will work without the identity in the header?

Regards
