### ISSUE TITLE
Xiaomi: on OpenPGP dialog fail: proper error message with advice to fix

### ISSUE THREAD

**Issue by d9k** [android-password-store/Android-Password-Store#589]
When I click "Select OpenPGP Key id" in Password Store settings empty page shows for a moment but immediately closes (slides to left).

Xiaomi Redmi Note 4.
MIUI 10, 11
tried to remove and install recent version of OpenPGP (5.4) and Password Store (1.3.3) from F-Droid.

The app worked well but broke several weeks ago

**Comment by d9k** [comment]
OK, I find solution: 

for OpenKeyChain:
Other permissions -> Display popup window while running in the background.

I think the Password Store must detect inability to access OpenPGP and should show error messages with advice to change application settings for Xiaomi phone user.

**Comment by Skrilltrax** [comment]
@d9k This is a OEM specific behaviour and we will try to add [dontkillmyapp](https://dontkillmyapp.com) to future releases.
