### ISSUE TITLE
[BUG] Error: q::c:: is not in the password store.

### ISSUE THREAD

**Issue by gigavinyl** [android-password-store/Android-Password-Store#590]
**Describe the bug**
When I try to run pass in order to unlock a password, I get this error `A clear and concise description of what the bug is.`

**To Reproduce**
Run `pass example.com`

**Expected behavior**
Return password

**Device information (please complete the following information):**
 - Device: Thinkpad X230
 - OS: NetBSD 9.0_RC1
 - App version 1.7.3

**Comment by Skrilltrax** [comment]
Hey, APS is an app to work with passwords created using pass. This is **not** a place to file pass bugs.

**Comment by gigavinyl** [comment]
Oh shoot! So sorry, I didn't realize this was the wrong repo!

**Comment by Skrilltrax** [comment]
No problem :+1:
