### ISSUE TITLE
[BUG] jgit TransportException when synchronizing repository

### ISSUE THREAD

**Issue by kietoparao** [android-password-store/Android-Password-Store#591]
**Describe the bug**
I get a JGit `TransportException` error when trying to Synchronize repository using the android app. Not really sure if it's a dup of #568, that's why I'm opening a new one.

**To Reproduce**
1. Go to android app "Password Store"
2. Click on the three-dotted icon up on the right corner
3. Click on "Synchronize repository"
4. See `TransportException` error

**Expected behavior**
The app is able to connect via ssh-key to the server and update the passwords on the Android phone

**Screenshots**
![jgit_error](https://user-images.githubusercontent.com/31295319/70577526-b21faf80-1bab-11ea-8ec1-81cb0e34eb41.jpeg)

**Device information (please complete the following information):**
 - Device: Xiaomi Redmi 3S
 - OS: MIUI Global 10.2.2.0 (MALMIXM)
 - App version: 1.3.1

**Additional context**
My gpg key expired 3 days ago, so the first issue I encountered (now solved) was that I couldn't view the passwords from the android app because of that. I imported the renewed gpg key to OpenKeyChain app and it worked again. Then, I tried to synchronize the repository and that's when I got the error here explained. I followed all the steps on the wiki page to [generate an SSH key from a terminal](https://github.com/android-password-store/Android-Password-Store/wiki/Generate-SSH-Key) to try to use a new SSH key on the Password Store android app, but the same `TransportException` error appeared.

If anyone can help me debug this, I really appreciate it because I'm out of ideas to try to fix this :)

**Comment by msfjarvis** [comment]
This does not look like a problem with the app because it says that your server is denying access.

**Comment by kietoparao** [comment]
> This does not look like a problem with the app because it says that your server is denying access.

You're right, later I found out that it was only a network permission error given to the android App, sorry for the confusion. I'm closing it.
