### ISSUE TITLE
[BUG] OpenKeychain doesn't appear in Authentication Mode dropdown

### ISSUE THREAD

**Issue by kevinoid** [android-password-store/Android-Password-Store#596]
**Describe the bug**
I am attempting to configure Password Store to use an HSM via OpenKeychain for both PGP and SSH, but in the "Repository information" settings, "Authentication Mode" only contains "ssh-key" and "username/password", not "OpenKeychain" as it does on another device

**To Reproduce**
1. Install [OpenKeychain](https://play.google.com/store/apps/details?id=org.sufficientlysecure.keychain) version 5.4 (54000) from Play Store.
2. Import key in OpenKeychain and confirm the key has an authentication subkey (as described in [Generate SSH Key](https://github.com/android-password-store/Android-Password-Store/wiki/Generate-SSH-Key#from-openkeychain-coming-soon) on the Wiki).
2. Install [Password Store](https://play.google.com/store/apps/details?id=com.zeapo.pwdstore) version 1.3.2 from Play Store.
3. Open Password Store
4. Press "Clone From Server"
5.  Press either "SD-Card" or "Hidden (Preferred)"
6.  Tap "Authentication Mode" dropdown and observe only "ssh-key" and "username/password" options.

**Expected behavior**
"OpenKeychain" would appear in the "Authentication Mode" dropdown (as it does on my other device).

**Device information (please complete the following information):**
 - Device: Google Pixel
 - OS: Stock Android 10 (QP1A.191005.007.A3)
 - App version: Password Store 1.3.2, OpenKeychain 5.4 (54000)

**Additional context**
Note:  Although the wiki has "Coming Soon" next to OpenKeychain, it was working well on my previous device and #486 was merged a while ago.  Let me know if there's anything else I can do to troubleshoot, or any steps I'm forgetting.

Thanks,
Kevin

**Comment by msfjarvis** [comment]
Can you reproduce this on the [latest debug](https://github.com/android-password-store/Android-Password-Store/suites/359276007/artifacts/700671) APK? 

Note to self: Setup signed snapshots on my server...

**Comment by kevinoid** [comment]
Nope.  OpenKeychain *does* appear in the "Authentication Mode" dropdown in the debug APK you linked.  (It also looks slick!)  Thanks!  Is it likely to be released soon?

**Comment by msfjarvis** [comment]
> Nope. OpenKeychain _does_ appear in the "Authentication Mode" dropdown in the debug APK you linked. (It also looks slick!) Thanks! Is it likely to be released soon?

I really cannot tell at this point when this will go out. @zeapo  has stepped back from the project but the Play Store listing has not been transferred to my account yet, nor has he provided me the signing keys for the project so I cannot release a new version even if I wanted to.

Like I said, I'm going to be setting up snapshots for the app so that people can stay up-to-date with master while I wait for Mohamed to complete the handover.

**Comment by kevinoid** [comment]
That sounds frustrating.  Thanks for the extra effort to provide snapshots and continue work on the project.  I certainly appreciate it!

**Comment by msfjarvis** [comment]
> That sounds frustrating. Thanks for the extra effort to provide snapshots and continue work on the project. I certainly appreciate it!

Thanks for the kind words :)

Can you close the issue if it's fixed for you? I'm gonna be making an announcement about the whole release situation shortly.

**Comment by kevinoid** [comment]
Sure thing.  Sounds great.  Thanks again!
