### ISSUE TITLE
[BUG] Can not select openPGP key id

### ISSUE THREAD

**Issue by jscolaire** [android-password-store/Android-Password-Store#598]
**Imposible select openpgp key**
I got password-store 1.3.2 version and OpneKeychain 5.4 version. I can not select OpenGPG key id, the screen to select this key is showed and inmediately closed. 
My phone is Xiamoi MI 8 and the applications both was working well and suddenly password-store can not work.

**To Reproduce**
1. Go to 'Settings->Select OpenPGP key id'

And no more, the screen to select key is not showed

**Expected behavior**
The application have show screen for select key

**Device information (please complete the following information):**
 - Device: Xiaomi MI8
 - OS: MIUI Global 11.0.6 Android 9
 - App version 1.3.2

**Comment by msfjarvis** [comment]
Try the workarounds in #518

**Comment by jscolaire** [comment]
Ok thanks, it works
