### ISSUE TITLE
Select openPGP Key id is empty 

### ISSUE THREAD

**Issue by SEPEZHO** [android-password-store/Android-Password-Store#603]
Hello, i have one pgp key in OpenKeychain. In password store i select this app. But when i try to select pgp key, app (password store) dot redirect me in openkeychain app, he just show me white screen. And thats all. Can u help me?

**Comment by msfjarvis** [comment]
Please fill out the template properly so we can help you without having to guess things back and forth.

**Comment by echuraev** [comment]
@msfjarvis I have the same problem. When I'm trying to select my pgp key then I see a white screen for a one or two seconds and then it returns to the previous screen with settings. I'm trying to use Password-store on Xiaomi Mi9t.

**Comment by msfjarvis** [comment]
> @msfjarvis I have the same problem. When I'm trying to select my pgp key then I see a white screen for a one or two seconds and then it returns to the previous screen with settings. I'm trying to use Password-store on Xiaomi Mi9t.

Refer to #518

**Comment by echuraev** [comment]
Thanks, that works for me!
