### ISSUE TITLE
[BUG] Autofill dialog window is too small

### ISSUE THREAD

**Issue by Gigahawk** [android-password-store/Android-Password-Store#611]
**Describe the bug**
Autofill dialog is too small in portrait mode to see any entries.
Two entries can be seen in landscape mode but it's still really small.

**To Reproduce**
1. Enable autofill
2. Open an app with autofill configured
3. See small autofil dialog

**Expected behavior**
Autofill dialog should be reasonably sized.

**Screenshots**
<img src="https://imgur.com/ppsMv0E.png" width="260">&emsp;
<img src="https://imgur.com/mr0J5Kl.png" width="260">&emsp;

**Device information (please complete the following information):**
 - Device: Nexus 5X Emulator
 - OS: stock ROM Android version 10.0
 - App version 1.3.4-SNAPSHOT-debug (commit 8189651)

 - Device: Oneplus 6
 - OS: OxygenOS Android version 9.0
 - App version 1.3.4-SNAPSHOT-debug (commit 8189651)

**Comment by msfjarvis** [comment]
I've merged #612. Thanks!
