### ISSUE TITLE
Validate SSH keys during import

### ISSUE THREAD

**Issue by msfjarvis** [android-password-store/Android-Password-Store#619]
I managed to accidentally import a 1080p video as an SSH key and trigger OOMs during SSH operations seven times before realising what was up. This should not be allowed to happen.

**Comment by msfjarvis** [comment]
I can't seem to find anything in Jsch that would allow actually validating the key, all code samples I found tell me to attempt a connection for validation which defeats the usecase we're trying to patch. Open to any pointers on how to approach this.

**Comment by Dioxo** [comment]
what about trying to validate the file extension and size?
I would think that if the size is less than 100KB and without file extension, you could "validate" that it is a SSH key.
I think it would be a good validation to at least discard files that couldn't be keys.

I'm working on it to show you.

**Comment by chschlue** [comment]
Not sure about file extension as it doesn't actually tell you anything and might not be present at all, depending on source.
Other than that it's small (sanity check) as @Dioxo said, it's also random by design and cannot really be validated.

**Comment by Dioxo** [comment]
The only way that i found to validate a key, is by console `$ ssh-keygen -y -f KEY`, but i've not found a library or code sample that does it.

**Comment by msfjarvis** [comment]
A size check does not sound that far fetched but I'd like to properly validate is possible. I'm also considering entirely getting rid of Jsch and using [SSHJ](https://github.com/hierynomus/sshj) instead.

**Comment by msfjarvis** [comment]
Fixed by #709, thanks for your contribution @Dioxo!
