### ISSUE TITLE
[BUG] Pulling/Pushing/Synchronizing doesn't work

### ISSUE THREAD

**Issue by matrixes** [android-password-store/Android-Password-Store#629]
**Describe the bug**
I was able to clone the repository once, and since that day, I haven't been able to push/pull/synchronize any of the information.
When I try to synchronize, there is a repeated nag screen that I have to "set the information about the server before synchronizing with the server" with "Nah... Later" and "On my way..." buttons.
No matter how may times I go to "set the information" about the server, nothing happens.
I'm honestly not even sure _what_ information I'm expected to set.

**To Reproduce**
1. Clone git repo
2. Click on 'ActionBar menu'
3. Click on 'Synchronize or Push or Pull'
4. Get the dialog that tells you to "set the information"

**Expected behavior**
* Explain to me exactly what's missing so I can fix it
* Make dialog buttons and messages more informative

**Device information (please complete the following information):**
 - Device: Google Pixel 3 XL
 - OS: stock ROM Android version 10.0
 - App version: 1.4.0

**Additional context**
* Not being able to synchronize my information is rendering this app next to useless. I can still use this _somewhat_ by the first clone, but it gets outdated _fast_.
* What does the "Nah... Later" button even mean? Cancel? Skip setting information and synchronize anyway? As a user I need clear and concise information about what will happen when I press buttons.

**Comment by msfjarvis** [comment]
I agree that the dialog is very poorly worded and needs fixing. From what I see, the dialog shows only in two cases:

- No OpenPGP key is selected in settings.
- One of git username, server, remote repository name: is empty.

**Comment by matrixes** [comment]
Alright, that gave me at least something to troubleshoot without messing around blindly.

In my case the field "Repo path" is empty. If I put at least one character in that field I am taken to the password prompt. However, I haven't figured out a character that doesn't end up in a failed connection. My repo doesn't require/take a path, so the connection errors out because there is something set in that field.

**Comment by msfjarvis** [comment]
> Alright, that gave me at least something to troubleshoot without messing around blindly.
> 
> In my case the field "Repo path" is empty. If I put at least one character in that field I am taken to the password prompt. However, I haven't figured out a character that doesn't end up in a failed connection. My repo doesn't require/take a path, so the connection errors out if there is something set in that field.

If you directly paste the clone URL in the `Repository URI` field the app will attempt to automatically fill the relevant fields. If that doesn't work, can you share the URI here so I can figure out if the app needs any fixes?

**Comment by matrixes** [comment]
**Example**
Protocol: https
Username: [user]
Server URL: https://gitlab.com/[user]/[project].git
Port: [empty]
Repo path: [empty]
Repository URI: https://gitlab.com/[user]/[project].git/
Authentication Mode: username/password

I guess the way you could repeatedly verify this behaviour would be to create a Gitlab account and a project, pushing, pulling and synchronizing through that.

**Comment by matrixes** [comment]
And as an addition I don't get this behaviour:

> If you directly paste the clone URL in the `Repository URI` field the app will attempt to automatically fill the relevant fields.

but instead if I paste the clone URL in the `Server URL` field, `Repository URL` gets filled, but none of the others.

Maybe this is a side effect of me already having had information set before trying to paste the clone URL again, I can't tell anymore. This section of the app is pretty messy no matter how I slice it, in consistency, intuitiveness and behaviour.

**Comment by msfjarvis** [comment]
I apologize for the historically confusing UX there, it's a very high priority item in the list of things we want to do right from the get-go on v2. I have confirmed that setting the `Repository URI` field to `git@gitlab.com:<username>/<repository_slug>.git` for ssh and `gitlab.com/<username>/<repository_slug>.git` for HTTPS lets me clone/push/pull/synchronize the repository perfectly. For HTTPS I also have my username set and use a personal access token for a password due to 2FA.

**Comment by matrixes** [comment]
No need to apologise, I'm confident you'll fix it moving forward.

I guess, since the app prevents me from doing any kind of sync because it seems my details to be inadequate, that I'll have to clear the app data.
Is there a way for me to back the contents up before I do that? I have a few credentials added to the password store that I need saved/backed up.

**Comment by msfjarvis** [comment]
> No need to apologise, I'm confident you'll fix it moving forward.
> 
> I guess, since the app prevents me from doing any kind of sync because it seems my details to be inadequate, that I'll have to clear the app data.
> Is there a way for me to back the contents up before I do that? I have a few credentials added to the password store that I need saved/backed up.

You shouldn't need to clear data but there's a repository export option that will copy your local git repo to a directory on your device storage. You can then pull that directory to your PC and merge the changes from there to your pass repo using `pass git pull path/to/copied/folder`.

**Comment by matrixes** [comment]
> I have confirmed that setting the Repository URI field to git@gitlab.com:<username>/<repository_slug>.git for ssh and gitlab.com/<username>/<repository_slug>.git for HTTPS lets me clone/push/pull/synchronize the repository perfectly.

I'm solely using HTTPS and the behaviour for me is, after having reset the app:

1. Tap "Clone from Server"
2. Tap "Hidden (preferred)", get settings screen
3. Copy clone repository URL from Gitlab
4. Paste into `Repository URL` in settings screen of the app

What happens here is that none of the other fields are populated by this.

If I tap "Clone!" I get a dialogue asking me "Did you forget to specify a username?"

If I then start typing a username into the Username field, the URI gets replaced with `[username]@:` forcing me to reenter the `Repository URI`.

No matter what I do, in terms of cloning and performing synchronisations after the cloning, it's the same dialogue telling me that I probably forgot something. I always succeed in making the initial clone, but after that, some or several details are probably stored in a way that make the app believe it doesn't have enough or wrong information.

Now, what I'll do is to go back to the Legacy password store app, as this one isn't all that useful to me in its current state. If there's a specific issue targeting the revamp/rework of the mechanics of the Git settings I'll gladly subscribe to it so I can test it out when there's a release pushed related to that.

**Comment by msfjarvis** [comment]
> > I have confirmed that setting the Repository URI field to [git@gitlab.com](mailto:git@gitlab.com):/<repository_slug>.git for ssh and gitlab.com//<repository_slug>.git for HTTPS lets me clone/push/pull/synchronize the repository perfectly.
> 
> I'm solely using HTTPS and the behaviour for me is, after having reset the app:
> 
> 1. Tap "Clone from Server"
> 2. Tap "Hidden (preferred)", get settings screen
> 3. Copy clone repository URL from Gitlab
> 4. Paste into `Repository URL` in settings screen of the app
> 
> What happens here is that none of the other fields are populated by this.
> 
> If I tap "Clone!" I get a dialogue asking me "Did you forget to specify a username?"
> 
> If I then start typing a username into the Username field, the URI gets replaced with `[username]@:` forcing me to reenter the `Repository URI`.
> 
> No matter what I do, in terms of cloning and performing synchronisations after the cloning, it's the same dialogue telling me that I probably forgot something. I always succeed in making the initial clone, but after that, some or several details are probably stored in a way that make the app believe it doesn't have enough or wrong information.
> 
> Now, what I'll do is to go back to the Legacy password store app, as this one isn't all that useful to me in its current state. If there's a specific issue targeting the revamp/rework of the mechanics of the Git settings I'll gladly subscribe to it so I can test it out when there's a release pushed related to that.

We haven't actually changed this part in a while so I'm not sure how the UX is so divergent from v1.3.3 :confused:. If it's any help, here's all the git settings that do the job for me

![image](https://user-images.githubusercontent.com/13348378/75410900-64f9e100-5943-11ea-97c0-7ba98558bb2f.png)

**Comment by matrixes** [comment]
>  If it's any help, here's all the git settings

It is of tremendous help, because if i pieced together the information _exactly_ the way you pictured it, it finally works for both cloning and subsequent synching! I'm very thankful for this!

Hopefully my woes can be considered when you dig into modifications of this in the future. One suggestion I can think of on the top of my head that would be more than useful is that when I enter a complete Repository URI, such as: `[https://][server.com]/[repo/path]`, the app make use of that information by populating the fields of `Protocol`, `Username`, `Server URL`, `Repo path` so the app gets the required information in the field it expects.

Another tediousness with the input form here is that it very often replaces information when typing in individual fields. I in 99% of the cases take a copy of a URI from e.g. Github or Gitlab and paste it somewhere. In this case the "Repository URI" field makes a fair bit of sense to paste it in. However, if I get a "Did you forget to enter a username?" or similar dialogue, and go to enter a username, the whole URI is replaced. At this point it's a guesswork of whether I should paste the URI again or not.

In the end, copying and pasting the URI isn't the correct way because it only works during e.g. the initial clone, I've concluded as much. But it would be _very_ helpful if it supported that in the future and I'm looking forward to future improvements!

**Comment by msfjarvis** [comment]
> > If it's any help, here's all the git settings
> 
> It is of tremendous help, because if i pieced together the information _exactly_ the way you pictured it, it finally works for both cloning and subsequent synching! I'm very thankful for this!

Glad to hear that :)

> Hopefully my woes can be considered when you dig into modifications of this in the future. One suggestion I can think of on the top of my head that would be more than useful is that when I enter a complete Repository URI, such as: `[https://][server.com]/[repo/path]`, the app make use of that information by populating the fields of `Protocol`, `Username`, `Server URL`, `Repo path` so the app gets the required information in the field it expects.
> 
> Another tediousness with the input form here is that it very often replaces information when typing in individual fields. I in 99% of the cases take a copy of a URI from e.g. Github or Gitlab and paste it somewhere. In this case the "Repository URI" field makes a fair bit of sense to paste it in. However, if I get a "Did you forget to enter a username?" or similar dialogue, and go to enter a username, the whole URI is replaced. At this point it's a guesswork of whether I should paste the URI again or not.

That happens to be a result of a two-way URI builder that tries to create a URI if the other fields are filled and also attempts to autofill username/server/path if a URI is specified. Sometimes it does a terrible job at both, and we get the class of problems you wrangled with. I'll try to revisit it for the March release and teach the algorithm some manners about HTTP URLs :)

**Comment by msfjarvis** [comment]
Thanks for your valuable insight into this whole issue @matrixes. I've just merged a revamped version of this entire space into master and I hope that it is far more friendlier to users. Please do let us know of anything else you think would improve UX here.
