### ISSUE TITLE
[BUG] Can't delete folders containing a password

### ISSUE THREAD

**Issue by TheLastProject** [android-password-store/Android-Password-Store#638]
**Describe the bug**
If a folder contains a password, trying to delete it silently fails

**To Reproduce**
1. Click the Floating Action Button
2. Click the Directory icon to create a new folder
3. Enter a name (Test) and click Create
4. Click the new folder
5. Click the Floating Action Button
6. Click the Password File icon to create a new password
7. Give it a name (Test) and enter a password (Test)
8. Go back to the main screen
9. Long-press the directory Test
10. Click the delete button
11. Click "Yes" on the Dialog "Are you sure you want to delete the password Test?"
12. Notice the directory is still there

**Expected behavior**
The directory and all passwords in it are deleted

**Screenshots**
![photo_2020-02-22_16-20-29](https://user-images.githubusercontent.com/1885159/75094868-4a181d00-558f-11ea-8681-bb54c7ce5c54.jpg)
![photo_2020-02-22_16-20-31](https://user-images.githubusercontent.com/1885159/75094867-48e6f000-558f-11ea-8f32-8366870620d4.jpg)
![photo_2020-02-22_16-20-33](https://user-images.githubusercontent.com/1885159/75094866-47b5c300-558f-11ea-9a30-79491e046442.jpg)

**Device information (please complete the following information):**
 - Device: Fairphone 3
 - OS: Stock ROM Android version 9
 - App version 1.5.0

**Additional context**
It works fine if the directory does not contain any passwords.

This seems like a fairly simple bug to tackle. If this issue can be confirmed, I am willing to take a stab at fixing this myself.

**Comment by msfjarvis** [comment]
Thanks for your report
