### ISSUE TITLE
Is it possible to use dropbox or google drive to store my gpg key and data store?

### ISSUE THREAD

**Issue by oren** [android-password-store/Android-Password-Store#643]
**Is your feature request related to a problem? Please describe.**
This is might not be a feature request but more a request to understand if the following is possible: I want to store both my gpg key and my data store on dropbox or google drive. is this option possible? If so, can I have a step by step guide for achieving it?

**Describe the solution you'd like**
If the feature exist, i would like a wiki page documenting how to use it.

**Describe alternatives you've considered**
I don't have an alternatives. I prefer to not use git to store my data.

Thanks!

**Comment by msfjarvis** [comment]
This is not possible and we currently have no plans for it either.

**Comment by oren** [comment]
Let me know if I understand my options:
1. Use my own server with git
2. Use a private or a public GitHub or gutbucket repo

Is this accurate?

**Comment by msfjarvis** [comment]
> Is this accurate?

Yep.

**Comment by jbal91** [comment]
> Let me know if I understand my options:
> 
>     1. Use my own server with git
> 
> Is this accurate?

Keep in mind "your own server with git" can just be a laptop or desktop PC with `git`, `pass`, and `ssh` installed, on the same network as your Android device.

**Comment by oren** [comment]
Oh. That's actually nice. So I can have my laptop serve as my DB! Does it mean I can use the app even when I am not at home (assuming I have the recent version of my password db)?

**Comment by msfjarvis** [comment]
> Oh. That's actually nice. So I can have my laptop serve as my DB! Does it mean I can use the app even when I am not at home (assuming I have the recent version of my password db)?

You only require network access to your git remote when you're pushing or pulling the repository. Once you have the password store on-device, no network access is required to be able to decrypt existing passwords or create new ones.

**Comment by oren** [comment]
That's perfect. I will try it.

**Comment by jbal91** [comment]
Just keep in mind that if the git repo on your laptop is a normal repo (like `pass git init` creates) as opposed to a bare repo you will only be able to pull from it, not push into it. This may or may not be congruent to your workflow. In my case, I only make changes on my desktop, so it works for me.

The username is your laptop's username, the server URL is your laptop's IP address (Android doesn't support Bonjour/Avahi/mdns, sadly, so no `.local` addresses), and the repo path is `.password-store`.

If you want to sync on the go, you can make a Tor hidden service on your laptop and use Orbot VPN mode to connect to it, but it's finicky and slow.

**Comment by oren** [comment]
I am trying to setup git on my laptop but I getting an error if I try to pull or push:

```
sudo apt-get install openssh-client openssh-server
git init --bare pass-repo
pass git init
pass git remote add origin ssh://git@localhost:/home/oren/pass-repo
pass git pull origin master

bash: /home/oren/gogs/gogs: No such file or directory
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by chschlue** [comment]
The error is apparently caused by Gogs messing with your authorized_keys.
I would suggest you only setup Gogs after you have a basic git and ssh setup up and running.
Or don't use it at all. I don't see why one would need Gogs to manage a pass repo plus it enlarges your attack surface.

**Comment by oren** [comment]
Yeah. I played with gog a few years ago. Not sure what's going on here. How do I get rid of whatever caused this error?

**Comment by chschlue** [comment]
Gogs uses "hooks" in your authorized_keys file to deal with ssh keys.
Look in `~/.ssh/authorized_keys` for lines containing something like `command="/home/oren/gogs..."`

**Comment by oren** [comment]
nice. i removed that line.

```
pass git pull origin master
oren@localhost's password:
```

What password is it asking for? I tried my password I use to login to my laptop but that didn't work. I am on ubuntu btw. I am not sure if it's relevant though.

**Comment by chschlue** [comment]
I have no idea whether Ubuntu's default sshd config allows passwords or not (apparently not, otherwise user oren's pw should be working)
You can either enable passwords in `/etc/ssh/sshd_config' or add your own pubkey from `~/.ssh/id_rsa.pub` or `~/.ssh/id_ed25519.pub` to `~/.ssh/authorized_keys` to be able to log in from localhost.

**Comment by oren** [comment]
I might typed the wrong password previously. Here is the error i see now:
```
fatal: Couldn't find remote ref master
fatal: The remote end hung up unexpectedly
```

Also, I opened /etc/ssh/sshd_config and uncommented this line:
```
PasswordAuthentication yes
```
and than restarted sshd with:
```
sudo service ssh restart
```
but I got the same error.

Just to make sure I understand what's going on here. I have 2 folders: `~/.password-store` and `~/pass-repo` and it doesn't matter where I run the pass commands, right? Also, I Assume that what I am trying to do is push the 'database' into pass-repo and than access it from the phone as well. Let me know if I got that right.

**Comment by oren** [comment]
Also, here is some more information that might help in troubleshooting:
```
pass git remote -v

origin	ssh://oren@localhost:/home/oren/pass-repo (fetch)
origin	ssh://oren@localhost:/home/oren/pass-repo (push)
```

**Comment by chschlue** [comment]
You will have to `pass git push -u origin master` your passwords before you can pull anything.
Remember, `~/pass-repo` is empty right now.
BTW, if your remote is on localhost, ssh is not necessary other than for testing your sshd setup.

**Comment by oren** [comment]
ok. I am able to push and pull on my laptop. 

Now I am not sure what steps should I take on the android app. In the settings I clicked on 'edit git server settings' and filled my git server info (my laptop) but that's all I could figure out. I see a lot of other options in the settings including 'select external repository' and 'select OpenPGP Provider'. I tried both but I am not sure how to continue. Am I suppose to copy my pgp key to my phone? If so, how do I do that?

**Comment by chschlue** [comment]
You need an OpenPGP provider (like OpenKeyChain) to supply the keys used to encrypt your passwords and an SSH key to access your git repo for syncing (or use passwords for that).
The SSH key can be generated by the app (public part has to be added to `~/.ssh/authorized_keys` on your laptop then) or imported from somewhere else.

**Comment by oren** [comment]
Thank you!

Unfortunately I need more details instructions on the tools and the process I should follow. Let me try breaking it down into small parts. I'll need step by step for each part if that's ok.

Regarding pgp keys. I already generate key for pass on my laptop. I can export it using `gpg2 --export-secret-keys > secret.gpg` but not sure if that's relevant for our discussion (:

Let's talk about OpenKeychain. I installed it on my android phone and it gives me a few options:
1. create my key
1. use secure token
1. import key from file
1. secure wifi transfer
1. skip setup
