### ISSUE TITLE
Swipe refresher spinner stays on when a remote git repo is not configured

### ISSUE THREAD

**Issue by glowinthedark** [android-password-store/Android-Password-Store#646]
**Describe the bug**
Swiping to refresh without a configured git repo or with some of the prerequisites not satisfied (i.e. missing ssh key, missing keychain approval, etc) results in the spinning animation not stopping when returning to the main activity.

**To Reproduce**
1. Reset the app data or remove the app prefs e.g. with `adb root ; adb shell rm -rf /data/data/dev.msfjarvis.aps.debug/shared_prefs`
2. Swipe down to sync the repo. The configuration dialog appears with buttons to configure the repo or 'Nah, later'
3. Click 'Nah, later' or 'On my way..'

**Expected behavior**
After returning to to password list the wait animation is gone.

**Actual behavior**
After returning to to password list the wait animation is still there.

> Notes: about to push a fix for this.

**Comment by msfjarvis** [comment]
Fixed with #647
