### ISSUE TITLE
Architectural changes required for long-term maintenance

### ISSUE THREAD

**Issue by msfjarvis** [android-password-store/Android-Password-Store#680]
This app and its codebase are very old, dating back to 2014 (before yours truly even had a phone, to put in perspective). As such, a lot of design choices made at the time are now limiting growth and development of the project and making things difficult that shouldn't be.

This issue is going to serve as a tracking issue for all the various known changes required to make the app more maintainable, and will be updated as and when said changes are made or new requirements arise from the depths of tech debt.

- [x] Split GitActivity into separate parts based on each operation it performs.
- [x] Split PgpActivity similarly.
- [x] Evaluate the story around migrating away from the sluggish Jsch to the more maintained [SSHJ](https://github.com/hierynomus/sshj).
- [x] Prepare for a no-git mode to facilitate external storage users.
- [ ] Abstract out file handling into a generic interface so we can use SAF to deal with external storage changes in Android.
- [x] Get rid of Apache Commons code. We do not need to carry this dependency, Kotlin and Android provide us everything that we want.

While @Skrilltrax continues working on [v2](https://github.com/android-password-store/Android-Password-Store/tree/v2), these changes will certainly help extend the timeline for the eventual switch to it, allowing both sets of maintainers to continue working at a comfortable pace.

**Comment by msfjarvis** [comment]
GitActivity refactor is being done in #685

**Comment by msfjarvis** [comment]
With the merge of #685 the first task is now complete 🚀

**Comment by msfjarvis** [comment]
#776 targets task 2 and hopefully unblocks further improvements :)

**Comment by Dioxo** [comment]
>Get rid of Apache Commons code. We do not need to carry this dependency, Kotlin and Android provide us everything that we want.

Are you talking about Apache commons IO or Codec? Or both? @msfjarvis

**Comment by msfjarvis** [comment]
> > Get rid of Apache Commons code. We do not need to carry this dependency, Kotlin and Android provide us everything that we want.
> 
> Are you talking about Apache commons IO or Codec? Or both? @msfjarvis

IO at the bare minimum, would be nice to not require Codec either.

**Comment by Dioxo** [comment]
I'll try to help with IO, I'll send a PR in next days with some progress in it. :)

**Comment by Dioxo** [comment]
In order to update this issue, with the merge of #840 , the last task is also completed ;)

**Comment by FabianHenneke** [comment]
> In order to update this issue, with the merge of #840 , the last task is also completed ;)

I updated the list, thanks for the contribution!

**Comment by msfjarvis** [comment]
With #776 landing we're now down to our last task :tada:

I personally feel that we should completely disable Git when the user enables the external repository option since there is no good reason to be doing that other than using a third-party sync solution like a WebDAV client or Syncthing. This would solve #845 as well as greatly simplify the work needed for us to transition to SAF for external repository handling. We can't go forever with the `android:requestLegacyExternalStorage` attribute.

**Comment by msfjarvis** [comment]
The main tasks here have been resolved and we might not end up needing SAF so it's about time this is closed.
