### ISSUE TITLE
[FEATURE] Should have manual option for clearing "Key" Password

### ISSUE THREAD

**Issue by joneldominic** [android-password-store/Android-Password-Store#696]
**Is your feature request related to a problem? Please describe.**
The main reason I use this kind of application is to improve my privacy and security for my accounts. But, sometimes it frustrates me when I open the app then choose an account and all in a sudden, it will show the password and other details automatically without asking my password for my **KEY** _(GPG)_. I know there is a "**Remember**" option when I enter my KEY password but I think the option is not enough. Let's, for example, I choose "for one hour" (knowing it has the shortest duration) but the problem is a lot of things may happen for an hour (my phone may be stolen for example). Though there is also an option called "until screen off" but the problem with this is that it's not consistent (I tested the behavior a lot of times), sometimes it asks for the password and sometimes doesn't and just directly display all of my accounts sensitive information.

**Describe the solution you'd like**
What I want is there should be an option for the user to have the control over clearing the **Key** password or a _remember_ option of let's say "don't remember" / "one time only".

**Describe alternatives you've considered**
As for now, my only solution is to settle with "until screen of" option (even if it's not consistent) and to manually remove "Settings/Crypto/Select OpenPGP Provider" (It doesn't solve the problem though, it just buy some time and gives intimidating settings if an account is clicked - assuming and hoping just in case if my phone is lost/stolen/falls into the hands of others)

**Additional context**
PS. You can ask me follow-up questions in case you don't get my point.

**Comment by msfjarvis** [comment]
It's not ours to control. OpenKeychain provides everything related to GPG. We send it a stream of encrypted data, tell them what key we'd like to decrypt with, and get back an error or a stream of decrypted data. Their issue tracker can be found [here](https://github.com/open-keychain/open-keychain), which would be the right place for this issue.
