### ISSUE TITLE
[BUG] using a local non-hidden storage on the sd card fails with permission denied

### ISSUE THREAD

**Issue by savar** [android-password-store/Android-Password-Store#697]
**Describe the bug**
On a fresh installation via F-Droid (Password Store 1.3.3) I can use my "imported" (unzipped) local repository to view existing passwords. When trying to add/edit/delete any of them it simply does nothing or throws an error. `logcat` shows me that it fails while trying to write.. the code giving this error is

```java
            if (file.canWrite() == false) {
                throw new IOException("File '" + file + "' cannot be written to");
            }
```
within FileUtils.java "openOutputStream()".

I tried to use the "master" branch and tried to debug this. The fact is, I was not able to write.
My "work around" was: I replaced all `Manifest.permission.READ_EXTERNAL_STORAGE` in
app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt to `Manifest.permission.WRITE_EXTERNAL_STORAGE` as WRITE includes READ and it seems to be required to ask for that permission even if the Manifest actually includes that detail.

On my Android 9 maybe even though I gave "access" to the storage it seems to have both permissions separately managed under the hood. I don't know enough of the permission model of Android and so I also didn't check the code closely if it should only ask in specific situations for WRITE and others just for READ access but I think that is easy to be fixed by someone knowing the code better.

I removed all the boilerplate as I hope it was already clear enough what the issue is. In case you really need more information, I can give all of them but I guess the issue and the resolution is simple/clear enough?!

**Comment by msfjarvis** [comment]
Changing READ_EXTERNAL_STORAGE to WRITE_EXTERNAL_STORAGE does seem to do the trick, and is perfectly reasonable as well. I'll start up a PR. Thanks for your in-depth research into this!

**Comment by savar** [comment]
Thank you :) .. shall I close the issue or wait for your pull request which could close it as well?

**Comment by msfjarvis** [comment]
> Thank you :) .. shall I close the issue or wait for your pull request which could close it as well?

The PR will close it. I got sidetracked while writing up the PR body, will put it up now.
