### ISSUE TITLE
[BUG] Oreo autocomplete does not find entry

### ISSUE THREAD

**Issue by jvanbruegge** [android-password-store/Android-Password-Store#705]
From #653, cc @msfjarvis 
I just tried the snapshot and the search does not work apparently for the naming scheme path/to/domain.tld.gpg. For example when trying to log into paypal, the search correctly contains paypal.com but it does not find Banking/paypal.com.gpg. Clearing the search and selecting the entry from the list however correctly fills username and password and if i save the association I get it suggested the next time above the option to search

1. Install current snapshot, i used [this link](https://dl.msfjarvis.dev/?dir=APS)
2. Have your passwords organized as multiline files with `path/to/domain.tld.gpg` and the username as second line like `login: <username>`
3. go to a website, I used https://github.com and https://paypal.com in Firefox mobile for android
4. tap into the username or password field to make the oreo autofill ui appear
5. Select "search in store"
6. See search ui with e.g. domain "github.com" pre filled in the search bar
7. See "no results"

**Expected behavior**
A single entry for the site "github.com"

**Workaround**
Clearing the search show all entries as expected, but even clearing and retyping the exact same search string (github.com) leads to the expected one result

**Device information (please complete the following information):**
 - Device: OnePlus 3
 - OS: LineageOS 15.1
 - App version: 1.7-snapshot

**Comment by msfjarvis** [comment]
Thanks @jvanbruegge! I believe that's enough information for Fabian, but he might have additional questions or require you to assist with testing when he triages this.

**Comment by jvanbruegge** [comment]
I assume this is only a small bug because retyping the exact same search string makes it work as expected

**Comment by jvanbruegge** [comment]
(Accidental button press)

**Comment by FabianHenneke** [comment]
Thanks for the detailed report!

I am planning to address this in three steps:

- Add a file organization setting for a directory structure like "work/Banking/paypal.com.gpg". Do you usually store usernames in the encrypted extra contents?
- Make the phishing-resistant StrictDomain search independent of the file organization setting by letting it match any path component. This should not pose a security risk and make search "just work" out of the box.
- Add a switch to the Autofill search popup that allows toggling StrictDomain/fuzz search mode. This addresses the confusion associated with different behavior between the first and all further searches.

What do you think? @msfjarvis @jvanbruegge

**Comment by jvanbruegge** [comment]
> Do you usually store usernames in the encrypted extra contents?

Yes, a typical password file looks like this for me:
```
<password>
login: <username>
<sometimes extra notes>
```
> Make the phishing-resistant StrictDomain search independent of the file organization

What is the behavior of StrictDomain now?

> Add a switch to the Autofill search popup that allows toggling StrictDomain/fuzz search mode

Yes this would make it visible

**Comment by FabianHenneke** [comment]
> What is the behavior of StrictDomain now?

It matches only the specific path component that fits the file organization layout chosen in the settings. Since your particular layout hasn't been implemented yet, the search does not find anything. I plan to address this by both adding explicit support for your layout and making the StrictDomain search slightly less strict.

**Comment by jvanbruegge** [comment]
I see, yeah that would work

**Comment by hargut** [comment]
@FabianHenneke Thank you for your work on Android Autofill.
