### ISSUE TITLE
[BUG] Cannot create new password or folder

### ISSUE THREAD

**Issue by dgmulf** [android-password-store/Android-Password-Store#710]
**Describe the bug**
Attempting to create a new password or folder does nothing.

**Device information (please complete the following information):**
 - Device: Google Pixel XL
 - OS: Android 10
 - App version 1.6.0

**Additional context**
I am using an external repository synced between my devices using Syncthing. I'm not using git functionality. Password decryption works as expected.

**Comment by msfjarvis** [comment]
This is fixed in master. You can install the snapshot build linked in the README to get the update before this month's scheduled release.
