### ISSUE TITLE
Crash on Startup when using SD-Card Storage

### ISSUE THREAD

**Issue by Jaulers** [android-password-store/Android-Password-Store#711]
When trying to start the app using sd-card password storage, it crashes.

**To Reproduce**
1. Freshly install app
2. Select 'Use local Directory'
3. Select 'SD-Card' and create a new directory for the password store
4. When starting the app for the first time after that, it asks for permission to access the sd-card
5. After that it crashes and also on each following startup.

**Expected behavior**
No crash.

**Device information:**
 - Device: Fairphone 2
 - OS: Android 10 (LineageOS 17.1)
 - App version: 1.3.3

**Logcat**
[Logcat](https://github.com/android-password-store/Android-Password-Store/files/4485749/pwdstore_logcat.txt) produced when starting the app.
.

**Comment by msfjarvis** [comment]
1.3.3 is far too outdated and the issue has since been fixed on master. If you don't wish to upgrade from a non F-Droid source from the README, you'll have to wait till the end of this month for the new F-Droid listing to hopefully go up.
