### ISSUE TITLE
[TRANSIFEX] language not active for translation

### ISSUE THREAD

**Issue by xmgz** [android-password-store/Android-Password-Store#715]
Hi,
I have not found any way to contact APS on Trasifex so I open this issue here

**Description**
- I requested new language team creation (gl): Done.
- It's been acepted and created by APS: Done.
- I've joined that new team (gl): Done.

and then...

- I can not access to translation interface on that language so I can not translate APS.

I suspect that brazilian, slovak and serbian teams are with the same problem

**Expected behavior**
been able to translate APS

**Screenshots**
![screeshot](https://i.imgur.com/C4b7OJi.png)

**Device information (please complete the following information):**
- transifex web interface

**Additional context**
I have no problem to translate on my other transifex teams. Aditionally I've submited a join request to another APS team just to test if it is something related to the whole project or just some languages (I'm waiting the aproval at the time of writing).

I'm open at making any test if needed

Please check APS transifex configuration if possible, **thank you**

**Comment by msfjarvis** [comment]
@xmgz Can you check now? It seems Transifex hadn't actually processed your join request...

**Comment by xmgz** [comment]
Yes, it's accesible now. Thank you.

[solved]
