### ISSUE TITLE
[BUG] Error when adding local repository to the external MicroSD card.

### ISSUE THREAD

**Issue by flintstoney** [android-password-store/Android-Password-Store#736]
**Describe the bug**
I have 'Password store' + 'OpenKeychain' and the pass repository on Gitlab.com. 
When I check in Settings an external repository (My Micro SD card) And try to synchronize the repository I see an error. I tried the authentication method via HTTPS and SSH, and both give an error. I noticed that in Totalcmd (for Android) the path to my External storage is /storage/0123-4567/* and in the settings of 'Password store' I see the path /storage/emulatet/0/* And it is not my External storage. When I don't check the internal storage path authentication goes well with HTTPS and with SSH.

**To Reproduce**
1. Open 'Password store'
2. Go to 'Settings'
3. Scroll down to 'External repository' and check it
4. Synchronize the repository
5. See error:
An error occurred while performing the operation Git
Error occurred during the sync
operation,
Please check the FAQ for possible
reasons why this error might
occur.Message from jgit:
Attempt to read from field ‘int
org.eclipse.jgit.lib.AnyObjectld.w1' on
a null object reference
Caused by:
null 

**Expected behavior**
I expect a successful synchronization with my repository server on Gitlab. 

**Screenshots**
https://i.imgur.com/TpS9ObW.png

**Device information (please complete the following information):**
 - Device: Lenovo Vibe P1a42
 - Device CPU: CPU: Qualcomm Snapdragon 615 (8 cores x 1.5GGHz)
 - Device RAM: 3Gb
 - Device internal storage: 16Gb (1.7Gb Aviabile)
 - Device external storage MicroSD: 57.95Gb (42.7Gb Aviabile)
 - OS: Android 6.0.1 
 - App version: 1.7.0

**Additional context**
Maybe the problem is that 'Password store' don't make the path to my external storage correctly. When I don't check the internal storage path authentication goes well with HTTPS and with SSH.

**Comment by msfjarvis** [comment]
Hey, can you try the [v1.7.1](https://github.com/android-password-store/Android-Password-Store/releases/tag/v1.7.1) APK? We believe the problem is fixed there.

**Comment by flintstoney** [comment]
I tried the v1.7.1 and the problem is the same.

**Comment by msfjarvis** [comment]
> > Hey, can you try the [v1.7.1](https://github.com/android-password-store/Android-Password-Store/releases/tag/v1.7.1) APK? We believe the problem is fixed there.
> 
> I tried the v1.7.1 and the problem is the same.

Does wiping app data and then going through the initial setup flow also not work?

**Comment by msfjarvis** [comment]
@FabianHenneke should we be checking for storage permission before each operation? Seems a bit excessive but might just be what is needed here...

**Comment by msfjarvis** [comment]
> > @FabianHenneke should we be checking for storage permission before each operation? Seems a bit excessive but might just be what is needed here...
> 
> It seems reasonable to do so, even if it means a bit more work.
> 
> Just in case the root cause should turn out to be a different one: This JGit error is exactly the one I got once when I tried syncing the repository before cloning it.

So maybe this is a problem with how we track repository initialization state... I've always felt the logic in PasswordRepository was a bit ambiguous, seems like a good time to rework that.

**Comment by flintstoney** [comment]
> > @FabianHenneke should we be checking for storage permission before each operation? Seems a bit excessive but might just be what is needed here...
> 
> It seems reasonable to do so, even if it means a bit more work.
> 
> Just in case the root cause should turn out to be a different one: This JGit error is exactly the one I got once when I tried syncing the repository before cloning it.

I don't think it's about permissions to use MicroSD card. Because I can select it and I see all the folders and files in them when I look select the path. But when I select the desired path in /storege/0123-4567/ (MicroSD) it's creating a similar one in /storage/emulated/0/ (Internal storage). For example I created a directory named MyPasswords on MicroSD card an I found a copy of this directory in internal storage.

**Comment by msfjarvis** [comment]
Yeah it wasn't storage permissions. I did some dumpster diving into JGit repositories and found a couple tidbits that seemed to do the trick. The fixes are in the [bug/uninitialized-repository](https://github.com/android-password-store/Android-Password-Store/tree/bug/uninitialized-repository) branch, I'll start up a PR shortly.

**Comment by itsfarseen** [comment]
I was facing this problem in v1.11.3.

I selected SDCard/Syncthing/password-store folder using the folder picker in onboarding screen.
It still showed the onboarding screen after that. So I checked settings.
It showed `/storage/emulated/0/Syncthing/password-store`. 
But `/storage/emulated/0` is Internal Storage, not SD Card.

I worked around this by using Shared Preferences Editor to manually edit `git_external_repo` and change `/storage/emulated/0/Syncthing/password-store` to `/path/to/sdcard/Syncthing/password-store`.

PS: The sdcard is usually not mounted as read-write in most recent ROMs. 
Since I face "unable to write to sdcard" issue in many apps, I was already using a Magisk module to mount sdcard as read-write.

PPS: You have to force stop Password Store app before editing SharedPreferences for the change to be picked up.
