### ISSUE TITLE
[BUG] Decryption time is too long (up to 2min)

### ISSUE THREAD

**Issue by flintstoney** [android-password-store/Android-Password-Store#737]
**Describe the bug**
I have 'Password store' + 'OpenKeychain' and the pass repository on Gitlab.com. I am using a GPG.sec.asc key. The problem is that when I try to decrypt in 'Password store' a password it the decryption is taking too long - about 1min 30sec - up to 2min. And I need to keep my phone screen awake. If it is going to sleep the decryption process is aborted and I need to make it from beginning. After decrypting I see that not only the password I specified is decrypted but also all other passwords in my repository are decrypted too. I believe that decryption takes that long, because it is decrypting all passwords and not only the one I specified. It is kind of unacceptable when you need to access somewhere fast.

**To Reproduce**
1. Open 'Password store'
2. Select the desired Password (tape on it)
3. introducing the password for my gpg key (rsa4096).
4. Waiting about 1min 30 sec - up to 2 min and keep my screen to not go to sleep.
5. I see that all passwords in my repository are decrypted.

**Expected behavior**
I expect a fast decryption of one specified password and not for all passwords. At least I need to choose an option in settings, to decrypt the one selected password (fast) or to decrypt all passwords (long).

**Device information (please complete the following information):**
 - Device: Lenovo Vibe P1a42
 - Device CPU: CPU: Qualcomm Snapdragon 615 (8 cores x 1.5GGHz)
 - Device RAM: 3Gb
 - Device internal storage: 16Gb (1.7Gb Aviabile)
 - Device external storage MicroSD: 57.95Gb (42.7Gb Aviabile)
 - OS: Android 6.0.1 
 - App version: 1.7.0

**Additional context**
This is not a critical bug, but it causes great inconvenience and I also think that for security reasons it is not necessary to decrypt all passwords.

**Comment by msfjarvis** [comment]
I am pretty confident we _never_ decrypt all passwords. How are you verifying that all passwords are being decrypted?

**Comment by flintstoney** [comment]
> I am pretty confident we _never_ decrypt all passwords. How are you verifying that all passwords are being decrypted?

I may be wrong about decrypting all passwords. I made an assumption because of a too long decryption. After typing my gpg key password I see that it is opened until I type on it. Maybe this is why when I tape on other password it is opening decrypted. But whatever, when I want to decrypt a password it takes too long time. 1min 30sec and more.

**Comment by msfjarvis** [comment]
> > I am pretty confident we _never_ decrypt all passwords. How are you verifying that all passwords are being decrypted?
> 
> I may be wrong about decrypting all passwords. I made an assumption because of a too long decryption. After typing my gpg key password I see that it is opened until I type on it. Maybe this is why when I tape on other password it is opening decrypted. But whatever, when I want to decrypt a password it takes too long time. 1min 30sec and more.

This could very easily be an `[Open Keychain](https://github.com/open-keychain/open-keychain)` bug. Can you take an individual password file from your password store and try to decrypt it directly with Open Keychain?

**Comment by flintstoney** [comment]
> > > I am pretty confident we _never_ decrypt all passwords. How are you verifying that all passwords are being decrypted?
> > 
> > 
> > I may be wrong about decrypting all passwords. I made an assumption because of a too long decryption. After typing my gpg key password I see that it is opened until I type on it. Maybe this is why when I tape on other password it is opening decrypted. But whatever, when I want to decrypt a password it takes too long time. 1min 30sec and more.
> 
> This could very easily be an `[Open Keychain](https://github.com/open-keychain/open-keychain)` bug. Can you take an individual password file from your password store and try to decrypt it directly with Open Keychain?

where is the passwords local repository directory?

**Comment by msfjarvis** [comment]
> > > > I am pretty confident we _never_ decrypt all passwords. How are you verifying that all passwords are being decrypted?
> > > 
> > > 
> > > I may be wrong about decrypting all passwords. I made an assumption because of a too long decryption. After typing my gpg key password I see that it is opened until I type on it. Maybe this is why when I tape on other password it is opening decrypted. But whatever, when I want to decrypt a password it takes too long time. 1min 30sec and more.
> > 
> > 
> > This could very easily be an `[Open Keychain](https://github.com/open-keychain/open-keychain)` bug. Can you take an individual password file from your password store and try to decrypt it directly with Open Keychain?
> 
> where is the passwords local repository directory?

The hidden directory is inaccessible to other apps. You can use the export option  in settings to place a copy to your internal storage or SD card.

**Comment by flintstoney** [comment]
> > > I am pretty confident we _never_ decrypt all passwords. How are you verifying that all passwords are being decrypted?
> > 
> > 
> > I may be wrong about decrypting all passwords. I made an assumption because of a too long decryption. After typing my gpg key password I see that it is opened until I type on it. Maybe this is why when I tape on other password it is opening decrypted. But whatever, when I want to decrypt a password it takes too long time. 1min 30sec and more.
> 
> This could very easily be an `[Open Keychain](https://github.com/open-keychain/open-keychain)` bug. Can you take an individual password file from your password store and try to decrypt it directly with Open Keychain?

Seems like you was right. I tried to decrypt a password directly and it took the same time - about 1min 30 sec. Seems like it's an OpenKeychain  issue. I will report a bug to them. Maybe you can recommend me other decrypt application that will work with 'Password store'? And what should I do with this bug? Should I delete it or mar it solved?

**Comment by msfjarvis** [comment]
> > > > I am pretty confident we _never_ decrypt all passwords. How are you verifying that all passwords are being decrypted?
> > > 
> > > 
> > > I may be wrong about decrypting all passwords. I made an assumption because of a too long decryption. After typing my gpg key password I see that it is opened until I type on it. Maybe this is why when I tape on other password it is opening decrypted. But whatever, when I want to decrypt a password it takes too long time. 1min 30sec and more.
> > 
> > This could very easily be an `[Open Keychain](https://github.com/open-keychain/open-keychain)` bug. Can you take an individual password file from your password store and try to decrypt it directly with Open Keychain?
> 
> Seems like you was right. I tried to decrypt a password directly and it took the same time - about 1min 30 sec. Seems like it's an OpenKeychain  issue. I will report a bug to them. Maybe you can recommend me other decrypt application that will work with 'Password store'? And what should I do with this bug? Should I delete it or mar it solved?

Unfortunately OpenKeychain is the only supported tool. You can leave this issue open and I'll mark it as blocked so we know that this is out of control at the moment.

**Comment by flintstoney** [comment]
Thank you!

**Comment by FabianHenneke** [comment]
This has been reported upstream: https://github.com/open-keychain/open-keychain/issues/2546

**Comment by msfjarvis** [comment]
OpenKeychain maintainer @Valodim reached out to me in January of this year about a potential restructuring of how apps integrate with OpenKeychain but I haven't heard back from them since so I doubt the project is actually moving along anymore :/

**Comment by msfjarvis** [comment]
There's been no movement on this from OpenKeychain so I'll close this here for now.
