### ISSUE TITLE
[BUG] cannot search in root folder

### ISSUE THREAD

**Issue by merrickluo** [android-password-store/Android-Password-Store#740]
**Describe the bug**
I have two folders in my password store root, the search won't work when I'm at root, only works if I go into one of them. 

**To Reproduce**
1. Go to home page
2. Click on search
3. type anything

**Expected behavior**
display search results from both folders

**Screenshots**
![image](https://user-images.githubusercontent.com/1495875/80170011-8f9da880-8619-11ea-91b8-e886d91946c1.png)
![image](https://user-images.githubusercontent.com/1495875/80170024-988e7a00-8619-11ea-9395-d1cd36bf0261.png)
![image](https://user-images.githubusercontent.com/1495875/80170150-e4412380-8619-11ea-82b7-099bad1ddc58.png)

**Device information (please complete the following information):**
 - Device: Google Pixel 3
 - OS: stock ROM Android version 10.0
 - App version: 1.7.1

**Additional context**
The Recursive filtering is checked in Settings.

**Comment by msfjarvis** [comment]
I can't seem to reproduce this, searching for `github.com` showed results from both my top-level folders.
![screenshot-20200424-083523](https://user-images.githubusercontent.com/13348378/80171121-2dd44300-8607-11ea-9554-a6be66720831.png)

**Comment by merrickluo** [comment]
I tried force stop reopen and even reinstall the app, but it's still not working, I'm not sure if it's related, I'm not syncing the files with git but using an external directory syncing with syncthing. And I checked the storage permission is granted. maybe i'll try to build a debug version to see some logs.

**Comment by msfjarvis** [comment]
I've assigned Fabian, he wrote the code for this and might be able to tell what edge cases could trigger it.

**Comment by FabianHenneke** [comment]
I am also unable to reproduce this and don't really know what could cause an issue like this except for permission/file system shenanigans. I would greatly appreciate if you could try a debug version and check the log for any errors.

**Comment by msfjarvis** [comment]
@merrickluo can you see if #743 matches your problem scenario?

**Comment by merrickluo** [comment]
> @merrickluo can you see if #743 matches your problem scenario?

Yes... It indeed starts with a dot.
