### ISSUE TITLE
How to confirm a key in OpenKeyChain in order to use in APW

### ISSUE THREAD

**Issue by JJeancarlocc** [android-password-store/Android-Password-Store#742]
Hello,

So this I want to accomplish:

1. I generated a gpg key in Ubuntu and then set up my password store in a local folder.
2. I uploaded my password store to cloud repo and then successfully synchronyze with APW
3. I transfered my gpg key to my phone in order to activate it with OpenKeyChain. This is the part I'm stucked. I tried to somehow put my passphrase to my gpg but i'm not able to do it in OpenKeyChain. And when I try do decrypt a password in APW it pops up an error "This key is not available. To used it you have to import your own".

Any ideas?

Regards,
Jeancarlo C.

**Comment by msfjarvis** [comment]
Hey Jeancarlo. Once you transfer your GPG key's **private** part to your phone, you need to start OpenKeychain, click on the FAB (round button with a + on it), then select "Import from file". A blank window opens with a folder icon at the top right, select that icon, and then navigate to where you copied the key previously. OpenKeychain will detect it and then give you some information about the key, and an "Import" button. Click that, then you can proceed to use the key in Password Store.

**Comment by JJeancarlocc** [comment]
There may be something obvious that I'm missing but I'm unable to find that "import" button after doing "Import from file" step.

Sorry for bad quality:
![OpenKeyChain](https://user-images.githubusercontent.com/23285173/80234989-a72b6000-861e-11ea-8f3b-ea1a6a311b2d.gif)

**Comment by msfjarvis** [comment]
Your key is already imported, there's a warning but I don't speak your language so I cannot tell you what it is and how to fix it.

**Comment by JJeancarlocc** [comment]
My bad, It says "Not confirmed: Scan QR code in order to confirm key!"
Do you know what this could be?

**Comment by msfjarvis** [comment]
> My bad, It says "Not confirmed: Scan QR code in order to confirm key!"
> Do you know what this could be?

I have never seen it before. I'd recommend deleting the existing key then reimporting it the way I suggested since that's what works for me.

**Comment by JJeancarlocc** [comment]
Alright so I figured out. I've been importing public keys and private keys as ASC files though OpenKeyChain recognizes that as someone's else key. When I imported as '.key' file I was able to make it work. Thanks for all, closing this thread
