### ISSUE TITLE
[BUG] Search was broken in recent release

### ISSUE THREAD

**Issue by skrat** [android-password-store/Android-Password-Store#750]
**Describe the bug**
Typing in the search field hides the list hides the list, presumably the search returns zero results. It used to be slow, but now it's broken altogether. I have some couple of hundred entries.

**To Reproduce**
1. Go to main activity
2. Click on search field
3. Type something that should return some results

**Expected behavior**
Results

**Screenshots**
https://www.youtube.com/watch?v=ruCmBuznbfI

**Device information (please complete the following information):**
 - Device: One+ 5
 - OS: stock ROM, android 9, all updates
 - App version 1.7.1

**Additional context**
I use no git or ssh sync, it's a local store that I sync with Syncthing. OpenKeychain PGP provider.

**Comment by msfjarvis** [comment]
If your password directory fits the bill for #743 then please update to the snapshot build from [here](https://dl.msfjarvis.dev/APS/) to get the fix early.

**Comment by msfjarvis** [comment]
Oh wait how's the snapshot build gone o_O

I'll get that sorted in a minute...

**Comment by msfjarvis** [comment]
Should be all good now! Sorry for that blip.

**Comment by skrat** [comment]
@msfjarvis yes it does fit the #743 description , thanks I'll wait for the release in play-store any idea when that could happen?

**Comment by msfjarvis** [comment]
This is the 3rd issue/PR for this so I think I'll push a patch release right about now...

**Comment by msfjarvis** [comment]
I've pushed the v1.7.2 release out to Play Store and to GitHub.
