### ISSUE TITLE
[BUG] Have to manually start OpenKeychain to get the password

### ISSUE THREAD

**Issue by skrat** [android-password-store/Android-Password-Store#751]
**Describe the bug**
$subj

**Screenshots**
https://www.youtube.com/watch?v=LtSTQW96m_c

**Device information (please complete the following information):**
 - Device: One+ 5
 - OS: stock ROM Android version 9.0
 - App version 1.7.1

`Failed to get last changed date` that's the error that I'm seeing and that you can't see in the video, in the 1st attempt.

**Comment by msfjarvis** [comment]
The `Failed to get last changed date` part is just an internal error that we expose to users unnecessarily. I'm gonna get rid of that.

About needing to start OpenKeychain manually, I believe the problem here is OOS killing the OpenKeychain service causing a connection failure. The advice here should help: https://dontkillmyapp.com/oneplus

**Comment by assasinfil** [comment]
I found the bug in OpenKeychain, it is necessary to give it permission to create windows on top of others.

**Comment by msfjarvis** [comment]
Other OnePlus 5 users I am in contact with have failed to reproduce this problem after following the recommendations on dontkillmyapp.com so I am closing this unless you have any further input that could point to an actual bug.

**Comment by skrat** [comment]
Yeah excluding it from battery optimization solved the issue, but I'm not sure this is way to go. This is recommended fix for way too many things. Isn't there a way for you to explicitly invoke the app even if it's closed? If it's already selected in the options as key provider, then why not opening it explicitly instead of relying on it to be running all the time. Excuse my limited understanding of Android tho.

**Comment by msfjarvis** [comment]
> Yeah excluding it from battery optimization solved the issue, but I'm not sure this is way to go. This is recommended fix for way too many things. Isn't there a way for you to explicitly invoke the app even if it's closed? If it's already selected in the options as key provider, then why not opening it explicitly instead of relying on it to be running all the time. Excuse my limited understanding of Android tho.

It's not as straightforward as just forcefully asking for an app to start. OnePlus makes unwarranted changes to the framework like all other Chinese OEMs and break apps in this fashion. This is not a problem on stock Android which means that our part of this is not problematic.
