### ISSUE TITLE
[FEATURE] Make the name of the field used for username from encrypted extra content configurable

### ISSUE THREAD

**Issue by IvanMalison** [android-password-store/Android-Password-Store#761]
The new autofill system seems to assume that directories/contaning files are to be used as the usernames for passwords, but I actually use a field within the file. Is this system of organizing passwords supported?

**Comment by msfjarvis** [comment]
#707 should have resolved that since #705 seems to be the same issue as this. Use the first option for Password file organization, that should do the job.

**Comment by IvanMalison** [comment]
Ah I see. I think #705 is related, but I use a different field name for to set the username, so I'll make this issue about making the field name used configurable.

**Comment by msfjarvis** [comment]
> Ah I see. I think #705 is related, but I use a different field name for to set the username, so I'll make this issue about making the field name used configurable.

That's very unlikely to happen. The best I can do is adding your field name to the list of fields we look up. Will create a PR for this after I finish with the other bug I'm working on.

**Comment by IvanMalison** [comment]
> That's very unlikely to happen.

Why? Seems like it should be pretty easy to do.

**Comment by msfjarvis** [comment]
> > That's very unlikely to happen.
> 
> Why? Seems like it should be pretty easy to do.

I'm not interested in adding user-facing settings for cases that don't absolutely require them. This is something that can reasonably be resolved for the majority without exposing another knob for users to fiddle with, so that's what we will do.

**Comment by msfjarvis** [comment]
[These](https://github.com/android-password-store/Android-Password-Store/blob/f99a14d95b7f9df482585f043ce1263662e66132/app/src/main/java/com/zeapo/pwdstore/PasswordEntry.kt#L166) are the fields we currently support for usernames as they match what we've seen in the wild. What field name are you using?

**Comment by IvanMalison** [comment]
> I'm not interested in adding user-facing settings for cases that don't absolutely require them.

Can you motivate this? What's the harm? I'm pretty sure that most people that use pass possess a level of technological literacy that should make allowing this sort of thing harmless.

> These are the fields we currently support for usernames as they match what we've seen in the wild. What field name are you using?

I use "user" which is the default that is used with rofi-pass: https://github.com/carnager/rofi-pass

Does it really make sense to have to make a code change to support every new field that someone might use for this?

What will the code do in the presence of multiple such entries? Are alternative capitalizations handled?

The official website gives an example where with a capitalized "username" field (https://www.passwordstore.org/).

What about:

- USERNAME
- account
- email
- handle
- name
- id
- identity

**Comment by msfjarvis** [comment]
> > I'm not interested in adding user-facing settings for cases that don't absolutely require them.
> 
> Can you motivate this? What's the harm? I'm pretty sure that most people that use pass possess a level of technological literacy that should make allowing this sort of thing harmless.

There's more aspects to consider here than technical literacy (which by itself is not true in all cases, as many people have requested the barrier of entry be lowered). Every new settings option creates more clutter and devolves the experience for all users. My comfort with the CLI does not imply I am impervious to bad UI.

> > These are the fields we currently support for usernames as they match what we've seen in the wild. What field name are you using?
> 
> I use "user" which is the default that is used with rofi-pass: [carnager/rofi-pass](https://github.com/carnager/rofi-pass)
> 
> Does it really make sense to have to make a code change to support every new field that someone might use for this?

Yes, because there's a relatively small set of label names that I consider to be prevalent and "correct" for the purpose. This list is not high maintenance after the first few expansions.

> What will the code do in the presence of multiple such entries? Are alternative capitalizations handled?

The app will traverse the list from first to last and will select whatever matches first as the username. Adding the settings preference to bandaid this particular case is unnecessary baby-proofing in my opinion, and the user should resolve it on their own end. Capitalizations are handled as the app ignores case while matching.

> The official website gives an example where with a capitalized "username" field ([passwordstore.org](https://www.passwordstore.org/)).
> 
> What about:
> 
> * USERNAME
> * account
> * email
> * handle
> * name
> * id
> * identity

I'll add these.

**Comment by colonelpanic8** [comment]
I'm not sure what changed, but this has been broken again for me for the last few releases.

It may also be related to the way fetching the default is handled, but I just get the text of the name of entry in the password store as the username.

**Comment by msfjarvis** [comment]
> I'm not sure what changed, but this has been broken again for me for the last few releases.
> 
> It may also be related to the way fetching the default is handled, but I just get the text of the name of entry in the password store as the username.

Please file a new issue.
