### ISSUE TITLE
[BUG] "Display over other apps" settings panel keeps popping up.

### ISSUE THREAD

**Issue by kevincox** [android-password-store/Android-Password-Store#767]
**Describe the bug**

**To Reproduce**
1. Focus on a password dialog
2. Settings panel opens

**Expected behavior**
I stay in the app and the popup for filling the password works.

**Device information (please complete the following information):**
 - Device: Google Pixel 1
 - OS: stock ROM Android 10 QPA.191005.007.A3
 - App version: 1.3.2

**Additional context**

It seems to happen more often on some apps then others. I have even been in cases where hitting back to close the settings panel goes back to the app then immediately back to the settings panel. The end result is that you just mash back until it stops.

**Comment by msfjarvis** [comment]
1.3.2 is extremely outdated and unsupported. Please check the README page for how to obtain a supported version. The bug in question is from the old Autofill implementation that has been replaced with a proper and more secure one.

**Comment by kevincox** [comment]
Wow, I didn't realize that the app had been renamed. Do you have any ability to replace the old app to redirect to the new one? Or at least remove it from the play store?

**Comment by msfjarvis** [comment]
> Wow, I didn't realize that the app had been renamed. Do you have any ability to replace the old app to redirect to the new one? Or at least remove it from the play store?

The old app has been unpublished and a note was added to the description pointing to the new version. That's the best we can do.

**Comment by kevincox** [comment]
Ok, because I have just let the app auto-install when restoring my phone
every time and had no way of knowing this. I'm sure I'm not the only one.

**Comment by msfjarvis** [comment]
> Ok, because I have just let the app auto-install when restoring my phone every time and had no way of knowing this. I'm sure I'm not the only one.

I'm aware you're not alone but we literally cannot do anything else about it.

**Comment by cipherboy** [comment]
I'm seeing the same behavior on a newer version of the app. Could we get this reopened? It is fully reproducible every time on my particular device, and is quite annoying because there's no way to bypass the prompt outside of removing the autofill functionality -- you _have_ to select a password from the store and it prevents you from entering one manually. 

 - Device: Moto G6
 - OS: OEM's Android 9 / PPSS29.118-15-11-9 / Patch level Feb 1, 2020
 - App version: 1.7.2,

**Comment by msfjarvis** [comment]
The problem you're referring to only exists in the version of Autofill that is used on pre-Oreo devices. I use Autofill every single day across 3 devices and I simply cannot reproduce it. Would you be able to confirm that reinstalling does not fix it and a video recording of the bug in action so we can see what exactly is the problem?

**Comment by Rio6** [comment]
Hello, I'm having the same issue too. I've uploaded a screen recording here [https://youtu.be/rpFQyyEGcYM](https://youtu.be/rpFQyyEGcYM)

- Phone: Samsung J4
- Android Version: 9
- App Version: 1.8.1

(sorry for the lag, my phone doesn't handle screen recording well)

**Comment by FabianHenneke** [comment]
Reopening since @Rio6's video shows that this bug can be triggered by the modern Autofill service.

**Comment by msfjarvis** [comment]
I'll dive into this in the morning.

**Comment by jonathf** [comment]
Can confirm the same bug behavior as @Rio6 on the setup:

* Phone: Samsung Galaxy S10e
* Android version: 10
* App version: 1.8.1

**Comment by msfjarvis** [comment]
@jonathf @Rio6 can you both check your accessibility services and check if the Password Store service is still enabled?

**Comment by jonathf** [comment]
Yes, it is installed and enabled.

Note that the app works fine on most apps. It is just some that fails. In my case, I have problem with Chrome and Firefox.

**Comment by msfjarvis** [comment]
> Yes, it is installed and enabled.

That's the problem, it shouldn't be. We don't use the accessibility service on Android Oreo and above. Try disabling it manually and I'll push a patch to prompt users automatically.

> Note that the app works fine on most apps. It is just some that fails. In my case, I have problem with Chrome and Firefox.

That's just the flakiness of that old code at play.

**Comment by jonathf** [comment]
Disabling the accessibility service did the trick.
Thanks @msfjarvis, much appriciated.

**Comment by Rio6** [comment]
Yes that fixed it. Thanks!

**Comment by cipherboy** [comment]
Yes, @msfjarvis this fix works for me too. \o/ Sorry for bugging you!
