### ISSUE TITLE
[BUG] Cannot configure SSH git

### ISSUE THREAD

**Issue by milogert** [android-password-store/Android-Password-Store#777]
**Describe the bug**
When configuring git with SSH I enter the following information (personal information redacted):
* Username: `git`
* Server URL: `ssh.example.com`
* Port: `EMPTY`
* Repo path: `:passwords.git` OR `passwords.git` (both fail)
* Authentication Mode: SSH or OpenKeyChain. I didn't attempt password since I don't want to allow that in my repository.

When I press "Clone" it returns an error like
```
Error occurred during the clone operation, Message from jgit:
Invalid remote: origin
Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: ssh://git@ssh.example.com/:passwords.git: fatal: '/:passwords.git' does not appear to be a git repository
```

You will notice that it adds a `/` at the start of the repo path, probably from here: https://github.com/android-password-store/Android-Password-Store/blob/041cf00510a75042223d1857660fc7f1dff958ef/app/src/main/java/com/zeapo/pwdstore/git/BaseGitActivity.kt#L98

**To Reproduce**
1. Enter the data I did above.
2. Press "Clone"
3. See the error

**Expected behavior**
The repository should be successfully cloned.

**Device information (please complete the following information):**
 - Device: OnePlus 8 Pro
 - OS: Oxygen OS 10.5.6.IN11AA
 - App version: 1.7.2

**Additional context**
This worked with the older version of the application, but I am setting this up on a new phone and encountered this today.

Additionally, this happens with both an SSH key generated in-app and copied on to the server as well as with an OpenKeyChain GPG authentication key.

Finally, I tested this on my machine with `git clone git@ssh.example.com:passwords.git` and it successfully clones the repository.

**Comment by FabianHenneke** [comment]
Thanks for the detailed report!

We should probably remove a leading colon before adding the slash.
However, specifying the path without a leading colon should work (and does work for my repositories). Could you provide us with the error message you receive in that case?

**Comment by FabianHenneke** [comment]
We improved the error checking in the Git server configuration activity in #779, which should fix the issue you are seeing. The change should already be in the snapshot build available at https://dl.msfjarvis.dev/APS/. Please give it a try if you have the time and if it should still not work, post here or open a new issue.

**Comment by milogert** [comment]
Hey, thanks for such a rapid response! I tried out the snapshot you posted and everything synced down perfectly!

Also... Auto complete is 🤤 ❤️
