### ISSUE TITLE
[BUG] path cannot be relative

### ISSUE THREAD

**Issue by C0DK** [android-password-store/Android-Password-Store#784]
**Describe the bug**
When creating a new password store via SSH (so remote) you can input the `path name` however it has to be absolute, which kinda sucks. I'd love for it to be relative to my home repository.

**To Reproduce**
1. Open app with no remote store
2. create remote store with ssh
3. input a valid (relative) path

**Expected behavior**
It to just work :P 

**Screenshots**
Damn - i forgot to take a photo

**Device information (please complete the following information):**
 - App version [e.g. 1.7.2]

**Comment by msfjarvis** [comment]
In the current master you can set relative paths for default SSH port and require to have an absolute path for custom ports. Does that match what you expect?

**Comment by C0DK** [comment]
oic - i didn't realize that it would accept default ports, so i inputted 21 manually, which was the reason for my mistakes then.
