### ISSUE TITLE
[BUG] Git cloning over ssh uses the wrong repo path

### ISSUE THREAD

**Issue by Arax20** [android-password-store/Android-Password-Store#789]
As of version 1.8.0, I have been unable to perform any git operations with my password store. The application returns the following error whenever a pull/push/synchronize request is made:
![image](https://user-images.githubusercontent.com/45805601/82750587-f7085e80-9d65-11ea-90c2-cf38821db760.png)
As is visible in the screenshot, I believe the issue to be that there is a missing '/' in the path to the git repos. It should be `xerver@192.168.0.128:/home/xerver/git/password-store.git` instead of `xerver@192.168.0.128:home/xerver/git/password-store.git`. I am able to directly push and pull to the repo from termux and the legacy password-store app on the playstore so it likely isn't an issue with the repo itself.

**Comment by msfjarvis** [comment]
We're aware of the problem, it's a regression in the app. I am working on a fix https://github.com/android-password-store/Android-Password-Store/pull/788
