### ISSUE TITLE
[BUG] Cannot generate an SSH key before cloning

### ISSUE THREAD

**Issue by FabianHenneke** [android-password-store/Android-Password-Store#795]
**Describe the bug**
When Password Store is started for the first time (or after deleting a repository), it offers to "Clone from server". However, it is not possible to generate an SSH key at that time since the respective settings option is hidden.

**To Reproduce**
1. Reset Password Store.
2. Start it and select "Clone from server" or "Settings".

**Expected behavior**
Either of the two should offer to generate and view an SSH key. Ideally, this would be accessible right from the "Clone from server" flow.

**Comment by msfjarvis** [comment]
Does this dialog not show up for you? The generate button does work as intended here.

![Screenshot_20200526-120229_Password Store](https://user-images.githubusercontent.com/13348378/82867818-1d3a2400-9f49-11ea-891b-b762e2faf747.jpg)

**Comment by FabianHenneke** [comment]
> Does this dialog not show up for you? The generate button does work as intended here.

Nvm then, I didn't know you improved the flow so much. ;-)
