### ISSUE TITLE
[BUG] Unable to Autofill credentials in PayPal app

### ISSUE THREAD

**Issue by msfjarvis** [android-password-store/Android-Password-Store#820]
**Describe the bug**
It seems that some combination of bad behaviour from us and PayPal is causing the login fields to immediately get cleared after Autofill fills them in.

**To Reproduce**
1. Open the PayPal app
2. Tap on the email field, search for and select your password from the Autofill dialog box
3. Fields are populated for a split second before being cleared

**Expected behavior**
Email and password fields shouldn't be getting cleared automatically.

**Screenshots**

**Device information (please complete the following information):**
 - Device: Google Pixel 2
 - OS: R Developer Preview
 - App version: 1.9.0-SNAPSHOT from the Keystore branch

**Additional context**
N/A

**Comment by msfjarvis** [comment]
PayPal rightfully sets FLAG_SECURE so I can't screenrecord it :(

**Comment by FabianHenneke** [comment]
They clear their login form `onResume` and the Autofill framework apparently fills in our dataset before that happens. This breaks all Autofill apps that show authentication UI and don't require an additional confirmation step.

The only "workaround" I see would be to not return the fill-in data directly after the search flow, but rather add a new match dataset like the one we would show on subsequent login. This would require an additional tap for all users *and* still wouldn't work if there is an OpenKeychain, such as for keys on Yubikeys. I would thus like to label this issue won't fix. The way PayPal designed their login flow, I highly doubt they will listen to our "bug report" though.

**Comment by msfjarvis** [comment]
Yeah we're not gonna hack around their stupidity.
