### ISSUE TITLE
[BUG] Alert dialog is shown 2 times when synchronizing repository and doesn't save passphrase

### ISSUE THREAD

**Issue by Dioxo** [android-password-store/Android-Password-Store#828]
**Describe the bug**
*If not checked "remember password"*
The alert dialog when synchronizing the repository is shown twice, the second time it shows as "wrong passphrase".

*If checked "remember password"*
The alert dialog is shown once, but password is not saved.

It only happens with this option, if I try with pull or push, it doesn't display many times and saves the password (but i don't see any confirmation when adding wrong or correct password, not sure what this prompt does...)

**To Reproduce**

1. Clear saved passphrase for local ssh key (if there's any)
2. Try to sync 

**Expected behavior**
The alert dialog only shows once and the passphrase is saved if checked box.

**Device information (please complete the following information):**
 - Device: Redmi Note 8
 - OS: 9.0
 - App version : Recently pulled from repo.

**potential cause**
I tried to solve this problem but I couldn't because this error is generated since synchronization makes a call to pull and another to push. 
It's each call that generates the alert dialog. It's normal that the error "wrong passphrase" comes up because the application tries to make 2 consecutive calls and takes them as if it was a password error, but in reality the first one is a call to pull and the next one is to push. 

And because the second time the application considers that it was a "password error", it deletes the saved password.

I add captures of the application stack to justify why I think it's the push and pull calls that call this method of displaying the alert dialog. At the bottom left you can see that the first time is called by a pull command and the second time is the push command.

The firs time that the prompt is shown.
![3](https://user-images.githubusercontent.com/24482259/83538217-dc687f00-a4f5-11ea-801e-6a95e291af59.png)

The second time.
![4](https://user-images.githubusercontent.com/24482259/83538235-decad900-a4f5-11ea-870a-a60dc236b418.png)

**Comment by FabianHenneke** [comment]
@msfjarvis I'll see whether I can fix this independent of the answer to the following question, but do we know why JGit chooses to authenticate twice for a git pull followed by a git push? If we could resolve that, we would have both solved this issue and saved a roundtrip to the server.

**Comment by msfjarvis** [comment]
> @msfjarvis I'll see whether I can fix this independent of the answer to the following question, but do we know why JGit chooses to authenticate twice for a git pull followed by a git push? If we could resolve that, we would have both solved this issue and saved a roundtrip to the server.

It's running multiple commands separately [[reference](https://github.com/android-password-store/Android-Password-Store/blob/43ae4bbdb7c189e614f5f7af0a2dc53e70a741bd/app/src/main/java/com/zeapo/pwdstore/git/SyncOperation.kt#L39-L45)]. Not sure if this can be avoided, will investigate.

**Comment by FabianHenneke** [comment]
@Dioxo Could you check whether #829 fixes the issue for you? It should both fix the retry issue and remember the password for the duration of the entire sync operation.

@msfjarvis Are we okay with remembering the password for that long? We did previously and are now taking better care to clear it, but I still want to get your ok.

**Comment by msfjarvis** [comment]
> @msfjarvis Are we okay with remembering the password for that long? We did previously and are now taking better care to clear it, but I still want to get your ok.

I think it's a perfectly reasonable duration, no issues with it.

**Comment by Dioxo** [comment]
@FabianHenneke it works almost perfect with the fix that you did, the only problem is that the sync contains 2 operations (pull and push), so if i cancel the alert dialog when sync, it will cancel for the pull call, but it will ask it show again the alert dialog for the push call.

I would like to ask you what's the idea of this Alert Dialog? even if i type anything or cancel it, it will pull or push no matter what.

**Comment by FabianHenneke** [comment]
> @FabianHenneke it works almost perfect with the fix that you did, the only problem is that the sync contains 2 operations (pull and push), so if i cancel the alert dialog when sync, it will cancel for the pull call, but it will show again the alert dialog for the push call.

I would like to call that intended behavior for the purpose of that dialog. It's more of a question whether the sync operation should or should not run the push after the pull fails. @msfjarvis What do you think?
 
> I would like to ask you what's the idea of this Alert Dialog? even if i type anything or cancel it, it will pull or push no matter what.

Could you provide me with steps to reproduce that? When I cancel the dialog, I get an error about SSHJ failing to read my key file - which makes sense as it can't read the private key without its passphrase.

**Comment by Dioxo** [comment]
> I would like to call that intended behavior for the purpose of that dialog. It's more of a question whether the sync operation should or should not run the push after the pull fails. @msfjarvis What do you think?

For me, the sync is a atomic operation, even if it has to do a pull and after the push, if one of them fails, it would be usefull to have a error message.

>Could you provide me with steps to reproduce that? When I cancel the dialog, I get an error about SSHJ failing to read my key file - which makes sense as it can't read the private key without its passphrase.

I didn't do something different, the first time when cloning the repo i dont check "remember passphrase", and when i manually do a pull or push, if i cancel the alert dialog, it just do the action ignoring the fact that i canceled it.

**Comment by Dioxo** [comment]
Or even if i write anything and press "OK", it continues to pull and push. That's why  i ask about the funcionality about this because the operations work no matter what I write or do in the alert dialog.

**Comment by FabianHenneke** [comment]
> > Could you provide me with steps to reproduce that? When I cancel the dialog, I get an error about SSHJ failing to read my key file - which makes sense as it can't read the private key without its passphrase.
> 
> I didn't do something different, the first time when cloning the repo i dont check "remember passphrase", and when i manually do a pull or push, if i cancel the alert dialog, it just do the action ignoring the fact that i canceled it.

That is pretty weird. Are you using SSH password authentication or public key authentication with a passphrase on the key file? If you look into the settings, is there an option for clearing the stored passphrase?

**Comment by FabianHenneke** [comment]
> Or even if i write anything and press "OK", it continues to pull and push. That's why i ask about the funcionality about this because the operations work no matter what I write or do in the alert dialog.

Did you confirm that it really updates the repo/pushes the changes to the server? We had an issue until recently that would prevent any error from being shown even if the push or pull failed. Could you retry after pulling in the recent changes from the PS repo?

**Comment by Dioxo** [comment]
>Did you confirm that it really updates the repo/pushes the changes to the server?
Yeah, i confirmed it. I added some passwords from my pc and then pushed, then pull from my phone and canceled the pull operation, it did it anyways, it happens the same when writing anything or leaving blank space inside the dialog and confirm the operation.

**Comment by Dioxo** [comment]
I also realised that, with a fresh install, when cloning, after importing the SSH key, it will show the dialog, if i cancel it, APS will clone the repo anyway.

I think the dialogue is not being taken into account and it doesn't have any effect to add something in it or cancel the dialog.

**Comment by Dioxo** [comment]
>If you look into the settings, is there an option for clearing the stored passphrase?

Yeah, there's the option.

**Comment by FabianHenneke** [comment]
> > If you look into the settings, is there an option for clearing the stored passphrase?
> 
> Yeah, there's the option.

What happens if you use that option once and then repeat your tests? Does the dialog still not accept the server operations?

It is conceivable that the dialog shows up even though the stored password is used, but I don't know yet how this could happen.

**Comment by FabianHenneke** [comment]
@msfjarvis As in the screenshots above, some of the translations describe "Remember passphrase" as "insecure". I think that we should remove those parts of the translations.

**Comment by msfjarvis** [comment]
> @msfjarvis As in the screenshots above, some of the translations describe "Remember passphrase" as "insecure". I think that we should remove those parts of the translations. Whether or not storing the passphrase is "secure" depends on the particular usecase and cannot be decided by us. On a modern phone with a screen lock, it's probably fine for almost all users.

Yeah we have a lot of translations that are outdated at this point. Maybe I should just get rid of all of them and migrate to Crowdin while we're at that...

**Comment by Dioxo** [comment]
>What happens if you use that option once and then repeat your tests? Does the dialog still not accept the server operations?

@FabianHenneke I deleted the stored passphrase, then a pull from repository to see if it works and the dialog is shown as usual, but if i cancel the dialog, the pull call is still executed.

I'll try to see this myself in the debugger to find why it continues the action even if it was cancelled. But normally what's the expected behavior ? I have to use which passphrase and there's a error message if it wasn't the right passphrase? or how is this dialog handled?

**Comment by FabianHenneke** [comment]
> > What happens if you use that option once and then repeat your tests? Does the dialog still not accept the server operations?
> 
> @FabianHenneke I deleted the stored passphrase, then a pull from repository to see if it works and the dialog is shown as usual, but if i cancel the dialog, the pull call is still executed.
> 
> I'll try to see this myself in the debugger to find why it continues the action even if it was cancelled. But normally what's the expected behavior ? I have to use which passphrase and there's a error message if it wasn't the right passphrase? or how is this dialog handled?

If you cancel the dialog, it will try to use the empty string as the passphrase. If your SSH key was created with encryption, but an empty passphrase, this might make the pull operation go though even if you hit cancel. But in that case, typing "foobar" in the dialog and confirming it should definitely lead to an error.

In general, the dialog will show up precisely if your SSH key is encrypted with a passphrase. If it is and you never supply your passphrase to Password Store, I could only see the pull operation succeeding if your server does not require authentication.

**Comment by Dioxo** [comment]
I see what you mentione @FabianHenneke , i tried with a SSH key with a passphrase and know the dialog works normal, so i think the problem is when having keys without passphrase.

And i don't know if it's good to continue the operation when the user cancels it because APS launches an error like `The checkInts differed, the key was not correctly decoded`. and like you said, if the ssh key doesn't have a passphrase, cancel the dialog could generate the continuation of the operation, and i don't think that's ok to do.

But i don't understand why if i put a ssh key that doesn't have passphrase and write anything in the dialog, it keeps working. Could you try this to see if it also happens to you?

**Comment by FabianHenneke** [comment]
I will investigate this.

**Comment by FabianHenneke** [comment]
> I see what you mentione @FabianHenneke , i tried with a SSH key with a passphrase and know the dialog works normal, so i think the problem is when having keys without passphrase.
> 
> And i don't know if it's good to continue the operation when the user cancels it because APS launches an error like `The checkInts differed, the key was not correctly decoded`. and like you said, if the ssh key doesn't have a passphrase, cancel the dialog could generate the continuation of the operation, and i don't think that's ok to do.
> 
> But i don't understand why if i put a ssh key that doesn't have passphrase and write anything in the dialog, it keeps working. Could you try this to see if it also happens to you?

I cannot reproduce this, neither with an SSH key generated in the app nor with one generated via `ssh-keygen -t rsa` or `ssh-keygen -t ed25519` on my computer.

Could you provide more details on how you generated the SSH key that leads to the issue you describe? Ideally, could you generate a new key pair in the same way for testing purposes and paste it here?

**Comment by Dioxo** [comment]
After creating another key pair and deleting the application data, this problem no longer appears, which is rare because I haven't changed anything to my configuration on my server. 
I don't know if it was a problem with my previous keys, but I think it was magically solved.
I think i can close this issue because your PR works perfect, thanks.

One last thing before closing, is it okay to show an error when canceling the dialog? Because if i'm canceling something, why am i getting a errot because failed to decrypt my passphrase.

**Comment by FabianHenneke** [comment]
> One last thing before closing, is it okay to show an error when canceling the dialog? Because if i'm canceling something, why am i getting a errot because failed to decrypt my passphrase.

Could you check whether https://github.com/android-password-store/Android-Password-Store/pull/833 resolves this for you?

**Comment by Dioxo** [comment]
Fixes in #833 and #829 works well and solve this issue, so closing...
