### ISSUE TITLE
[BUG] Tabs in extra content not displayed

### ISSUE THREAD

**Issue by chschlue** [android-password-store/Android-Password-Store#830]
**Describe the bug**
Extra content view does not display tabs

**To Reproduce**
1. Open password entry containing extra content separated by tabs
2. Enjoy missing whitespace

**Expected behavior**
```
a	b	c
```

**Screenshots**
not allowed

**Device information (please complete the following information):**
 - Device: Nokia 7.2
 - OS: Android (One) 10
 - App version 1.8.1

**Comment by Dioxo** [comment]
I think its possible to just do a replace to add 4 spaces when displaying the extra content like 
                               
 `entry.extraContentWithoutUsername.replace("\t","\u0020\u0020\u0020\u0020")
`

but it will add spaces inside the extra content, i'm not sure if it's good to change the tab for spaces and saves them. Or only change the tab for spaces when displaying but in reality they are still tabs.

**Comment by chschlue** [comment]
@Dioxo 
Perhaps the proper solution is much simpler and doesn't require a workaround.
Android UI can handle tabs properly, after all:
![Screenshot_20200603-181303-01](https://user-images.githubusercontent.com/40901018/83662380-b4495080-a5c7-11ea-985c-70f67cc7de9a.jpeg)
(Text with `\t` pasted into Gmail, for example, and that's not even a monospace font)

**Comment by msfjarvis** [comment]
> @Dioxo
> Perhaps the proper solution is much simpler and doesn't require a workaround.

Yeah there's no hacks needed here, if OpenKeychain isn't mangling tabs then it should be a trivial fix.

**Comment by msfjarvis** [comment]
Tried a bunch of things but I'm not really getting anywhere. OpenKeychain apparently 'normalizes' all tab characters to spaces based on my analysis of the Unicode codepoints of what we get back from decryption.

**Comment by msfjarvis** [comment]
Closing as part of [issue tracker cleanup](https://github.com/android-password-store/Android-Password-Store/discussions/1836).
