### ISSUE TITLE
More secure kex & MAC

### ISSUE THREAD

**Issue by tBKwtWS** [android-password-store/Android-Password-Store#832]
After running some ssh-audit tools, I removed some less secure key exchange algorithms and message authentication codes on my servers SSH config. This broke the Android-Password-Store app, no longer being able to authenticate.

The server logs shows what kex & MAC are being offered by the Android Password Store application.
```
sshd: Unable to negotiate: no matching key exchange method found. Their offer: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
sshd: Unable to negotiate: no matching MAC found. Their offer: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
```

I would be nice if one of the following could be supported:
```
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512,diffie-hellman-group14-sha256
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
```

After reading [this](https://tools.ietf.org/id/draft-ietf-curdle-ssh-kex-sha2-09.html) already outdated IETF draft on kex, I understood the most secure choice would be to enable hex ecdh-sha2-nistp384 & MAC hmac-sha2-256.

However [ssh-audit](https://github.com/arthepsy/ssh-audit) a tool last updated in 2016 flags those as insecure, with an error on the kex having weak elliptic curves & the MAC being encrypt-and-MAC mode.

I won't pretend to be a security researcher and might have missed some obvious solution. Or might just have been led astray by this audit tool.

But it would seem beneficial to support some modern and strong key & MAC. To be ready for the future as some less secure algorithms are being slowly phased out. Or just to be as secure as we can.
Also it would be nice if ed25519 ssh-keys would be supported, as importing it fails. (I saw the comment on another issue  it not supported right now)
Is there anything I can do to assist? (Perhaps the ssh is solved by an upstream component where  could create an issue?)

Also if I have misunderstood, or am to security paranoid, please tell me so.

**Comment by msfjarvis** [comment]
A quick search for Keyex & MAC in the issues section would have taken you to https://github.com/android-password-store/Android-Password-Store/issues/448, which was closed after we implemented support for newer, more secure algorithms. You're not excessively paranoid, just jumped the gun on creating the issue :)

**Comment by tBKwtWS** [comment]
Darn, I only read all open issues. Next time I will use the search box.

Thanks!!!
