### ISSUE TITLE
Autocomplete respect subdomains

### ISSUE THREAD

**Issue by Schueni1** [android-password-store/Android-Password-Store#837]
I have multiple passwords for a single domain.
- a password for _cloud.example.com/user_ 
- a password for _gitea.example.com/user_ 
- and so on...

When I am in Firefox on one of these subdomains and I am prompted for a password, I always have to click on _search in store_. Otherwise it will just select the first entry that contains _example.com_.

Is this fixable?

**Comment by FabianHenneke** [comment]
Autofill uses the public suffix +1 as the reference for matches, which is`example.com` in your case and would be e.g. `someone.github.io` since `github.io` is a public suffix. This is the "correct" choice for most websites that are neither personal nor work domains.

> Otherwise it will just select the first entry that contains _example.com_.

Could you elaborate on this a bit more? Does this selection happen automatically for you? 

In a similar case, I would simply create two Autofill matches for `example.com` with filenames "Cloud" and "Git", putting a username in the encrypted extra contents. Would this work for you?

**Comment by Schueni1** [comment]
I tested a little more. Once I selected the correct password file for the given subdomain, it seems to remember it. Now the correct password for a given ```subdomain.domain.com``` is always at the top of the list.  
Though it is still a bit confusing that all proposed options look the same. All of them are of the form ```example.com/user```.  
The subdomain is not shown. If the usernames are the same I always have to trust, that the first entry is the correct one.
I think it would be nice to also display the subdomain.

**Comment by FabianHenneke** [comment]
Not showing (and storing) the subdomain has been a conscious decision on my part, but of course we can rethink this decision.

Most public sites use subdomains for their login page, but may even have multiple such pages on different subdomains. Thanks to the Public Suffix List, there is a way to assign to all these pages a unique and stable domain that is consistent with what browsers and other password managers are doing. It also serves to restrict focus to the part of the domain that is most relevant in trust decisions, which helps users detect phishing attempts.

Given that the current issue should mostly be relevant for personal and work sites, which are frequently used and do not pose a risk for credential leakage, I personally find the workaround of putting information about the subdomain in the file/folder name and optionally moving the username into the encrypted extras to be sufficient. I would thus prefer to leave this as is and keep Autofill simple.

@msfjarvis @Skrilltrax What do you think?

**Comment by FabianHenneke** [comment]
> I see the point here, since I have a few apps hosted on subdomains and thus seeing a list of `user: msfjarvis, site: msfjarvis.dev` on each of them effectively makes Autofill assignments useless and I have to search every single time. If this is relatively easy to do I would really love to have this change at least as an opt-in feature at assignment time.

Also @Schueni1: Do you have a picture in mind of how this should work? When would you like to decide that the particular entry should be associated to the full domain? Should the entry only *show* the full domain or should it also *match* (only?) the full domain? 

Please don't feel deterred by all these questions, it's just that getting this right without hearing a few use cases first seems unlikely.

**Comment by Schueni1** [comment]
As you said earlier, matching only the fulldomain might be an issue with big corp sites. On big corp sites I would just have an entry like ```schmoogle.com/user```
. If I am on service.schmoogle.com I expect it to still show the entry for this site.

For my selfhosted services I have a username/password for each subdomain. In my humble opinion there are two options to handle this:

• show all entries for the domain and let me choose.  
• Only show the entry with the matching subdomain. If there is no entry for this subdomain, then just list all entries for the domain.

In both cases it would be nice to show the subdomain.  
PS: I like the second option more :wink:

**Comment by Schueni1** [comment]
Actually you first proposed option of having two autofill matches would work for me as well. I would just have to reorganize my password structure.

**Comment by Schueni1** [comment]
Actually putting the username inside the encrypted password-file solves the problem for me.

**Comment by FabianHenneke** [comment]
> Actually putting the username inside the encrypted password-file selecting the third password file organization scheme without actually reordering the the file structure solves the problem for me.
> 
> In summary this works for me:
> 
> * Now I have this file structure `work/(subdomain).example.org/john@doe.org`
> * But selected this scheme in the app `work/example.org/john@doe.org/password.gpg`
> * and I added the username to the encrypted file like so: `login:username`
> 
> This way autofill always shows me the subdomain and I can be sure I selected the correct entry.

Glad that this works for you, but it sounds like a bit of a hack ;-)

How about the following simple solution: We add a preference that lets users specify a list of domains they would like to be considered as additional public suffixes. This way, we don't have to change any of the actual autofill UI and will preserve the "correct" default. What do you think?

@msfjarvis Do you know a good way to let users manage a set of strings in a preference screen?

**Comment by msfjarvis** [comment]
> > Actually putting the username inside the encrypted password-file selecting the third password file organization scheme without actually reordering the the file structure solves the problem for me.
> > In summary this works for me:
> > 
> > * Now I have this file structure `work/(subdomain).example.org/john@doe.org`
> > * But selected this scheme in the app `work/example.org/john@doe.org/password.gpg`
> > * and I added the username to the encrypted file like so: `login:username`
> > 
> > This way autofill always shows me the subdomain and I can be sure I selected the correct entry.
> 
> Glad that this works for you, but it sounds like a bit of a hack ;-)
> 
> How about the following simple solution: We add a preference that lets users specify a list of domains they would like to be considered as additional public suffixes. This way, we don't have to change any of the actual autofill UI and will preserve the "correct" default. What do you think?
> 
> @msfjarvis Do you know a good way to let users manage a set of strings in a preference screen?

Don't think there is any. Best bet would be an EditTextPreference backed by a StringSet as opposed to a String.

**Comment by Schueni1** [comment]
> How about the following simple solution: We add a preference that lets users specify a list of domains they would like to be considered as additional public suffixes. This way, we don't have to change any of the actual autofill UI and will preserve the "correct" default. What do you think?

Sounds good to me!
