### ISSUE TITLE
Allow the user to disable git

### ISSUE THREAD

**Issue by zeapo** [android-password-store/Android-Password-Store#86]
This is useful for external folders

**Comment by kevincox** [comment]
I'm glad this is an open issue. I use the app without git and when creating a password it crashes while trying to call jgit. It would be really nice to be able to generste passwords from the app.

**Comment by zeapo** [comment]
it will take some time, but it's work in progress, see #121

**Comment by kevincox** [comment]
:+1:

**Comment by TheLastProject** [comment]
Ah, now I know why the app crashes with a git error every single time I move a password without being able to figure out how to tell it I don't use git in the first place. Glad there is an issue for this yeah

**Comment by hughdavenport** [comment]
Just wondering whether this should be closed as #121 is now merged.

**Comment by raindev** [comment]
@hughdavenport, #121 is closed, but not merged.

**Comment by zeapo** [comment]
@raindev because I was not happy with what I've written, so I threw it away

The base architecture has to be re-tought and rewritten before we could implement non-git repositories correctly.

**Comment by msfjarvis** [comment]
Existing non-git stores behave correctly in the app, and there are no plans to add support for creating non-git stores from the app so this issue is resolved.
