### ISSUE TITLE
Autofill does not work as intended with IceCatMobile

### ISSUE THREAD

**Issue by divad42** [android-password-store/Android-Password-Store#869]
Instead of suggesting a password based on the url, in [IceCatMobile](https://f-droid.org/en/packages/org.gnu.icecat/) it just suggests passwords named "IceCatMobile".

**Comment by msfjarvis** [comment]
Please don't remove the issue template while reporting bugs, we require it for a reason.

**Comment by FabianHenneke** [comment]
This is the default behavior with browsers for which we have not explicitly enabled support. I reviewed the situation around `org.gnu.icecat` and consider it a reasonable addition to our list of supported browsers (see #871).

@divad42 Are you able to test whether #871 resolves the issue for you? If you are not comfortable with Android Studio, we could merge it and provide you with an APK of the dev version.

**Comment by FabianHenneke** [comment]
@divad42 We have added IceCat to the list of trusted browsers. Could you confirm that the issue is resolved for you with [this APK](https://dl.msfjarvis.dev/APS/) that contains the change?

**Comment by divad42** [comment]
It works perfectly!  Thank you so much!

**Comment by FabianHenneke** [comment]
Great!

I take that as an independent confirmation of IceCat's certificate hash, so we've done our due diligence here.
